### PR TITLE
libvirt.tests: Fix storage_discard bugs.

### PR DESCRIPTION
**Pull request by yumingfei**
* Create lvm for given block device too.
 * Delete lvthin before vgthin in cleanup
 * Add sleeping time to wait for fstrim operation

Rely on https://github.com/autotest/autotest/pull/905

Signed-off-by: Yu Mingfei <yumingfei@cn.fujitsu.com>

### CODE REVIEW

**Comment by yumingfei** [comment]
Travis CI is failed because PR905 is not merged.

**Comment by will-Do** [comment]
Please rebase your patch as the dependent PR already merged

**Comment by yumingfei** [comment]
The travis error shows that my change in autotest hasn't been distributed to released autotest version.
```
$ sudo apt-get -y --force-yes install autotest
```
So maybe we have to release a new autotest version to let it go.
@lmr , do you have any idea?

**Comment by lmr** [comment]
Well, I will release a new version of autotest after I fix the PEP8 problems, then.

**Comment by yumingfei** [comment]
It seems that some other errors still exist in this PR, so closing it and transmitting to somebody else. :(

**Pull request closed without merging**
