### PR TITLE
libvirt: Add test case for cpu-models command

### PR DESCRIPTION
**Pull request by will-Do**
Signed-off-by: Yanbing Du <ydu@redhat.com>

### CODE REVIEW

**Comment by will-Do** [comment]
BTW, this PR dependent on autotest/virt-test#2010
Tests pass on libvirt-1.2.9.1-2.fc20.x86_64(2 cases SKIP as remote host not config):
```
# ./run -t libvirt --test virsh.cpu_models -k --keep-image-between-tests
Running setup. Please wait...
SETUP: PASS (4.42 s)
DATA DIR: /home/ydu/Work/virt-test/shared/data
DEBUG LOG: /home/ydu/Work/virt-test/logs/run-2015-02-16-23.08.00/debug.log
TESTS: 6
(1/6) type_specific.ydu-libvirt.virsh.cpu_models.positive_test.local_host.auto_get_arch: PASS (10.85 s)
(2/6) type_specific.ydu-libvirt.virsh.cpu_models.positive_test.local_host.specific_arch: PASS (10.81 s)
(3/6) type_specific.ydu-libvirt.virsh.cpu_models.positive_test.remote_host.auto_get_arch: SKIP
(4/6) type_specific.ydu-libvirt.virsh.cpu_models.positive_test.remote_host.specific_arch: SKIP
(5/6) type_specific.ydu-libvirt.virsh.cpu_models.negative_test.invalid_arch: PASS (10.74 s)
(6/6) type_specific.ydu-libvirt.virsh.cpu_models.negative_test.invalid_option: PASS (10.86 s)
TOTAL TIME: 64.85 s (01:04)
TESTS PASSED: 4
TESTS FAILED: 0
TESTS SKIPPED: 2
SUCCESS RATE: 100.00 %

**Comment by waynesun09** [comment]
Run with failures, seems missed a virt-test depend PR, @will-Do please help check.
```
16:52:41 INFO | ERROR type_specific.io-github-autotest-libvirt.virsh.cpu_models.positive_test.local_host.auto_get_arch -> TestError: Fail to get guest arch list of the host supported:
'CapabilityXML' object has no attribute 'get_os_arch_machine_map'
```

**Comment by will-Do** [comment]
Yes, there's an other depend PR which already merged: https://github.com/autotest/virt-test/pull/2036

**Comment by waynesun09** [comment]
@will-Do the function name changed to 'get_guest_capabilities', so need to update the test module here.

**Comment by will-Do** [comment]
Thanks, will update it

**Comment by waynesun09** [comment]
ACK and merging now.

**Pull request merged**
