### PR TITLE
max_vcpus: Fix an issue in negative_test.ioapic_iommu

### PR DESCRIPTION
**Pull request by Yingshun**
The max vcpu was changed, so the guest vcpu setting should be
updated.

Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Comment by Yingshun** [comment]
**Before fix:**
```
# avocado run --vt-type libvirt --vt-machine-type q35 max_vcpus.negative_test.ioapic_iommu --vt-connect-uri qemu:///system
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 87e46ef0db9a45e61457b425020d598183ad0b98
JOB LOG    : /root/avocado/job-results/job-2021-02-22T22.03-87e46ef/job.log
 (1/1) type_specific.io-github-autotest-libvirt.max_vcpus.negative_test.ioapic_iommu: FAIL: Expect should fail with one of unsupported configuration: Maximum CPUs greater than specified machine type limit|exceeds the maximum cpus supported, but succeeded: Domain 'avocado-vt-vm1' defined from /tmp/xml_utils_temp_z8snoj3n.xml\n\n\n (7.72 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```


**After fix:**
```
JOB ID     : 21cdee84aaf84885a5a8bcbb4d34d29b1c7f1e0e
JOB LOG    : /root/avocado/job-results/job-2021-02-22T22.11-21cdee8/job.log
 (1/1) type_specific.io-github-autotest-libvirt.max_vcpus.negative_test.ioapic_iommu: PASS (7.50 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Review by chloerh — COMMENTED** [review]
The fix seems fine, but would it affect tests on older libvirt?

**Comment by Yingshun** [comment]
> The fix seems fine, but would it affect tests on older libvirt?

No, it wouldn't. The max value of vcpu on old libvirt version is smaller than that on current version, so it's ok.

**Comment by chloerh** [comment]
Oh, sorry that I didn't read more carefully, seems good.

**Review by chloerh — APPROVED** [review]

**Pull request merged**
