### PR TITLE
Fix nvme case failure due to pre-existed partitions on nvme device

### PR DESCRIPTION
**Pull request by chunfuwen**
Fix nvme case failure due to pre-existed partitions on nvme device
clean up nvme device partitions before attaching to VM

### CODE REVIEW

**Comment by chunfuwen** [comment]
previously failed logs:

2023-03-30 02:02:45,495 stacktrace       L0039 ERROR| 
2023-03-30 02:02:45,495 stacktrace       L0041 ERROR| Reproduced traceback from: /var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py:274
2023-03-30 02:02:45,496 stacktrace       L0045 ERROR| Traceback (most recent call last):
2023-03-30 02:02:45,496 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virtual_disks/virtual_disks_nvme.py", line 140, in run
2023-03-30 02:02:45,496 stacktrace       L0045 ERROR|     test.fail("Attached 1 virtual disk but got %s." % len(new_disks))
2023-03-30 02:02:45,496 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/core/test.py", line 979, in fail
2023-03-30 02:02:45,496 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2023-03-30 02:02:45,496 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Attached 1 virtual disk but got 3.

**Comment by chunfuwen** [comment]
the result is under testing

**Comment by chunfuwen** [comment]
Command 'virsh list' finished with 0 after 0.026221491s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.nvme.hotplug.attach_nvme

**Review by cliping — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
