### PR TITLE
Fixup virsh_net_dhcp_leases testcase

### PR DESCRIPTION
**Pull request by bssrikanth**
This patch will resolve two issues:
1. `IndexError: list index out of range` hit by testcases which are trying to delete nic entries of vm instance.
2. Guests unable to detect the hotplggged nic, since nics were hotplugged too early.. before vm was fully started.

Signed-off-by: Srikanth Aithal <sraithal@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by bssrikanth** [comment]
Before fix:

Issue 1:

avocado run --vt-type libvirt --vt-config /home/srikanth/avocado-fvt-wrapper/config/tests/guest/libvirt/network_srikanth.cfg --vt-only-filter 'Fedora.24.ppc64le'
JOB ID : ee98aacd2ed1e34ab5bdb7714fd6e87823627d1b
JOB LOG : /home/srikanth/avocado-fvt-wrapper/results/job-2016-10-12T09.38-ee98aac/job.log
TESTS : 3
(1/3) guest_import.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-qemu.unattended_install.import.import.default_install.aio_native: PASS (69.60 s)
(2/3) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.negative_test.invalid_net: PASS (3.49 s)
(3/3) guest_remove.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.remove_guest.without_disk: PASS (1.47 s)
RESULTS : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 74.56 s
JOB HTML : /home/srikanth/avocado-fvt-wrapper/results/job-2016-10-12T09.38-ee98aac/html/results.html

In above run observe that virsh.net_dhcp_leases.negative_test.invalid_net: PASSED .. same will fail when we add one more test before it which manipulates the original nics..

avocado run --vt-type libvirt --vt-config /home/srikanth/avocado-fvt-wrapper/config/tests/guest/libvirt/network_srikanth.cfg --vt-only-filter 'Fedora.24.ppc64le'
JOB ID : 83e86a7bfacd816ab771a73c07ab227c9a655191
JOB LOG : /home/srikanth/avocado-fvt-wrapper/results/job-2016-10-12T09.41-83e86a7/job.log
TESTS : 4
(1/4) guest_import.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-qemu.unattended_install.import.import.default_install.aio_native: PASS (66.58 s)
(2/4) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.negative_test.invalid_option: PASS (4.88 s)
(3/4) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.negative_test.invalid_net: ERROR (3.36 s)
(4/4) guest_remove.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.remove_guest.without_disk: PASS (1.32 s)
RESULTS : PASS 3 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 76.14 s
JOB HTML : /home/srikanth/avocado-fvt-wrapper/results/job-2016-10-12T09.41-83e86a7/html/results.html

DEBUG log of virsh.net_dhcp_leases.negative_test.invalid_net: ERROR's points to below error:

09:42:37 ERROR| File "/home/srikanth/avocado-fvt-wrapper/data/avocado-vt/test-providers.d/downloads/powerkvm-libvirt/libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py", line 135, in run
09:42:37 ERROR| vm.del_nic(idx)
09:42:37 ERROR| File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-41.0-py2.7.egg/virttest/virt_vm.py", line 832, in del_nic
09:42:37 ERROR| nic = self.virtnet[nic_index_or_name]
09:42:37 ERROR| File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-41.0-py2.7.egg/virttest/utils_net.py", line 2340, in getitem
09:42:37 ERROR| return super(VMNet, self).getitem(index_or_name)
09:42:37 ERROR| IndexError: list index out of range
09:42:37 ERROR|
09:42:37 ERROR| Traceback (most recent call last):

09:42:37 ERROR| File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-41.0-py2.7.egg/avocado_vt/test.py", line 434, in _run_avocado
raise test_exception

09:42:37 ERROR| IndexError: list index out of range

Issue 2:

Currently we are not waiting for vm to boot fully before hotplugging nic. 

Error shows that guest was not able to detect the hotplugged nic.

02:45:12 ERROR|   File "/home/srikanth/avocado-fvt-wrapper/data/avocado-vt/test-providers.d/downloads/powerkvm-libvirt/libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py", line 80, in f
02:45:12 ERROR|     return utils_net.get_guest_ip_addr(session, mac_addr)
02:45:12 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-41.0-py2.7.egg/virttest/utils_net.py", line 1393, in get_guest_ip_addr
02:45:12 ERROR|     raise IPAddrGetError(mac_addr, err)
02:45:12 ERROR| IPAddrGetError: Get guest nic ['9a:ba:60:64:c9:6d'] IP address errorerror info: Failed to determine interface name with mac 9a:ba:60:64:c9:6d



After patch applied, all testcase failuers are handled:

 (1/7) guest_import.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-qemu.unattended_install.import.import.default_install.aio_native: PASS (62.59 s)
 (2/7) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.positive_test.attach_interface_before_vm_start: PASS (43.68 s)
 (3/7) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.positive_test.attach_interface_after_vm_start: PASS (69.58 s)
 (4/7) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.negative_test.invalid_option: PASS (2.87 s)
 (5/7) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.negative_test.invalid_net: PASS (4.31 s)
 (6/7) guest_network.net_virsh_attach_detach_interface_matrix.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.virsh.net_dhcp_leases.negative_test.invalid_mac: PASS (5.26 s)
 (7/7) guest_remove.qemu.qcow2.virtio_scsi.smp2.virtio_net.Fedora.24.ppc64le.powerkvm-libvirt.remove_guest.without_disk: PASS (1.54 s)
RESULTS    : PASS 7 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 189.83 s
JOB HTML   : /home/srikanth/avocado-fvt-wrapper/results/job-2016-10-17T06.22-d9f7a15/html/results.html

**Comment by bssrikanth** [comment]
@will-Do please let me know your reviews here.

**Comment by will-Do** [comment]
@bssrikanth 
Sorry, not check github these days.
Yes, this is the problem I tried to fix in https://github.com/autotest/tp-libvirt/pull/887, but it's not 100% stable yet, as the new NIC may not assign IP address. I was thinking we should try to login VM by serial:
```
wait_for_login(new_nic, serial=True)
```
I just recreate the fix in https://github.com/autotest/tp-libvirt/pull/894, could you please help to try this patch?

**Comment by bssrikanth** [comment]
@will-Do with #894 patch we will be able to overcome issue 1 since we are not removing original nics. So now question is should we have 1 or 2:
1. Have the testcase flow as-is, add the restore part from this PR
2. Change the flow, dont remove the original nics. #894. 

Issue 2 reported in this PR would still need to wait until VM comes up fully before hotplugging the nic.

**Comment by bssrikanth** [comment]
Issue 2 fix has been included in #894. Closing this one. Thanks @will-Do

**Pull request closed without merging**
