### PR TITLE
Offline migration

### PR DESCRIPTION
**Pull request by balamuruhans**
Added offline migration test case

### CODE REVIEW

**Comment by dzhengfy** [comment]
@balamuruhans ,
Regarding offline migration, it can handle both active guest and inactive guest. I guess this PR only covers the active guest.  If True, I suggest make the offline test complete with the two scenarios. If I missed something, please correct me. Thanks.

**Comment by balamuruhans** [comment]
@dzhengfy True. Sure, I will add to cover both the scenarios.

**Comment by balamuruhans** [comment]
@dzhengfy , I have added both scenarios and tested it. Please find below for results,

# avocado run --vt-type libvirt --vt-config data/avocado-vt/backends/libvirt/cfg/migrate.cfg --vt-no-filter 'network user macvtap' --vt-only-filter 'RHEL.7.2.ppc64le qcow2'
JOB ID     : 0600d997a52a697b5adb29b0ac9ae024ead4e077
JOB LOG    : /var/lib/libvirt/images/bala/avocado-fvt-wrapper/results/job-2016-09-26T09.05-0600d99/job.log
TESTS      : 4
 (1/4) guest_import.qemu.qcow2.scsi.smp2.spapr-vlan.RHEL.7.2.ppc64le.powerkvm-qemu.unattended_install.import.import.default_install.aio_native: PASS (55.77 s)
 (2/4) guest_migration.qemu.qcow2.scsi.smp2.spapr-vlan.RHEL.7.2.ppc64le.powerkvm-libvirt.virsh.migrate.there_offline.with_inactive_guest: PASS (101.81 s)
 (3/4) guest_migration.qemu.qcow2.scsi.smp2.spapr-vlan.RHEL.7.2.ppc64le.powerkvm-libvirt.virsh.migrate.there_offline.with_active_guest: PASS (104.78 s)
 (4/4) guest_delete.qemu.qcow2.scsi.smp2.spapr-vlan.RHEL.7.2.ppc64le.powerkvm-libvirt.remove_guest.without_disk: PASS (1.36 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /var/lib/libvirt/images/bala/avocado-fvt-wrapper/results/job-2016-09-26T09.05-0600d99/html/results.html
TESTS TIME : 263.72 s

**Comment by balamuruhans** [comment]
@dzhengfy @waynesun09 please help me in merging this PR

**Comment by waynesun09** [comment]
ACK and merge now, thanks

**Comment by balamuruhans** [comment]
Thank you @dzhengfy @waynesun09

**Pull request merged**
