### PR TITLE
Adopt Avocado cpu library changes

### PR DESCRIPTION
**Pull request by sathnaga**
Cpu library is getting refactored through this
PR https://github.com/avocado-framework/avocado/pull/3350,
This PR modified respective test code to reflect the same.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by sathnaga** [comment]
@chloerh could you pls help review this one, Tnx!

**Comment by sathnaga** [comment]
Travis failure Depends on  https://github.com/avocado-framework/avocado-vt/pull/2679

**Comment by chloerh** [comment]
I found that libvirt_mem.py requires change too.

**Review by dzhengfy — COMMENTED** [review]
@sathnaga , one concern for this PR.
Our CI system is using avocado 69lts instead master branch. So this PR will break our testing once it is merged. So I prefer that we hold on this PR for some time.

**Comment by sathnaga** [comment]
> @sathnaga , one concern for this PR.
> Our CI system is using avocado 69lts instead master branch. So this PR will break our testing once it is merged. So I prefer that we hold on this PR for some time.

we should probably discuss more on the compatibility of Avocado LTS vs Avocado-VT to handle it better going forward...

**Comment by chloerh** [comment]
@dzhengfy Here are some background info:

https://github.com/avocado-framework/avocado/pull/3350  Refactor cpu library to adopt common naming convention across arch

After it got merged, the functions of some cpu utilities are different in 69lts and master. About these functions, avocado-vt should be compatible with both 69lts and master, so should tp-libvirt, this pr is about changes of tp-libvirt. 

I guess now it is not quite compatible with 69lts, but the solution has been decided. And after it is compatible with 69lts, I believe it should be ok then.

**Comment by chunfuwen** [comment]
@sathnaga 
Could you help backport avocado PR #3350  to avocado 69lts? in this way, this PR change will not break our CI where avocado-69lts is currently used .

**Comment by chloerh** [comment]
> @sathnaga
> Could you help backport avocado PR #3350 to avocado 69lts? in this way, this PR change will not break our CI where avocado-69lts is currently used .

@chunfuwen About that, we could see the comment here: 

https://github.com/avocado-framework/avocado-vt/pull/2455#issuecomment-683856220

**Comment by chunfuwen** [comment]
@sathnaga
I go through comments in https://github.com/avocado-framework/avocado-vt/pull/2455# ,and understand your concerning.
actually, porting important feature back to relatively new stable release  is common practice.
this often happen because  customer need this critical feature ,but want it on  the stable release.

**Comment by chloerh** [comment]
Hi @sathnaga , could you help update this pr to be compatible with 69lts, just like https://github.com/avocado-framework/avocado-vt/pull/2758
Now that 82lts is on the way, we're preparing the switch, this pr is very helpful.

**Comment by chunfuwen** [comment]
close it since there are no any updates in recent two years.
If author find it is required, there is opportunity to open it again

**Pull request closed without merging**
