### PR TITLE
Correct dd_data_to_vm usage

### PR DESCRIPTION
**Pull request by lento-sun**
Data generation method changed in avocado-vt, also need to
update it here.

Signed-off-by: Yi Sun <yisun@redhat.com>

### CODE REVIEW

**Comment by lento-sun** [comment]
depends on: https://github.com/avocado-framework/avocado-vt/pull/2754

**Comment by lento-sun** [comment]
@chunfuwen @Yingshun pls help to review this, the dd_data_to_vm() is moved to utils_disk now. so this needs to be fixed.

**Comment by chunfuwen** [comment]
We have guideline for committed message, please update that accordingly
Moreover, please upload test result if available.

**Review by chunfuwen — COMMENTED** [review]
see inline comment

**Comment by lento-sun** [comment]
(.libvirt-ci-venv-ci-runtest-bDlil1) [root@dell-per740xd-10 ~]# avocado run --vt-type libvirt incremental_backup.pull_mode.original_disk_local.hotplug_disk.nbd_tcp.scratch_to_file.not_reuse_scratch_file.default_exportbitmap.default_exportname incremental_backup.push_mode.original_disk_local.hotplug_disk.backup_to_qcow2.backup_to_file.reuse_target_file.positive_test incremental_backup.backing_chain.blockpull.mid_to_top.original_disk_local.nbd_tcp.shutoff_snapshot.scratch_to_file
JOB ID     : 32e87bf235d9e2647142f85c8a393ab1d25e0773
JOB LOG    : /root/avocado/job-results/job-2020-09-16T04.28-32e87bf/job.log
 (1/3) type_specific.io-github-autotest-libvirt.incremental_backup.pull_mode.original_disk_local.hotplug_disk.nbd_tcp.scratch_to_file.not_reuse_scratch_file.default_exportbitmap.default_exportname: PASS (39.48 s)
 (2/3) type_specific.io-github-autotest-libvirt.incremental_backup.push_mode.original_disk_local.hotplug_disk.backup_to_qcow2.backup_to_file.reuse_target_file.positive_test: PASS (40.53 s)
 (3/3) type_specific.io-github-autotest-libvirt.incremental_backup.backing_chain.blockpull.mid_to_top.original_disk_local.nbd_tcp.shutoff_snapshot.scratch_to_file: PASS (157.78 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 241.59 s

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
