### PR TITLE
qemu_monitor_socket_creation_delay: Fix a parameter issue

### PR DESCRIPTION
**Pull request by cliping**
Update cfg file to add a missing 'emulator_dict' parameter.

### CODE REVIEW

**Comment by cliping** [comment]
Before:
 (1/1) type_specific.io-github-autotest-libvirt.daemon.qemu_monitor_socket_creation_delay: ERROR: eval() arg 1 must be a string, bytes or code object (6.81 s)

After:
 (1/1) type_specific.io-github-autotest-libvirt.daemon.qemu_monitor_socket_creation_delay: PASS (24.97 s)

**Comment by cliping** [comment]
@rh-jugraham  Could you help review it? Thanks.

**Comment by rh-jugraham** [comment]
> Before: (1/1) type_specific.io-github-autotest-libvirt.daemon.qemu_monitor_socket_creation_delay: ERROR: eval() arg 1 must be a string, bytes or code object (6.81 s)
> 
> After: (1/1) type_specific.io-github-autotest-libvirt.daemon.qemu_monitor_socket_creation_delay: PASS (24.97 s)

Looks good to me and it successfully addresses the bug! I don't have the permissions to actually add myself as a 'reviewer' (or merge changes) so this is the best I can do. :heavy_check_mark:

**Review by rh-jugraham — APPROVED** [review]
Looks good to me - the changes successfully address the issue!

**Pull request merged**
