### PR TITLE
migrate_over_unix: fix disk selection

### PR DESCRIPTION
**Pull request by smitterl**
The code used the target name to identify disks inside of the VM with their impersistent names (vda, vdb, ...). However, they might change between boots.

Instead use a function to identify new disks as not containing the system root partition.

### CODE REVIEW

**Comment by smitterl** [comment]
@chunfuwen please help review

**Comment by smitterl** [comment]
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type s390-virtio virsh.migrate_over_unix.positive_testing.with_copy_storage --vt-connect-uri qemu:///system 
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 83c98b7bfa5992d9ad7b27c8e2005de713e6a9c8
JOB LOG    : /var/log/avocado/job-results/job-2024-06-10T06.33-83c98b7/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.with_copy_storage.default.single_disk.p2p_live_migration.without_postcopy: PASS (69.13 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.with_copy_storage.default.single_disk.live_migration.without_postcopy: PASS (70.37 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.with_copy_storage.default.multi_disks.p2p_live_migration.without_postcopy: PASS (105.56 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.with_copy_storage.multifd.multi_disks.p2p_live_migration.without_postcopy: PASS (107.10 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-06-10T06.33-83c98b7/results.html
JOB TIME   : 352.68 s
```

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by cliping — APPROVED** [review]
LGTM

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
