### PR TITLE
virsh_start:Add log of vmxml before test start

### PR DESCRIPTION
**Pull request by chloerh**
Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
Test result:
```
 (01/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.normal_start: PASS (8.65 s)
 (02/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.vm_named_by_num: PASS (11.56 s)
 (03/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.vm_named_long: PASS (11.34 s)
 (04/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.vm_name_start_with_special: PASS (11.20 s)
 (05/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.remote_start: ERROR: local variable 'remote_uri' referenced before assignment (7.07 s)
 (06/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.console: PASS (25.76 s)
 (07/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.paused: PASS (8.84 s)
 (08/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.autodestroy: PASS (8.84 s)
 (09/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.bypass-cache: PASS (9.03 s)
 (10/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.force-boot: PASS (42.52 s)
 (11/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.audit_log_search: PASS (9.04 s)
 (12/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_yes.libvirtd_off: PASS (9.79 s)
 (13/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_yes.no_option: PASS (7.65 s)
 (14/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_yes.dom_name_not_found: PASS (7.94 s)
 (15/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_yes.vm_running: PASS (9.07 s)
 (16/16) type_specific.io-github-autotest-libvirt.virsh.start.status_error_yes.vm_paused: PASS (9.46 s)
RESULTS    : PASS 15 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-10-13T22.30-7647632/results.html
JOB TIME   : 199.97 s
```
The failed case was supposed to run with a remote machine which was not configured with this run

**Review by vasekhodina — APPROVED** [review]
LGTM. I was thinking if it wouldn't be useful to add a VMXML debug log to the vm.start() function, because I think it is always useful to see what is the VMXML of the host that is currently booting. What do you think?

**Comment by chloerh** [comment]
> 

@vasekhodina I agree. But there seem to be more than one instance of vm being started, therefore I put the log at the end of the code block that manipulates vmxml. I'd be more than happy to try more other solutions. Thanks. Could you share your thoughts, pleas?

**Comment by vasekhodina** [comment]
In my tests I like to add a line that prints the VMXML of the VM that is currently being started to easily see what is happening. When I saw it used in other tests, I thought it could be added into the start function so nobody else has to add it anymore. However it would clutter the log too much in case of starting multiple VMs. Maybe we could add a print statement that prints the path to a VM XML if it exists. I was lines in the log that look like: `Defining VM from /tmp/random-string.xml` Maybe we could use that. Like like `Starting VM with XML /tmp/random-string.xml`.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
