### PR TITLE
Add selinux/mke2fs/guest_mount tests

### PR DESCRIPTION
**Pull request by zcyes**

### CODE REVIEW

**Comment by PandaWei** [comment]
Hi,
There's a lot of unused import and variable.
Please check your PR again.

**Comment by PandaWei** [comment]
Just for your information,
libguestfs/tests/guestfish_guest_mount.py:1: 'utils' imported but unused
libguestfs/tests/guestfish_guest_mount.py:2: 'utils_misc' imported but unused
libguestfs/tests/guestfish_guest_mount.py:3: 'unattended_install' imported but unused
libguestfs/tests/guestfish_guest_mount.py:4: 'virsh' imported but unused
libguestfs/tests/guestfish_guest_mount.py:4: 'qemu_storage' imported but unused
libguestfs/tests/guestfish_guest_mount.py:5: redefinition of unused 'utils_test' from line 2
libguestfs/tests/guestfish_guest_mount.py:7: 'shutil' imported but unused
libguestfs/tests/guestfish_guest_mount.py:56: local variable 'add_ref' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:57: local variable 'readonly' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:62: local variable 'image_path' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:105: local variable 'add_ref' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:106: local variable 'readonly' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:111: local variable 'image_path' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:119: local variable 'vt_result' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:152: local variable 'add_ref' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:153: local variable 'readonly' is assigned to but never used
libguestfs/tests/guestfish_guest_mount.py:158: local variable 'image_path' is assigned to but never used

**Comment by PandaWei** [comment]
libguestfs/tests/guestfish_mke2fs.py:1: 'utils' imported but unused
libguestfs/tests/guestfish_mke2fs.py:2: 'utils_misc' imported but unused
libguestfs/tests/guestfish_mke2fs.py:3: 'unattended_install' imported but unused
libguestfs/tests/guestfish_mke2fs.py:4: 'virsh' imported but unused
libguestfs/tests/guestfish_mke2fs.py:4: 'qemu_storage' imported but unused
libguestfs/tests/guestfish_mke2fs.py:6: 'shutil' imported but unused
libguestfs/tests/guestfish_mke2fs.py:10: 'time' imported but unused
libguestfs/tests/guestfish_mke2fs.py:55: local variable 'add_ref' is assigned to but never used
libguestfs/tests/guestfish_mke2fs.py:59: local variable 'image_path' is assigned to but never used
libguestfs/tests/guestfish_mke2fs.py:122: local variable 'add_ref' is assigned to but never used
libguestfs/tests/guestfish_mke2fs.py:126: local variable 'image_path' is assigned to but never used

**Comment by PandaWei** [comment]
libguestfs/tests/guestfish_selinux.py:1: 'utils' imported but unused
libguestfs/tests/guestfish_selinux.py:2: 'utils_misc' imported but unused
libguestfs/tests/guestfish_selinux.py:3: 'unattended_install' imported but unused
libguestfs/tests/guestfish_selinux.py:4: 'virsh' imported but unused
libguestfs/tests/guestfish_selinux.py:4: 'qemu_storage' imported but unused
libguestfs/tests/guestfish_selinux.py:6: 'shutil' imported but unused
libguestfs/tests/guestfish_selinux.py:9: 'commands' imported but unused
libguestfs/tests/guestfish_selinux.py:10: 'time' imported but unused
libguestfs/tests/guestfish_selinux.py:55: local variable 'add_ref' is assigned to but never used
libguestfs/tests/guestfish_selinux.py:80: local variable 'add_ref' is assigned to but never used
libguestfs/tests/guestfish_selinux.py:101: local variable 'add_ref' is assigned to but never used

**Comment by will-Do** [comment]
Any update for this ? I'm gonna close this pr and feel free to reopen it when you ready.

**Pull request closed without merging**
