### PR TITLE
bios: Boot order for OVMF guest with dev=hd

### PR DESCRIPTION
**Pull request by vasekhodina**
This PR adds script for automating VIRT-45958. It checks boot
element in <os> part of VMXML. The device is always hd.

```
avocado run --vt-type libvirt boot_order_ovmf..boot_dev
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 9bf86fd8dcf208a7a4ec64da4b827d507a6c4c6c
JOB LOG    : /var/lib/avocado/job-results/job-2022-08-31T08.48-9bf86fd/job.log
 (1/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.bootable_dev.boot_dev.hd_dev: STARTED
 (1/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.bootable_dev.boot_dev.hd_dev: PASS (75.95 s)
 (2/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.unbootable_dev_first.boot_dev.hd_dev: STARTED
 (2/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.unbootable_dev_first.boot_dev.hd_dev: FAIL: Test fail: Login timeout expired    (output: 'exceeded 240 s timeout') (302.26 s)
 (3/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.no_dev.boot_dev.hd_dev: STARTED
 (3/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.no_dev.boot_dev.hd_dev: PASS (274.76 s)
 (4/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.unbootable_dev.boot_dev.hd_dev: STARTED
 (4/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.unbootable_dev.boot_dev.hd_dev: PASS (293.64 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-08-31T08.48-9bf86fd/results.html
JOB TIME   : 950.20 s
```

# Check lists by category
## If the PR is new cases
- [x] Description of the cases
- [x] Links of libvirt features, libvirt bugs or case IDs
- [x] Test results

### CODE REVIEW

**Comment by vasekhodina** [comment]
1. One issue needs to be handled I'm working on it with Meina. It still fails in the test results.
2. PR #4374 needs to be merged before this one and rebase needs to be done.

**Review by dzhengfy — COMMENTED** [review]
LGTM. I am waiting for the discussing result about the failed case to approval. Thanks.

**Comment by dzhengfy** [comment]
@vasekhodina As you mentioned, could you provide your latest test results as you said the problem had been solved if IIUC?

**Comment by vasekhodina** [comment]
@dzhengfy There is still an issue. When I'm automating step 3 of VIRT-45958, where there is first disk unbootable and second bootable. The host required manual input (from human) to continue booting. Otherwise it just continues to restart util a timeout of the test is reached. For the test to be successful "continue boot" option needs to be selected on a boot screen.

**Comment by vasekhodina** [comment]
@dzhengfy I have no problem skipping the failing case. I will run the tests once more and then I will prepare the skip PR.

**Comment by vasekhodina** [comment]
Just for the record, latest test results:
```
[root@dell-per730-66 ~]# avocado run --vt-type libvirt boot_order_ovmf
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : a1dab253adb2f4da9318d6f32814a0a31d55bfbd
JOB LOG    : /var/lib/avocado/job-results/job-2022-10-14T05.51-a1dab25/job.log
 (1/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.bootable_dev.boot_dev.hd_dev: STARTED
 (1/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.bootable_dev.boot_dev.hd_dev: PASS (48.87 s)
 (2/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.bootable_dev.boot_order.file_disk: STARTED
 (2/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.bootable_dev.boot_order.file_disk: PASS (48.83 s)
 (3/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.unbootable_dev_first.boot_dev.hd_dev: STARTED
 (3/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.unbootable_dev_first.boot_dev.hd_dev: FAIL: Test fail: Login timeout expired    (output: 'exceeded 240 s timeout') (304.62 s)
 (4/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.no_dev.boot_dev.hd_dev: STARTED
 (4/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.no_dev.boot_dev.hd_dev: PASS (305.08 s)
 (5/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.unbootable_dev.boot_dev.hd_dev: STARTED
 (5/5) type_specific.io-github-autotest-libvirt.boot_order_ovmf.negative_test.unbootable_dev.boot_dev.hd_dev: PASS (303.23 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-10-14T05.51-a1dab25/results.html
JOB TIME   : 1014.50 s
```

**Comment by vasekhodina** [comment]
MR number 1895 opened in our gitlab for updating skiplist.

**Comment by vasekhodina** [comment]
@dzhengfy The last update already fixes the failures you saw.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
@meinaLi Could you help review it?

**Review by meinaLi — APPROVED** [review]

**Pull request merged**
