### PR TITLE
[Batch 2] Fix Admin API cases for split daemon mode

### PR DESCRIPTION
**Pull request by iccaszhulili**
As the server name changed under split daemon mode, the config
file is also changed, update them.

Signed-off-by: Lily Zhu <lizhu@redhat.com>

### CODE REVIEW

**Comment by iccaszhulili** [comment]
Under split daemon mode

JOB ID     : 47784bfadb5da6c490cae75dbcdc83d37b1880e2
JOB LOG    : /root/avocado/job-results/job-2020-11-06T14.55-47784bf/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virt_admin.client_disconnect: PASS (13.47 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB ID     : 2f0273c823f231541be5422c3b4780e5d1c66d98
JOB LOG    : /root/avocado/job-results/job-2020-11-06T14.56-2f0273c/job.log
 (1/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.normal_test.max_clients_test.max_clients_gt_nclients: PASS (15.75 s)
 (2/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.normal_test.max_clients_test.max_clients_lt_nclients: PASS (35.24 s)
 (3/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.normal_test.max_clients_test.max_clients_gt_max_unauth_clients: PASS (10.05 s)
 (4/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.normal_test.max_unauth_clients_test.max_unauth_clients_lt_max_clients: PASS (10.12 s)
 (5/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.normal_test.options_test_together.max_unauth_clients_lt_max_clients: PASS (10.00 s)
 (6/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.negative_test.max_clients_test.max_unauth_clients_gt_max_clients: PASS (10.15 s)
 (7/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.negative_test.max_unauth_clients_test.max_unauth_clients_gt_max_clients: PASS (10.02 s)
 (8/8) type_specific.io-github-autotest-libvirt.virt_admin.server_clients_set.negative_test.options_test_together.max_unauth_clients_gt_max_clients: PASS (9.98 s)
JOB ID     : 03faf0ba44464362a63dd780531de57d741a9e33
JOB LOG    : /root/avocado/job-results/job-2020-11-06T15.44-03faf0b/job.log
 (01/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.min_workers_test.min_workers_lt_nworkers: PASS (8.98 s)
 (02/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.min_workers_test.min_workers_gt_nworkers: PASS (8.60 s)
 (03/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.min_workers_test.lower_limit_test: PASS (8.63 s)
 (04/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.max_workers_test.max_workers_gt_nworkers: PASS (8.93 s)
 (05/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.max_workers_test.max_workers_lt_nworkers: PASS (9.15 s)
 (06/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.max_workers_test.upper_limit_test: PASS (8.84 s)
 (07/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.priority_workers_test: PASS (8.61 s)
 (08/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.normal_test.options_test_together: PASS (8.66 s)
 (09/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.negative_test.min_workers_test.min_workers_gt_max_workers: PASS (8.50 s)
 (10/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.negative_test.min_workers_test.invalid_value: PASS (8.46 s)
 (11/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.negative_test.max_workers_test.min_workers_gt_max_workers: PASS (8.96 s)
 (12/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.negative_test.max_workers_test.invalid_value: PASS (8.92 s)
 (13/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.negative_test.max_workers_test.non_numeric_value: PASS (8.78 s)
 (14/14) type_specific.io-github-autotest-libvirt.virt_admin.server_threadpool_set.negative_test.options_test_together: PASS (8.64 s)

**Comment by iccaszhulili** [comment]
Also tested under legacy mode, all cases passed either

**Comment by Yingshun** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/2817
A kind reminder, @iccaszhulili please update dependent avocado-vt PR if necessary

**Comment by iccaszhulili** [comment]
@Yingshun https://github.com/avocado-framework/avocado-vt/pull/2817 has been merged, thanks :)

**Review by Yingshun — APPROVED** [review]

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
