### PR TITLE
Add new case of comparing iface stat

### PR DESCRIPTION
**Pull request by chloerh**
- RHEL7-103794: [domifstat] domiflist, domifstat, domifaddr for
direct type interface

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
JOB LOG    : /root/avocado/job-results/job-2021-06-02T16.50-3b73bf2/job.log
 (1/1) type_specific.local.virtual_network.iface_stat.compare.direct_type: PASS (65.49 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by chloerh** [comment]
@yalzhang would you like to review?

**Review by yalzhang — APPROVED** [review]
LGTM

**Review by kamilvarga — APPROVED** [review]
LGTM.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
