### PR TITLE
Move backingchain feature related cfg and python files to backingchain

### PR DESCRIPTION
**Pull request by chunfuwen**
This may increase visibility and readability

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
no need to upload  test result since only file locations changes

**Review by cliping — APPROVED** [review]
LGTM

**Comment by Yingshun** [comment]
rebase plz @chunfuwen

**Review by Yingshun — APPROVED** [review]
LGTM.

**Pull request merged**
