### PR TITLE
virsh_boot.cfg: Add new checkpoint for error message

### PR DESCRIPTION
**Pull request by meinaLi**
virsh_boot.cfg: Add new checkpoint for error message
Signed-off-by: Meina Li <meili@redhat.com>

### CODE REVIEW

**Comment by meinaLi** [comment]
@chunfuwen Please merge this new pr.

**Comment by chloerh** [comment]
I'm not quite sure this expression is valid, can we see the test result of these 2 cases, just to be sure?

**Comment by meinaLi** [comment]
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.boot.ma_q35.by_ovmf.negative_test.no_readonly
JOB ID     : c998f61f4f5a7a57a00f51589a92f78d3b1da103
JOB LOG    : /root/avocado/job-results/job-2019-02-27T22.11-c998f61/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.boot.ma_q35.by_ovmf.negative_test.no_readonly: PASS (17.98 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 21.05 s
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.boot.ma_q35.by_ovmf.negative_test.readonly_no
JOB ID     : fab4acc790283177450d4c898fa68e9232f82429
JOB LOG    : /root/avocado/job-results/job-2019-02-27T22.12-fab4acc/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.boot.ma_q35.by_ovmf.negative_test.readonly_no: PASS (12.08 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 16.16 s

**Comment by chloerh** [comment]
Nice. Then It's ok to me

**Pull request merged**
