### PR TITLE
Fix some virtual disk failures due to command output change

### PR DESCRIPTION
**Pull request by chunfuwen**
Command output change to json format, and some flexbit change from on to true
or from off to false

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_option_bootdisk.disk_virtio_driver_options.ioeventfd_on

PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_option_bootdisk.disk_virtio_driver_options.scsi_ioeventfd.with_controller_model.ioeventfd_on

**Review by dzhengfy — COMMENTED** [review]
LGTM, but please also provide test result for old version. Thanks.

**Comment by chunfuwen** [comment]
old version result is available:
```
Command 'virsh list' finished with 0 after 1.3944947719573975s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_option_bootdisk.disk_virtio_driver_options.ioeventfd_on
```

**Review by cliping — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]

**Pull request merged**
