### PR TITLE
Add a case of managedsave-remove

### PR DESCRIPTION
**Pull request by chloerh**
- Managedsave-remove for a domain NOT in saved state but with a
corrupt saved file

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
Test result
FAIL 1-type_specific.local.virsh.managedsave.functional_test.rm_test.not_saved_with_file -> TestFail: Managed save image still exists

Caused by BZ1689809

**Comment by chloerh** [comment]
@yanqzhan Would you like to review?

**Review by yanqzhan — APPROVED** [review]
Function meets requirement to me.

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
