### PR TITLE
Fix at_dt_iscsi_disk..iscsi_pool.auth_in_pool failure

### PR DESCRIPTION
**Pull request by chunfuwen**
Fix at_dt_iscsi_disk.positive_test.hot_plug.volume_disk.iscsi_pool.auth_in_pool failure

In some extreme case, after iscsid is restarted and it may not be really ready for operation soon Add some logic here to ensure iscsid is active before further actions

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.at_dt_iscsi_disk.positive_test.hot_plug.volume_disk.iscsi_pool.auth_in_pool

**Comment by chunfuwen** [comment]
some failed log:
2022-11-16 04:06:17,903 process          L0470 DEBUG| [stdout] COMMAND
2022-11-16 04:06:17,903 process          L0739 INFO | Command 'ps -o comm 1' finished with 0 after 0.019680199s
2022-11-16 04:06:17,903 process          L0470 DEBUG| [stdout] systemd
2022-11-16 04:06:17,917 service          L0474 DEBUG| Setting ignore_status to True.
2022-11-16 04:06:17,917 process          L0658 INFO | Running 'systemctl reset-failed iscsid'
2022-11-16 04:06:17,930 process          L0739 INFO | Command 'systemctl reset-failed iscsid' finished with 0 after 0.007396387s
2022-11-16 04:06:17,930 service          L0474 DEBUG| Setting ignore_status to True.
2022-11-16 04:06:17,930 process          L0658 INFO | Running 'systemctl restart iscsid'
2022-11-16 04:06:17,970 process          L0739 INFO | Command 'systemctl restart iscsid' finished with 0 after 0.034137090s
2022-11-16 04:06:18,174 virsh            L0776 DEBUG| Running virsh command: pool-create  /tmp/xml_utils_temp_tpogk4h9.xml
2022-11-16 04:06:18,174 process          L0658 INFO | Running '/usr/bin/virsh pool-create  /tmp/xml_utils_temp_tpogk4h9.xml'
2022-11-16 04:06:18,277 process          L0470 DEBUG| [stderr] error: 
2022-11-16 04:06:18,277 process          L0470 DEBUG| [stdout] 
2022-11-16 04:06:18,278 process          L0470 DEBUG| [stderr] Failed to create pool from /tmp/xml_utils_temp_tpogk4h9.xml
2022-11-16 04:06:18,278 process          L0470 DEBUG| [stderr] error: internal error: Child process (/usr/sbin/iscsiadm --mode node --portal 127.0.0.1:3260,1 --targetname iqn.2022-11.com.virttest:emulated-iscsi.target --login) unexpected exit status 19: iscsiadm: Could not login to [iface: default, target: iqn.2022-11.com.virttest:emulated-iscsi.target, portal: 127.0.0.1,3260].
2022-11-16 04:06:18,278 process          L0470 DEBUG| [stderr] iscsiadm: initiator reported error (19 - encountered non-retryable iSCSI login failure)
2022-11-16 04:06:18,278 process          L0470 DEBUG| [stderr] iscsiadm: Could not log into all portals

**Comment by meinaLi** [comment]
@chunfuwen Actually I've submitted another PR to fix this issue: https://github.com/avocado-framework/avocado-vt/pull/3561. It's still not merged. In my opinion, we'd better to add authentication=1 to iscsi server. Would you have a look?

**Comment by chunfuwen** [comment]
close it since it looks like https://github.com/avocado-framework/avocado-vt/pull/3561 already fix this

**Pull request closed without merging**
