### PR TITLE
Fix attach_detach disk by switching get_tmp_dir to get_data_dir

### PR DESCRIPTION
**Pull request by chunfuwen**
Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.host_block_vm_id

**Comment by chunfuwen** [comment]
@kylazhang 
@dzhengfy 
please take a look

**Review by dzhengfy — APPROVED** [review]
LGTM
Please make the description field simpler.

**Comment by chunfuwen** [comment]
two lines changes , mark it as minor_fix

**Pull request merged**
