### PR TITLE
Add 1 case of attach/detach interface with multiqueue

### PR DESCRIPTION
**Pull request by chloerh**
- hotplug / unplug an network interface with multiqueue

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
```
# avocado run --vt-machine-type q35 --vt-type libvirt type_specific.local.virsh.attach_detach_interface.normal_test.vm_running.default_network.multiqueue.domname
JOB ID     : 6c04ca6f554c52ccea77628c01929a913007b678
JOB LOG    : /root/avocado/job-results/job-2020-11-10T10.48-6c04ca6/job.log
 (1/1) type_specific.local.virsh.attach_detach_interface.normal_test.vm_running.default_network.multiqueue.domname: PASS (53.21 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 54.21 s
```

**Review by yalzhang — APPROVED** [review]

**Review by dzhengfy — DISMISSED** [review]
LGTM

**Comment by dzhengfy** [comment]
I dismissed the approval because I think it is safe to have a look at more test cases' result as this is a common change. @chloerh

**Comment by chloerh** [comment]
Only 1 existing case could be affected, test result:
```
# avocado run --vt-type libvirt virsh.attach_detach_interface.normal_test.vm_running.default_network.multiqueue.domname,virsh.attach_detach_interface.normal_test.vm_running.direct.at_detach_device.domname
JOB ID     : b539c3089620b485c5c5a5fe52c44e539aa888d5
JOB LOG    : /root/avocado/job-results/job-2020-12-03T13.47-b539c30/job.log
 (1/2) type_specific.local.virsh.attach_detach_interface.normal_test.vm_running.default_network.multiqueue.domname: PASS (53.97 s)
 (2/2) type_specific.local.virsh.attach_detach_interface.normal_test.vm_running.direct.at_detach_device.domname: PASS (69.52 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 124.63 s
```
@dzhengfy

**Review by dzhengfy — APPROVED** [review]

**Pull request merged**
