### PR TITLE
auto_memory_placement_numad_fail: add case

### PR DESCRIPTION
**Pull request by dzhengfy**
This is to verify expected error message when numad service fails

Case ID: xxx-299204

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
libvirt-9.5.0 
 (1/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_strict: WARN: Test passed but there were warnings during execution. Check the log for details. (4.66 s)
 (2/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_interleave: WARN: Test passed but there were warnings during execution. Check the log for details. (5.13 s)
 (3/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_preferred: WARN: Test passed but there were warnings during execution. Check the log for details. (4.95 s)
 (4/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_restrictive: WARN: Test passed but there were warnings during execution. Check the log for details. (4.82 s)

**Comment by dzhengfy** [comment]
libvirt-8.0.0

 (1/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_strict: WARN: Test passed but there were warnings during execution. Check the log for details. (4.47 s)
 (2/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_interleave: WARN: Test passed but there were warnings during execution. Check the log for details. (4.50 s)
 (3/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_preferred: WARN: Test passed but there were warnings during execution. Check the log for details. (4.30 s)
 (4/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_restrictive: WARN: Test passed but there were warnings during execution. Check the log for details. (4.25 s)

**Comment by dzhengfy** [comment]
libvirt-8.0.0
on aarch64
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type arm64-mmio  guest_numa_node_tuning.auto_memory_placement_numad_fail
 (1/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_strict: PASS (12.13 s)
 (2/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_interleave: PASS (12.03 s)
 (3/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_preferred: PASS (11.98 s)
 (4/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_placement_numad_fail.mem_mode_restrictive: PASS (12.17 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2024-01-30T00.43-79a4e3b/results.html
JOB TIME   : 49.48 s

```

**Comment by dzhengfy** [comment]
@nanli1 Could you help review?

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
