### PR TITLE
Add restarting virtnetworkd for network hooks test

### PR DESCRIPTION
**Pull request by jinqi7**
Signed-off-by: qijing <jinqi@redhat.com>

### CODE REVIEW

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
@jinqi7 Could you provide test result before and after the fix?

**Comment by jinqi7** [comment]
Before fix:
2021-12-02 16:53:24,775 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/libvirt_hooks.py", line 348, in network_hook
2021-12-02 16:53:24,775 stacktrace       L0045 ERROR|     assert check_hooks(hook_str)
2021-12-02 16:53:24,775 stacktrace       L0045 ERROR| AssertionError
2021-12-02 16:53:24,775 stacktrace       L0045 ERROR|

**Comment by jinqi7** [comment]
# avocado run --vt-type libvirt --vt-machine-type q35 libvirt_hooks.vm.network_t
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 1f37ca435aac4a72e0cefbb0de512ef683ac8fd8
JOB LOG    : /root/avocado/job-results/job-2021-12-13T01.35-1f37ca4/job.log
 (1/1) type_specific.io-github-autotest-libvirt.libvirt_hooks.vm.network_t: PASS (46.97 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 48.38 s

**Review by cliping — APPROVED** [review]
LGTM

**Pull request merged**
