### PR TITLE
virsh_boot: Update usb controller and loader path to the default

### PR DESCRIPTION
**Pull request by meinaLi**
virsh_boot: Update usb controller and loader path to the default

Signed-off-by: Meina Li <meili@redhat.com>

### CODE REVIEW

**Comment by meinaLi** [comment]
```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.boot..positive_test.options.boot.hd.usb_disk
JOB ID     : 68174effb84ebbc50656447e911c1f4d17c30d8a
JOB LOG    : /root/avocado/job-results/job-2021-03-24T22.47-68174ef/job.log
 (1/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_dev.os_loader.valid_loader_type.valid_readonly: PASS (65.82 s)
 (2/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_dev.os_loader.valid_loader_type.no_readonly: PASS (85.26 s)
 (3/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_dev.os_loader.no_loader_type.valid_readonly: PASS (84.40 s)
 (4/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_dev.os_loader.no_loader_type.no_readonly: PASS (83.53 s)
 (5/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_order.os_loader.valid_loader_type.valid_readonly: PASS (82.83 s)
 (6/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_order.os_loader.valid_loader_type.no_readonly: PASS (80.44 s)
 (7/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_order.os_loader.no_loader_type.valid_readonly: PASS (93.85 s)
 (8/8) type_specific.io-github-autotest-libvirt.virsh.boot.by_seabios.positive_test.options.boot.hd.usb_disk.boot_order.os_loader.no_loader_type.no_readonly: PASS (87.33 s)
RESULTS    : PASS 8 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 669.48 s
```

**Comment by chunfuwen** [comment]
Does the change impact testing on previous release, such as rhel8.0 etc.?

**Comment by meinaLi** [comment]
> Does the change impact testing on previous release, such as rhel8.0 etc.?
No, we can use it in previous release.

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
