### PR TITLE
Add more negative scenarios for dompmsuspend operation.

### PR DESCRIPTION
**Pull request by rbian**

### CODE REVIEW

**Comment by rbian** [comment]
Depends on avocado-framework/avocado-vt/pull/270.

**Comment by lmr** [comment]
@rbian can you please rebase? A new pylint version caused problems in our tests, I've fixed them, but you need to rebase to pick up the fixes in your branch.

**Comment by will-Do** [comment]
ACK, we can merge this pr after the dependent one merged.

**Comment by waynesun09** [comment]
ACK

**Pull request merged**
