### PR TITLE
v2v: add case 'virt-v2v depends on platform-python'

### PR DESCRIPTION
**Pull request by vwu-vera**
Please check TC #RHEL-150296 and bz #1644275 #1850423

Signed-off-by:vwu

### CODE REVIEW

**Comment by vwu-vera** [comment]
(1/1) type_specific.io-github-autotest-libvirt.v2v_options.positive_test.cmd_free.deplist.input_mode.none.output_mode.none: PASS (4.31 s)

**Comment by vwu-vera** [comment]
@xiaodwan Please help to review the commit. Thanks.

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by vwu-vera** [comment]
@xiaodwan  Have modified accordingly. Please review. Thanks.

**Review by xiaodwan — APPROVED** [review]

**Pull request merged**
