### PR TITLE
Increase memory size in memory_discard and nvdimm

### PR DESCRIPTION
**Pull request by jinqi7**
Signed-off-by: qijing <jinqi@redhat.com>

Increase memory size to fix some vm crash issues

### CODE REVIEW

**Comment by jinqi7** [comment]
# avocado run --vt-type libvirt memory_discard.common.mem_dev
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : b7998eeb4e231d2c661a43d7d7088a67f224aeab
JOB LOG    : /root/avocado/job-results/job-2021-07-08T23.56-b7998ee/job.log
 (1/6) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.discard_yes: PASS (24.71 s)
 (2/6) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.shared_yes: PASS (24.78 s)
 (3/6) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.shared_no: PASS (28.93 s)
 (4/6) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.type_file: PASS (24.93 s)
 (5/6) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.type_anon: PASS (24.40 s)
 (6/6) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.discard_no: PASS (25.18 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 153.79 s

**Comment by jinqi7** [comment]
# avocado run --vt-type libvirt nvdimm.back_file.no_label
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : e15ac63a6bc12e05c8baafa0df7b284485af0626
JOB LOG    : /root/avocado/job-results/job-2021-07-08T22.40-e15ac63/job.log
 (1/1) type_specific.io-github-autotest-libvirt.nvdimm.back_file.no_label: PASS (96.80 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 97.33 s

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
