### PR TITLE
Fix fs-freezed failure by refined error message

### PR DESCRIPTION
**Pull request by chunfuwen**
Fix fs-freezed failure by refined error message

### CODE REVIEW

**Comment by chunfuwen** [comment]
Failed log:
2024-10-06 06:13:50,028 process          L0658 INFO | Running '/usr/bin/virsh domfsinfo avocado-vt-vm1'
2024-10-06 06:13:50,054 process          L0470 DEBUG| [stderr] error: Unable to get filesystem information
2024-10-06 06:13:50,054 process          L0470 DEBUG| [stdout]
2024-10-06 06:13:50,055 process          L0470 DEBUG| [stderr] error: internal error: unable to execute QEMU agent command 'guest-get-fsinfo': Command guest-get-fsinfo has been disabled: the agent is in frozen state
2024-10-06 06:13:50,056 process          L0739 INFO | Command '/usr/bin/virsh domfsinfo avocado-vt-vm1' finished with 1 after 0.020257318s
2024-10-06 06:13:50,062 virsh            L0873 DEBUG| status: 1
2024-10-06 06:13:50,062 virsh            L0874 DEBUG| stdout:
2024-10-06 06:13:50,062 virsh            L0875 DEBUG| stderr: error: Unable to get filesystem informationerror: internal error: unable to execute QEMU agent command 'guest-get-fsinfo': Command guest-get-fsinfo has been disabled: the agent is in frozen state

**Review by cliping — APPROVED** [review]

**Review by iccaszhulili — APPROVED** [review]

**Comment by iccaszhulili** [comment]
LGTM

**Comment by chunfuwen** [comment]
JOB ID     : d9cd72b01bab18bc8981b59985a4110d623bdf80
JOB LOG    : /var/log/avocado/job-results/job-2024-11-24T22.15-d9cd72b/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.domfsinfo.negative_tests.fs_freezed: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.virsh.domfsinfo.negative_tests.fs_freezed: PASS (82.52 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-11-24T22.15-d9cd72b/results.html
JOB TIME   : 87.86 s

**Review by slickedit — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
