### PR TITLE
Bugfix: Fix the cases NG when the domain has cdrom in virsh-domblklist

### PR DESCRIPTION
**Pull request by liuzzfnst**
When the domain has a none source cdrom driver, new_disk.source would
point to no object. And sometimes the output from xml and command output's
order is different, so we should order them and then compare them.

### CODE REVIEW

**Comment by liuzzfnst** [comment]
When the domain has a empty IDE-CDROM, the test case will fail and output follow log.
```
23:33:57 ERROR| LibvirtXMLNotFoundError: Error in Getter for property "source", element tag "source" not found on parent at xpath "/" in XML
```

**Comment by liuzzfnst** [comment]
Test result on libvirt-1.2.8-16.el7.x86_64 after using this patch.
```
# ./run -k --no-downloads -t libvirt --tests virsh.domblklist
SETUP: PASS (0.40 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /root/community/autotest/client/tests/virt-test/logs/run-2015-06-08-23.50.03/debug.log
TESTS: 13
(1/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.id_option: PASS (16.77 s)
(2/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.name_option: PASS (26.66 s)
(3/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.uuid_option: PASS (16.34 s)
(4/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.shutoff_option: PASS (0.92 s)
(5/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.details_option: PASS (16.09 s)
(6/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.inactive_option: PASS (11.80 s)
(7/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.inactive_with_shutoff_option: PASS (0.94 s)
(8/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.inactive_with_details_option: PASS (26.48 s)
(9/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.no_option: PASS (16.77 s)
(10/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.error_test.no_option: PASS (11.51 s)
(11/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.error_test.hex_id_option: PASS (11.70 s)
(12/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.error_test.invalid_id_option: PASS (25.31 s)
(13/13) type_specific.io-github-autotest-libvirt.virsh.domblklist.error_test.invalid_option: PASS (11.48 s)
TOTAL TIME: 192.82 s (03:12)
TESTS PASSED: 13
TESTS FAILED: 0
SUCCESS RATE: 100.00 %
```

**Comment by PandaWei** [comment]
LGTM

**Comment by PandaWei** [comment]
Hi
Your PR incorporate with others after updating.
Please fix it.

**Pull request closed without merging**
