### PR TITLE
Update device_source_path from test.virtdir to /var/tmp

### PR DESCRIPTION
**Pull request by chunfuwen**
since previous one may be interrupted by avocado itself
Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
@kylazhang 
@waynesun09 

This is minor fix for LIBVIRTAT-1608:Cannot access storage file '/root/.libvirt-ci/runtest/avocado-vt/avocado-vt/shared/test.raw' (as uid:107, gid:107): Permission denied&#10
It sound like our CI or Avocado framework will interrupt test.dir in some way:/root/.libvirt-ci/runtest/avocado-vt/avocado-vt/shared/

**Comment by kylazhang** [comment]
@chunfuwen I think it is CI issues and should not changed in tp-libvirt. @waynesun09 what's your suggestion?

**Comment by chunfuwen** [comment]
@kylazhang 
From below log, apparently the image file was created successfully.
Not quit sure,but somehow can figure out that it may CI or Avocado interrupt this folder.
The fix doesn't bring any change to any case logic itself,just give a experiential fix to confirm whether the figure is true or not.
*******************************************************************************
2017-08-03 19:41:20,830 process          L0389 INFO | Running 'qemu-img create -f raw /root/.libvirt-ci/runtest/avocado-vt/avocado-vt/shared/test.raw 1.0G'
2017-08-03 19:41:20,888 process          L0479 DEBUG| [stdout] Formatting '/root/.libvirt-ci/runtest/avocado-vt/avocado-vt/shared/test.raw', fmt=raw size=1073741824
2017-08-03 19:41:20,890 process          L0499 INFO | Command 'qemu-img create -f raw /root/.libvirt-ci/runtest/avocado-vt/avocado-vt/shared/test.raw 1.0G' finished with 0 after 0.0464880466461s
2017-08-03 19:41:21,053 virtual_disks_mu L0662 DEBUG| disk xml: <?xml version='1.0' encoding='UTF-8'?><disk device="disk" type="file"><source file="/root/.libvirt-ci/runtest/avocado-vt/avocado-vt/shared/test.raw" /><target bus="virtio" dev="vdb" /><driver cache="none" iothread="1" name="qemu" type="raw" /></disk>

**Comment by chunfuwen** [comment]
@kylazhang 
@waynesun09 
Confirmed with ruiKai, the CI change test.dir from previous /usr/share/xx to current /root/XX,which can not be accessed by qemu.
KaiRui will revert the change.

**Pull request closed without merging**
