### PR TITLE
[passthrough] group passthrough tests into new folder

### PR DESCRIPTION
**Pull request by smitterl**
Group passthrough tests into new folder structure `passthrough/<bus>`.

Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>

### CODE REVIEW

**Comment by smitterl** [comment]
I reviewed the import paths and didn't see any imports that might have broken by moving. I don't think we need to run the tests to confirm the change doesn't introduce any regression.

**Comment by smitterl** [comment]
@fbq815 for visibility

**Review by kamilvarga — APPROVED** [review]
LGTM.

**Review by dzhengfy — APPROVED** [review]
LGTM as we have not run these tests in our CI.

**Pull request merged**
