### PR TITLE
v2v: add a new case about env leak

### PR DESCRIPTION
**Pull request by xiaodwan**
see: bz#1901423

Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.env_leak.esx_67.json.default.it_vddk.vpx_uri: PASS (709.64 s)

**Comment by xiaodwan** [comment]
depends on https://github.com/autotest/tp-libvirt/pull/3387

**Comment by xiaodwan** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/2970

**Comment by xiaodwan** [comment]
@chloerh @yantian0 Please help to review this PR, thanks.

**Review by yantian0 — APPROVED** [review]

**Review by chloerh — APPROVED** [review]

**Pull request merged**
