### PR TITLE
Fixed the shell cmd failure issue in nvdimm test

### PR DESCRIPTION
**Pull request by jinqi7**
Signed-off-by: qijing <jinqi@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
Better have test results uploaded

**Comment by jinqi7** [comment]
@chloerh，can you help to review it? Thanks

**Comment by jinqi7** [comment]
avocado run --vt-type=libvirt nvdimm.back_file.no_label
JOB ID     : d0d4e462b24e07cde8d4e738f452c700dc0a5883
JOB LOG    : /root/avocado/job-results/job-2020-05-19T22.24-d0d4e46/job.log
 (1/1) type_specific.io-github-autotest-libvirt.nvdimm.back_file.no_label: PASS (112.92 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 114.26 s

**Comment by jinqi7** [comment]
The failure only happened in rhel7.*.

**Pull request merged**
