### PR TITLE
V2v dependence

### PR DESCRIPTION
**Pull request by weikunzz**
Add 'kernel-rt' package not dependence by virt-v2v chenckpoint.
Add two guest from different ova file compress method

### CODE REVIEW

**Comment by balamuruhans** [comment]
@weikunzz please have proper description for the changes made.

**Comment by balamuruhans** [comment]
Looks good to me, @chloerh @chunfuwen @kylazhang please acknowledge if it is fine.

**Comment by chloerh** [comment]
Maybe it's better to merge the 2 commits into 1. Others are ok to me.

**Comment by balamuruhans** [comment]
Thanks @chloerh @weikunzz. let us merge this.

**Pull request merged**
