### PR TITLE
v2v: add a new case about unknown_vmware_controller_type

### PR DESCRIPTION
**Pull request by xiaodwan**
see bz#1510801

Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.convert_from_file.positive_test.linux.input_mode.ova.normal.linux.output_mode.rhev.rhv_upload: PASS (807.25 s)

**Comment by xiaodwan** [comment]
@chloerh @yantian0 Please help to review this PR, thanks.

**Review by chunfuwen — COMMENTED** [review]
@xiaodwan 
In tp-libvirt(libvirt part), now we usually add polarion case id(without specific link) in git commit log.
Not sure whether there is matched polarion case id, if there is ,better add it.

**Comment by xiaodwan** [comment]
@chunfuwen I think polarion ID is not permanent, if the case management tool is changed in future, it's difficult to find the source.
but anyway, I'll add both polarion id and bugzilla id.

**Pull request merged**
