### PR TITLE
fix domain is disappeared issue in block job.

### PR DESCRIPTION
**Pull request by chunfuwen**
allow more time waiting before do blockjob operation
therefore fix it by extending timeout to 10 seconds

### CODE REVIEW

**Comment by chunfuwen** [comment]
paste failure error here
```
2018-06-03 05:39:40,103 stacktrace       L0044 ERROR| Reproduced traceback from: /var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py:434
2018-06-03 05:39:40,105 stacktrace       L0047 ERROR| Traceback (most recent call last):
2018-06-03 05:39:40,105 stacktrace       L0047 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py", line 157, in run
2018-06-03 05:39:40,105 stacktrace       L0047 ERROR|     test.fail("Domain is disappeared.")
2018-06-03 05:39:40,105 stacktrace       L0047 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado/avocado/core/test.py", line 1052, in fail
2018-06-03 05:39:40,105 stacktrace       L0047 ERROR|     raise exceptions.TestFail(message)
2018-06-03 05:39:40,105 stacktrace       L0047 ERROR| avocado.core.exceptions.TestFail: Domain is disappeared.
2018-06-03 05:39:40,105 stacktrace       L0048 ERROR| 
2018-06-03 05:39:40,190 virt_vm          L1093 DEBUG| Attempting to log into 'vm2' (timeout 240s)
2018-06-03 05:39:40,190 virt_vm          L0807 DEBUG| Found/Verified IP 192.168.122.225 for VM vm2 NIC 0
2018-06-03 05:39:41,663 client           L1113 DEBUG| Sending command: dmesg -T -l 0,1,2|grep .
2018-06-03 05:39:41,778 client           L1113 DEBUG| Sending command: echo $?
2018-06-03 05:39:42,030 libvirt_vm       L2144 WARNI| Requested MAC address release from persistent vm avocado-vt-vm1. Ignoring.
2018-06-03 05:39:42,063 libvirt_vm       L2109 DEBUG| Destroying VM
2018-06-03 05:39:42,097 libvirt_vm       L2115 DEBUG| Trying to shutdown VM with shell command
2018-06-03 05:39:43,523 libvirt_vm       L2125 DEBUG| Shutdown command sent; waiting for VM to go down...
```

**Comment by kylazhang** [comment]
If vm disappeared, it should be a bug, we could not add more sleep time here.

**Comment by iccaszhulili** [comment]
rh-caselink retest please

**Comment by chunfuwen** [comment]
issue not reproduce now.

**Pull request closed without merging**
