### PR TITLE
filesystem_device: Make add extra hugepages configurable

### PR DESCRIPTION
**Pull request by PaulYuuu**
1. Restore the host's hugepages after the test
2. Make add extra hugepages configurable

Signed-off-by: Yihuang Yu <yihyu@redhat.com>

### CODE REVIEW

**Comment by PaulYuuu** [comment]
Hello @chloerh, it's possible to help review this patch? 

This patch is to make it work on aarch64. BTW, do you know why so many extra hugepages were added before? I am to confirm whether it can be deleted directly.

**Comment by PaulYuuu** [comment]
```
avocado run --journal --vt-config /var/lib/avocado/data/avocado-vt/backends/libvirt/cfg/tests-example.cfg --tap-job-result off
JOB ID     : 3574ee3359001afa82fe8a6f6dee978987ad3652
JOB LOG    : /root/avocado/job-results/job-2020-10-23T03.37-3574ee3/job.log
 (01/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_off.cache_mode_none.one_fs.one_guest: PASS (62.22 s)
 (02/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_off.cache_mode_always.one_fs.one_guest: PASS (62.11 s)
 (03/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_off.cache_mode_auto.one_fs.one_guest: PASS (61.04 s)
 (04/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (59.51 s)
 (05/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.two_guests: PASS (74.61 s)
 (06/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.multiple_fs.one_guest: PASS (70.99 s)
 (07/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_always.one_fs.one_guest: PASS (60.88 s)
 (08/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_auto.one_fs.one_guest: PASS (59.93 s)
 (09/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.one_fs.one_guest: PASS (64.06 s)
 (10/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_always.one_fs.one_guest: PASS (58.63 s)
 (11/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_auto.one_fs.one_guest: PASS (59.76 s)
 (12/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_off.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (60.47 s)
 (13/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_off.lock_posix_on.cache_mode_always.one_fs.one_guest: PASS (61.43 s)
 (14/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_on.flock_off.lock_posix_on.cache_mode_auto.one_fs.one_guest: PASS (60.57 s)
 (15/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_on.lock_posix_off.cache_mode_none.one_fs.one_guest: PASS (60.12 s)
 (16/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_on.lock_posix_off.cache_mode_always.one_fs.one_guest: PASS (60.27 s)
 (17/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_on.lock_posix_off.cache_mode_auto.one_fs.one_guest: PASS (60.39 s)
 (18/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (62.28 s)
 (19/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_on.lock_posix_on.cache_mode_always.one_fs.one_guest: PASS (61.36 s)
 (20/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_on.lock_posix_on.cache_mode_auto.one_fs.one_guest: PASS (59.35 s)
 (21/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_off.lock_posix_off.cache_mode_none.one_fs.one_guest: PASS (57.92 s)
 (22/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_off.lock_posix_off.cache_mode_always.one_fs.one_guest: PASS (57.44 s)
 (23/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_off.lock_posix_off.cache_mode_auto.one_fs.one_guest: PASS (60.35 s)
 (24/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_off.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (64.52 s)
 (25/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_off.lock_posix_on.cache_mode_always.one_fs.one_guest: PASS (60.97 s)
 (26/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_off.flock_off.lock_posix_on.cache_mode_auto.one_fs.one_guest: PASS (58.17 s)
 (27/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_on.lock_posix_off.cache_mode_none.one_fs.one_guest: PASS (60.72 s)
 (28/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_on.lock_posix_off.cache_mode_always.one_fs.one_guest: PASS (57.83 s)
 (29/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_on.lock_posix_off.cache_mode_auto.one_fs.one_guest: PASS (59.39 s)
 (30/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (63.84 s)
 (31/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_on.lock_posix_on.cache_mode_always.one_fs.one_guest: PASS (60.15 s)
 (32/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_on.lock_posix_on.cache_mode_auto.one_fs.one_guest: PASS (62.85 s)
 (33/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_off.lock_posix_off.cache_mode_none.one_fs.one_guest: PASS (57.75 s)
 (34/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_off.lock_posix_off.cache_mode_always.one_fs.one_guest: PASS (58.84 s)
 (35/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_off.lock_posix_off.cache_mode_auto.one_fs.one_guest: PASS (60.90 s)
 (36/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_off.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (63.94 s)
 (37/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_off.lock_posix_on.cache_mode_always.one_fs.one_guest: PASS (60.32 s)
 (38/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.nop.fs_test.xattr_noset.flock_off.lock_posix_on.cache_mode_auto.one_fs.one_guest: PASS (60.83 s)
 (39/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.socket_file_checking.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (59.89 s)
 (40/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.socket_file_checking.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.multiple_fs.one_guest: PASS (71.55 s)
 (41/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.lifecycle.suspend_resume.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (89.05 s)
 (42/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.coldplug_coldunplug.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (62.60 s)
 (43/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.negative_test.invalid_queue_size.larger_than_uint16.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (8.61 s)
 (44/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.negative_test.invalid_queue_size.not_powerof_2.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (8.90 s)
 (45/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.negative_test.invalid_queue_size.larger_than_1024.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (8.82 s)
 (46/46) qemu.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.8.3.0.aarch64.arm64-pci.io-github-autotest-libvirt.virtual_devices.filesystem_device.negative_test.managedsave.nop.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest: PASS (48.74 s)
```

**Review by chloerh — APPROVED** [review]

**Comment by chloerh** [comment]
Tested on jenkins. All 46 cases passed

**Comment by chloerh** [comment]
@yafu-1 Would you like to review?

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
