### PR TITLE
Remove pid file under /dir for daemon.kill_starting

### PR DESCRIPTION
**Pull request by yafu-1**

### CODE REVIEW

**Comment by yafu-1** [comment]
Test result:
$ avocado run kill_starting --vt-type libvirt
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 0d9ea01e9d47e20b01bc74479f18487e628684f9
JOB LOG    : /var/log/avocado/job-results/job-2024-07-02T22.25-0d9ea01/job.log
 (1/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.virStateInitialize: STARTED
 (1/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.virStateInitialize: PASS (67.24 s)
 (2/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.qemuStateInitialize: STARTED
 (2/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.qemuStateInitialize: PASS (67.28 s)
 (3/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.netcfStateInitialize: STARTED
 (3/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.netcfStateInitialize: FAIL: Expect receive signal, but not. (66.56 s)
 (4/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.networkStateInitialize: STARTED
 (4/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.networkStateInitialize: PASS (6.73 s)
 (5/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.nwfilterStateInitialize: STARTED
 (5/5) type_specific.io-github-autotest-libvirt.daemon.kill_starting.nwfilterStateInitialize: PASS (7.32 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-07-02T22.25-0d9ea01/results.html
JOB TIME   : 220.77 s

One testcase failed as expected because virtinterfaced does not call netcfStateInitialize any more.

**Comment by dzhengfy** [comment]
@yafu-1Please help  also add what the error is without your fix. thanks.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by Yingshun — APPROVED** [review]

**Comment by yafu-1** [comment]
> @yafu-1Please help also add what the error is without your fix. thanks.

daemon.kill_starting can pass without the fix but will lead other cases fail with the error:
(023/134) type_specific.io-github-autotest-libvirt.daemon.crash_regression.destroy_console: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: Failed to connect socket to '/var/run/libvirt/virtnetworkd-sock': No such file or directory(exit status: 1) (66.15 s)
 (024/134) type_specific.io-github-autotest-libvirt.daemon.crash_regression.shutdown_console: STARTED
 (024/134) type_specific.io-github-autotest-libvirt.daemon.crash_regression.shutdown_console: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: Failed to connect socket to '/var/run/libvirt/virtnetworkd-sock': No such file or directory(exit status: 1)
...

**Pull request merged**
