### PR TITLE
Enable sriov tests on arm

### PR DESCRIPTION
**Pull request by Yingshun**
depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3857

### CODE REVIEW

**Comment by Yingshun** [comment]
Screenshot from 2024-03-04 17-11-39

**Comment by Yingshun** [comment]
Test results:  aarch64-function-sriov/12
Screenshot from 2024-03-04 17-12-03

**Comment by Yingshun** [comment]
Test results on function-sriov/18: The failed case is due to a known issue.
Screenshot from 2024-03-11 13-51-12

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by chloerh — APPROVED** [review]

**Pull request merged**
