### PR TITLE
capabilities: don't check cluster_id on s390x

### PR DESCRIPTION
**Pull request by smitterl**
Attributes on s390x are: thread, core, book, drawer.

Skip check cluster information as it doesn't apply.

### CODE REVIEW

**Comment by smitterl** [comment]
JOB ID     : a21fd98db79d55e9a7be6fbf767096185c918d41
JOB LOG    : /var/log/avocado/job-results/job-2024-09-09T02.55-a21fd98/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.capabilities.no_option: PASS (5.80 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-09-09T02.55-a21fd98/results.html
JOB TIME   : 6.11 s

**Comment by smitterl** [comment]
@liang-cong-red-hat please help review

**Comment by liang-cong-red-hat** [comment]
LGTM

**Review by chunfuwen — APPROVED** [review]
lgtm

**Pull request merged**
