### PR TITLE
Add virtio packed test cases in input and video devices

### PR DESCRIPTION
**Pull request by meinaLi**
Add virtio packed test cases in:
1) input device
2) video device

Signed-off-by: Meina Li <meili@redhat.com>

### CODE REVIEW

**Comment by meinaLi** [comment]
```
# avocado run --vt-type libvirt --vt-machine-type q35 virtual_devices.input_devices.positive_test.bus_type_virtio
JOB ID     : 1839304f24c94fe3584d07b76cccf7eac3060ad4
JOB LOG    : /root/avocado/job-results/job-2020-12-07T02.33-1839304/job.log
 (1/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_tablet.with_packed_on: PASS (7.09 s)
 (2/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_tablet.default: PASS (7.62 s)
 (3/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_mouse.with_packed_on: PASS (9.61 s)
 (4/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_mouse.default: PASS (6.99 s)
 (5/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_keyboard.with_packed_on: PASS (8.06 s)
 (6/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_keyboard.default: PASS (16.83 s)
 (7/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_passthrough.with_packed_on: PASS (7.81 s)
 (8/8) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_virtio.input_type_passthrough.default: PASS (17.01 s)
RESULTS    : PASS 8 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 93.54 s

# avocado run --vt-type libvirt --vt-machine-type q35  virtual_devices.video_devices.positive_test.primary_video.cirrus.secondary_video.virtio
JOB ID     : 26ebb989a38534bee931392c5aba9e831cd35439
JOB LOG    : /root/avocado/job-results/job-2020-12-07T02.36-26ebb98/job.log
 (1/3) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.cirrus.secondary_video.virtio.model_test.with_packed_on: PASS (7.47 s)
 (2/3) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.cirrus.secondary_video.virtio.model_test.default: PASS (7.82 s)
 (3/3) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.cirrus.secondary_video.virtio.heads_test.default_heads: PASS (8.16 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 29.26 s
```

**Comment by meinaLi** [comment]
This PR is related with https://github.com/avocado-framework/avocado-vt/pull/2848

**Comment by meinaLi** [comment]
@iccaszhulili Please help review this pr, thanks.

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by iccaszhulili** [comment]
LGTM

**Review by iccaszhulili — APPROVED** [review]

**Pull request merged**
