### PR TITLE
virsh_domif_setlink_getlink: Fix a code bug.

### PR DESCRIPTION
**Pull request by rbian**
Since login by ssh may timeout, remove the operation before setlink on guest.

### CODE REVIEW

**Comment by PandaWei** [comment]
We can increase the waiting time to avoid timeout.
Why remove it directly?

**Comment by rbian** [comment]
If login timeout, wait_for_login will login by serial console, this will disrupt the serial sesion which defined previously in the funciton. I thinks jsut checking 'ip link' on the guest is okay.

**Comment by PandaWei** [comment]
Indeed, we can check it's status with 'ip link'.
But .no codes to do it.
if you remove wait_for_login(), 
the following code is 'cmd_status = session.cmd_status('ip link set dev %s down'',
which will set it down directly without checking if it's up.

**Comment by rbian** [comment]
Okay, modified the code to check link state after domif_setlink. Thanks @PandaWei

**Comment by PandaWei** [comment]
ACK.

**Comment by waynesun09** [comment]
ACK and merge now, thx.

**Pull request merged**
