### PR TITLE
numa: Fix small typo

### PR DESCRIPTION
**Pull request by hs0210**

### CODE REVIEW

**Comment by hs0210** [comment]
@dzhengfy PTAL.

**Review by cliping — APPROVED** [review]
LGTM

**Comment by cliping** [comment]
Please upload test result, thanks.

**Comment by hs0210** [comment]
The test results are as follows, the failure case is another tp issue and needs to be fixed separately
```
 (01/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_strict.vcpu_auto: PASS (50.04 s)                                                                                                                                            
 (02/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_strict.vcpu_static: PASS (51.46 s)                                                                                                                                          
 (03/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (53.06 s)                                                                                                    
 (04/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave.vcpu_static: FAIL: Expect cpuset.mems=, but found 0-1 (52.19 s)                                                                                                  
 (05/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_preferred.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (61.72 s)                                                                                                     
 (06/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_preferred.vcpu_static: FAIL: Expect cpuset.mems=, but found 0-1 (58.13 s)                                                                                                   
 (07/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_restrictive.vcpu_auto: PASS (58.37 s)                                                                                                                                       
 (08/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_restrictive.vcpu_static: PASS (52.97 s)                                                                                                                                     
 (09/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_none.vcpu_auto: PASS (55.14 s)                                                                                                                                            
 (10/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_none.vcpu_static: FAIL: Expect cpuset.mems=, but found 0-1 (58.27 s)                                                                                                      
 (11/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_strict.vcpu_auto: PASS (52.92 s)                                                                                                                                          
 (12/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_strict.vcpu_static: PASS (8.83 s)                                                                                                                                         
 (13/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_interleave.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (54.11 s)                                                                                                  
 (14/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_interleave.vcpu_static: PASS (8.73 s)                                                                                                                                     
 (15/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_preferred.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (52.01 s)                                                                                                   
 (16/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_preferred.vcpu_static: PASS (18.44 s)                                                                                                                                     
 (17/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_restrictive.vcpu_auto: PASS (55.00 s)                                                                                                                                     
 (18/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_undefined.mem_mode_restrictive.vcpu_static: PASS (9.10 s)                                                                                                                                    
 (19/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_strict.vcpu_auto: PASS (56.75 s)                                                                                                                                               
 (20/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_strict.vcpu_static: PASS (53.79 s)                                                                                                                                             
 (21/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_interleave.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (62.65 s)                                                                                                       
 (22/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_interleave.vcpu_static: FAIL: Expect cpuset.mems=, but found 0-1 (58.14 s)                                                                                                     
 (23/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_preferred.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (63.00 s)                                                                                                        
 (24/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_preferred.vcpu_static: FAIL: Expect cpuset.mems=, but found 0-1 (57.84 s)                                                                                                      
 (25/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_restrictive.vcpu_auto: PASS (57.74 s)                                                                                                                                          
 (26/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_defined.mem_mode_restrictive.vcpu_static: PASS (53.65 s)                                                                                                                                        
 (27/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_none.vcpu_auto: PASS (54.41 s)                                                                                                                                               
 (28/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_none.vcpu_static: FAIL: Expect cpuset.mems=, but found 0-1 (58.10 s)                                                                                                         
 (29/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_strict.vcpu_auto: PASS (54.44 s)                                                                                                                                             
 (30/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_strict.vcpu_static: PASS (8.90 s)                                                                                                                                            
 (31/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_interleave.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (59.34 s)                                                                                                     
 (32/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_interleave.vcpu_static: PASS (8.89 s)                                                                                                                                        
 (33/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_preferred.vcpu_auto: FAIL: Expect cpuset.mems=, but found 0-1 (54.91 s)                                                                                                      
 (34/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_preferred.vcpu_static: PASS (8.97 s)                                                                                                                                         
 (35/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_restrictive.vcpu_auto: PASS (53.91 s)                                                                                                                                        
 (36/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.with_iothread.nodeset_undefined.mem_mode_restrictive.vcpu_static: PASS (9.19 s)                                                                                                                                       
RESULTS    : PASS 22 | ERROR 0 | FAIL 14 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
