### PR TITLE
virsh: Add test case for metadata

### PR DESCRIPTION
**Pull request by will-Do**
Signed-off-by: Yanbing Du <ydu@redhat.com>

### CODE REVIEW

**Comment by will-Do** [comment]
BTW, this pr dependent on https://github.com/autotest/virt-test/pull/2062

**Comment by rbian** [comment]
Test failed:

14:03:28 ERROR| Traceback (most recent call last):
14:03:28 ERROR|   File "/opt/tp-libvirt-virtual-network-18/virttest/standalone_test.py", line 220, in run_once
14:03:28 ERROR|     run_func(self, params, env) 
14:03:28 ERROR|   File "/opt/tp-libvirt-virtual-network-18/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_metadata.py", line 102, in run
14:03:28 ERROR|     check_result(result, status_error)
14:03:28 ERROR|   File "/opt/tp-libvirt-virtual-network-18/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_metadata.py", line 49, in check_result
14:03:28 ERROR|     utlv.check_exit_status(result, expect_status)
14:03:28 ERROR|   File "/opt/tp-libvirt-virtual-network-18/virttest/utils_test/libvirt.py", line 1203, in check_exit_status
14:03:28 ERROR|     raise error.TestFail(result.stderr)
14:03:28 ERROR| TestFail: /bin/bash: -c: line 0: syntax error near unexpected token `newline'
14:03:28 ERROR| /bin/bash: -c: line 0: `/usr/bin/virsh metadata --domain virt-tests-vm1 --uri http://herp.derp/ --current --key herp --set <function metadata at 0x2278398>'
14:03:28 ERROR| 
14:03:28 ERROR| 
14:03:28 ERROR| FAIL type_specific.io-github-autotest-libvirt.virsh.metadata.positive_test.current_option -> TestFail: /bin/bash: -c: line 0: syntax error near unexpected token `newline' 
/bin/bash: -c: line 0: `/usr/bin/virsh metadata --domain virt-tests-vm1 --uri http://herp.derp/ --current --key herp --set <function metadata at 0x2278398>'

**Comment by rbian** [comment]
Forgot the dependency patch. passed first 3 tests, hang on 4th test:
(1/6) type_specific.io-github-autotest-libvirt.virsh.metadata.positive_test.config_option: PASS (14.33 s)
(2/6) type_specific.io-github-autotest-libvirt.virsh.metadata.positive_test.current_option: PASS (2.32 s)
(3/6) type_specific.io-github-autotest-libvirt.virsh.metadata.positive_test.live_option: PASS (2.26 s)
(4/6) type_specific.io-github-autotest-libvirt.virsh.metadata.positive_test.edit_option:


14:15:40 DEBUG| Running virsh command: metadata --domain virt-tests-vm1 --uri http://herp.derp/ --edit --key herp 
14:15:40 DEBUG| Running '/usr/bin/virsh metadata --domain virt-tests-vm1 --uri http://herp.derp/ --edit --key herp'
14:15:44 DEBUG| Running virsh command: domstate virt-tests-vm1 
14:15:44 DEBUG| Running '/usr/bin/virsh -c 'qemu:///system' domstate virt-tests-vm1 '
14:15:44 DEBUG| status: 0
14:15:44 DEBUG| stdout: running
14:15:44 DEBUG| stderr:

**Comment by will-Do** [comment]
@rbian Thanks.
Yes, it should be a bug you mentioned, i will dig it later.

**Comment by will-Do** [comment]
Now all cases pass:
```
# ./run -t libvirt --test virsh.metadata -k --keep-image-between-test
SETUP: PASS (0.30 s)
DATA DIR: /root/Downloads/virt-test/shared/data
DEBUG LOG: /root/Downloads/virt-test/logs/run-2015-04-14-14.07.00/debug.log
TESTS: 6
(1/6) type_specific.ydu-libvirt.virsh.metadata.positive_test.config_option: PASS (12.93 s)
(2/6) type_specific.ydu-libvirt.virsh.metadata.positive_test.current_option: PASS (1.53 s)
(3/6) type_specific.ydu-libvirt.virsh.metadata.positive_test.live_option: PASS (1.59 s)
(4/6) type_specific.ydu-libvirt.virsh.metadata.positive_test.edit_option: PASS (2.31 s)
(5/6) type_specific.ydu-libvirt.virsh.metadata.negative_test.invalid_option: PASS (1.18 s)
(6/6) type_specific.ydu-libvirt.virsh.metadata.negative_test.nonexist_uri: PASS (1.21 s)
TOTAL TIME: 20.80 s
TESTS PASSED: 6
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by waynesun09** [comment]
Test result is good, ACK and merging now, thx @will-Do @rbian for your works.

**Pull request merged**
