### PR TITLE
virsh_nodeinfo: add case disable cpu

### PR DESCRIPTION
**Pull request by dzhengfy**
Case ID: RHEL7-17040 - [nodeinfo] - Get node basic information
Add a scenario to disable/enable a host cpu and check nodeinfo

### CODE REVIEW

**Comment by dzhengfy** [comment]
```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.nodeinfo 
JOB ID     : 9541f035f8e7d22320608abae3d96fb166d1bc0a
JOB LOG    : /root/avocado/job-results/job-2022-02-24T20.59-9541f03/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.no_option: PASS (7.29 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.disable_enable_vcpu: PASS (8.38 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.unexpect_option: PASS (6.41 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.with_libvirtd_stop: PASS (7.18 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 29.77 s

```

**Comment by dzhengfy** [comment]
@iccaszhulili Please help review

**Comment by iccaszhulili** [comment]
LGTM

**Review by iccaszhulili — APPROVED** [review]

**Review by Yingshun — APPROVED** [review]
LGTM

**Pull request merged**
