### PR TITLE
Update usage of cpu.numa_cell

### PR DESCRIPTION
**Pull request by chloerh**
The implement of numa_cell is being changed, this modification is
to fit the change.

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
Test result

```
# avocado run --vt-type libvirt nvdimm.back_file
JOB ID     : af8f342833532cd320675f9861f9300f85c05fa3
JOB LOG    : /root/avocado/job-results/job-2020-09-10T16.05-af8f342/job.log
 (1/4) type_specific.local.nvdimm.back_file.label.default: PASS (74.26 s)
 (2/4) type_specific.local.nvdimm.back_file.label.check_life_cycle: PASS (93.51 s)
 (3/4) type_specific.local.nvdimm.back_file.label.discard: PASS (5.14 s)
 (4/4) type_specific.local.nvdimm.back_file.no_label: PASS (139.15 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 315.13 s


# avocado run --vt-machine-type pseries --vt-type libvirt papr_hpt
\JOB ID     : a337de1db553827abc7ae0ebff0eaf43559c84ef
JOB LOG    : /root/avocado/job-results/job-2020-09-10T04.18-a337de1/job.log
 (1/8) type_specific.io-github-autotest-libvirt.papr_hpt.positive_test.disabled: PASS (59.66 s)
 (2/8) type_specific.io-github-autotest-libvirt.papr_hpt.positive_test.enabled.mem_hotplug: PASS (136.89 s)
 (3/8) type_specific.io-github-autotest-libvirt.papr_hpt.positive_test.maxpagesize.size_64k.with_hugepage: PASS (104.16 s)
 (4/8) type_specific.io-github-autotest-libvirt.papr_hpt.positive_test.maxpagesize.size_64k.no_hugepage: PASS (62.10 s)
 (5/8) type_specific.io-github-autotest-libvirt.papr_hpt.positive_test.maxpagesize.size_16m.with_hugepage: CANCEL: Power9 does not support 16M pagesize. (30.92 s)
 (6/8) type_specific.io-github-autotest-libvirt.papr_hpt.positive_test.maxpagesize.size_16m.no_hugepage: CANCEL: Power9 does not support 16M pagesize. (6.52 s)
 (7/8) type_specific.io-github-autotest-libvirt.papr_hpt.negative_test.maxpagesize.size_16m.with_hugepage: CANCEL: Power9 does not support 16M pagesize. (31.58 s)
 (8/8) type_specific.io-github-autotest-libvirt.papr_hpt.negative_test.maxpagesize.size_16m.no_hugepage: CANCEL: Power9 does not support 16M pagesize. (6.55 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 4
JOB TIME   : 442.09 s



```

**Comment by chloerh** [comment]
Depend on https://github.com/avocado-framework/avocado-vt/pull/2749

**Comment by chloerh** [comment]
Test result: 

```
JOB ID     : 1022e6264277d5a33a297d40c7d32232151b15c0
JOB LOG    : /root/avocado/job-results/job-2020-09-11T07.10-1022e62/job.log
 (01/27) type_specific.io-github-autotest-libvirt.virsh.create.none: PASS (6.10 s)
 (02/27) type_specific.io-github-autotest-libvirt.virsh.setvcpus.normal_test.guest_off.option_config: PASS (76.30 s)
 (03/27) type_specific.io-github-autotest-libvirt.virsh.net_destroy.normal_test.non_acl.default_option.persistent: PASS (4.71 s)
 (04/27) type_specific.io-github-autotest-libvirt.virsh.destroy.normal_test.non_acl.graceful: PASS (6.89 s)
 (05/27) type_specific.io-github-autotest-libvirt.virsh.blockcommit.normal_test.multiple_chain.file_disk.local.no_ga.notimeout.nobase.top_active.with_pivot: PASS (109.50 s)
 (06/27) type_specific.io-github-autotest-libvirt.virsh.resume.normal_test.vm_paused.valid_domname: PASS (27.07 s)
 (07/27) type_specific.io-github-autotest-libvirt.virsh.domfsfreeze_domfsthaw.positive.normal: PASS (155.23 s)
 (08/27) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.with_source: PASS (72.83 s)
 (09/27) type_specific.io-github-autotest-libvirt.virsh.reboot.normal_test.id_option.no_mode: PASS (143.78 s)
 (10/27) type_specific.io-github-autotest-libvirt.virsh.domiflist.with_valid_option.domid: PASS (59.02 s)
 (11/27) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.normal_test.tpm-crb_model.emulator.encrypted.basic: PASS (321.49 s)
 (12/27) type_specific.io-github-autotest-libvirt.virsh.setmem.valid_options.running.half_mem.domid.dom_arg_size_arg.cmd_flag_current.manipulate_action.none.no_action: PASS (105.22 s)
 (13/27) type_specific.io-github-autotest-libvirt.virsh.dump.positive_test.non_acl.bzip2_format_dump: PASS (12.81 s)
 (14/27) type_specific.io-github-autotest-libvirt.virsh.blockjob.positive_test.pivot_option: PASS (37.43 s)
 (15/27) type_specific.io-github-autotest-libvirt.virsh.vcpupin.online.positive_test.cpu_list.cpu_list_comma: PASS (7.85 s)
 (16/27) type_specific.io-github-autotest-libvirt.virsh.vcpupin.online.positive_test.live: PASS (16.29 s)
 (17/27) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.positive_test.vcpu_set.live.vm_operate.no_operation: PASS (112.95 s)
 (18/27) type_specific.io-github-autotest-libvirt.virsh.pool.positive_test.pool_type_dir: PASS (9.50 s)
 (19/27) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.attach_disk_image_format.qcow2_format: PASS (119.46 s)
 (20/27) type_specific.io-github-autotest-libvirt.virsh.volume.dir_pool.vol_encrypt_none.vol_format_qcow2.vol_allocation.normal_size: PASS (6.38 s)
 (21/27) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.positive_testing.get_emulatorpin_parameter.running_guest.emulatorpin_options.current: PASS (11.63 s)
 (22/27) type_specific.io-github-autotest-libvirt.virsh.snapshot.live.no_halt: PASS (110.35 s)
 (23/27) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: PASS (56.33 s)
 (24/27) type_specific.io-github-autotest-libvirt.virsh.managedsave.status_error_no.id_option.no_opt.no_progress: PASS (63.51 s)
 (25/27) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.non_acl.valid_netname: PASS (7.47 s)
 (26/27) type_specific.io-github-autotest-libvirt.virsh.shutdown.normal_test.name_option.agent_mode.agent_test: PASS (96.55 s)
 (27/27) type_specific.io-github-autotest-libvirt.virsh.net_create.normal_test.file_as_argument.new_network: PASS (12.24 s)
RESULTS    : PASS 27 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1772.62 s

```

**Review by kylazhang — APPROVED** [review]

**Comment by kylazhang** [comment]
As #2749 merged suddenly and it will affect most of our function test, so merge it now. For the following problem will submit new pr to fix. Thanks for understanding

**Pull request merged**
