### PR TITLE
Update controller of ppc vms to support hotplug/unplug

### PR DESCRIPTION
**Pull request by chloerh**
Replace old scsi controller with virtio-scsi controller to support
hotplug/unplug.

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
Could you help provide test result? @chloerh

**Comment by chloerh** [comment]
JOB ID     : 8496d6af7cdd5dcf6b355e14091f80248a28d294
JOB LOG    : /root/avocado/job-results/job-2021-03-19T01.45-8496d6a/job.log
 (01/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_managed.coldplug_disk.enable_auth.auth_uuid.auth_in_source: PASS (130.80 s)
 (02/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_managed.coldplug_disk.enable_auth.auth_uuid.auth_out_source: PASS (149.88 s)
 (03/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_managed.coldplug_disk.enable_auth.auth_usage.auth_in_source: PASS (136.57 s)
 (04/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_managed.coldplug_disk.enable_auth.auth_usage.auth_out_source: PASS (140.13 s)
 (05/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_managed.coldplug_disk.disable_auth: PASS (140.22 s)
 (06/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_not_managed.coldplug_disk.enable_auth.auth_uuid.auth_in_source: PASS (153.11 s)
 (07/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_not_managed.coldplug_disk.enable_auth.auth_uuid.auth_out_source: PASS (154.70 s)
 (08/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_not_managed.coldplug_disk.enable_auth.auth_usage.auth_in_source: PASS (135.53 s)
 (09/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_not_managed.coldplug_disk.enable_auth.auth_usage.auth_out_source: PASS (141.19 s)
 (10/10) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_not_managed.coldplug_disk.disable_auth: PASS (151.01 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1434.26 s

**Comment by chloerh** [comment]
@dzhengfy test result update.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
This only impacts ppc cases which is small scope. So I set minorfix and merge it.

**Pull request merged**
