### PR TITLE
migration_graphics: add case with graphics socket

### PR DESCRIPTION
**Pull request by dzhengfy**
Test scenario: Test migration with graphic device whose listening type is socket and
socket file could be generated correctly after migration
Case ID: VIRT-89391

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
(1/1) type_specific.io-github-autotest-libvirt.migration.migration_graphics.listen_type_socket.p2p: PASS (266.65 s)
libvirt-8.0.0-10.1.module+el8.7.0+17192+cbc2449b.x86_64

**Comment by dzhengfy** [comment]
@cliping Please help review. Thanks.

**Comment by dzhengfy** [comment]
@cliping Could you help review?

**Comment by dzhengfy** [comment]
@zhentang-tz Could you help review?

**Review by cliping — APPROVED** [review]
LGTM

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
