### PR TITLE
Add cases to cover hotplug rbd disk with enabled authentication as vi…

### PR DESCRIPTION
**Pull request by chunfuwen**
…rtio-scsi device

Those cases are related to bug1411398 1406442

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.ceph.hot_plug.with_auth.auth_place_in_source.disk_attach.attach_device.default
PASS 2-type_specific.io-github-autotest-libvirt.virtual_disks.ceph.hot_plug.with_auth.auth_place_in_source.disk_attach.attach_device.virtio-scsi
PASS 3-type_specific.io-github-autotest-libvirt.virtual_disks.ceph.hot_plug.with_auth.default.disk_attach.attach_device.default
PASS 4-type_specific.io-github-autotest-libvirt.virtual_disks.ceph.hot_plug.with_auth.default.disk_attach.attach_device.virtio-scsi

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
As the case is very old, we need not to test the libvirt version any more.

**Comment by dzhengfy** [comment]
It is only cfg modification. So I treat it as minor fix. Merge it.

**Pull request merged**
