### PR TITLE
virsh: Add test case for net-dhcp-leases

### PR DESCRIPTION
**Pull request by will-Do**
Signed-off-by: Yanbing Du <ydu@redhat.com>

### CODE REVIEW

**Comment by chuanchang** [comment]
[root@rhel7 virt-test]# ./run -t libvirt --tests type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases --no-downloads --keep-image --keep-image-between-tests
SETUP: PASS (0.30 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /home/ajia/Workspace/virt-test/logs/run-2015-04-08-16.07.24/debug.log
TESTS: 4
(1/4) type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.positive_test.hotplug_hotunplug_interface: FAIL (99.04 s)
(2/4) type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.negative_test.invalid_option: PASS (2.09 s)
(3/4) type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.negative_test.invalid_net: PASS (2.10 s)
(4/4) type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.negative_test.invalid_mac: FAIL (2.79 s)
TOTAL TIME: 106.11 s (01:46)
TESTS PASSED: 2
TESTS FAILED: 2
SUCCESS RATE: 50.00 %

For details:

16:09:03 ERROR| Traceback (most recent call last):
16:09:03 ERROR|   File "/home/test/Workspace/virt-test/virttest/standalone_test.py", line 220, in run_once
16:09:03 ERROR|     run_func(self, params, env)
16:09:03 ERROR|   File "/home/test/Workspace/tp-libvirt/libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py", line 177, in run
16:09:03 ERROR|     new_interface_ip = get_ip_by_mac(iface_mac, try_dhclint=True)
16:09:03 ERROR|   File "/home/test/Workspace/tp-libvirt/libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py", line 95, in get_ip_by_mac
16:09:03 ERROR|     iface_name = utils_net.get_linux_ifname(session, mac_addr)
16:09:03 ERROR|   File "/home/test/Workspace/virt-test/virttest/utils_net.py", line 2806, in get_linux_ifname
16:09:03 ERROR|     i = _process_output("ifconfig -a", r"(\w+)\s+Link.*%s" % mac_address)
16:09:03 ERROR|   File "/home/test/Workspace/virt-test/virttest/utils_net.py", line 2792, in _process_output
16:09:03 ERROR|     output = session.cmd_output_safe(cmd)
16:09:03 ERROR|   File "/home/test/Workspace/virt-test/virttest/aexpect.py", line 1526, in cmd_output_safe
16:09:03 ERROR|     raise ShellTimeoutError(cmd, o)
16:09:03 ERROR| ShellTimeoutError: Timeout expired while waiting for shell command to complete: 'ifconfig -a'    (output: '')
16:09:03 ERROR|
16:09:03 ERROR| FAIL type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.positive_test.hotplug_hotunplug_interface -> ShellTimeoutError: Timeout expired while waiting for shell command to complete: 'ifconfig -a'    (output: '')



16:09:09 DEBUG| Running '/usr/bin/virsh net-dhcp-leases virttest_net  --mac xyz'
16:09:09 DEBUG| status: 0
16:09:09 DEBUG| stdout: Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
16:09:09 DEBUG| stderr:
16:09:09 DEBUG| Destroying VM
16:09:10 WARNI| Requested MAC address release from persistent vm virt-tests-vm1. Ignoring.
16:09:10 DEBUG| Undefine VM virt-tests-vm1
16:09:10 DEBUG| Define VM from /tmp/xml_utils_temp_rLSOWs.xml
16:09:10 WARNI| Requested MAC address release from persistent vm virt-tests-vm1. Ignoring.
16:09:10 DEBUG| Checking image file /home/test/Workspace/virt-test/shared/data/images/jeos-19-64.qcow2
16:09:10 DEBUG| Running '/bin/qemu-img info /home/test/Workspace/virt-test/shared/data/images/jeos-19-64.qcow2'
16:09:10 DEBUG| Running '/bin/qemu-img check /home/test/Workspace/virt-test/shared/data/images/jeos-19-64.qcow2'
16:09:10 DEBUG| Running 'true'
16:09:10 DEBUG| Running 'ps -o comm 1'
16:09:10 DEBUG| Running 'dmesg'
16:09:10 ERROR|
16:09:10 ERROR| Traceback (most recent call last):
16:09:10 ERROR|   File "/home/test/Workspace/virt-test/virttest/standalone_test.py", line 220, in run_once
16:09:10 ERROR|     run_func(self, params, env)
16:09:10 ERROR|   File "/home/test/Workspace/tp-libvirt/libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py", line 139, in run
16:09:10 ERROR|     utlv.check_exit_status(result, status_error)
16:09:10 ERROR|   File "/home/test/Workspace/virt-test/virttest/utils_test/libvirt.py", line 1211, in check_exit_status
16:09:10 ERROR|     raise error.TestFail("Expect fail, but run successfully.")
16:09:10 ERROR| TestFail: Expect fail, but run successfully.
16:09:10 ERROR|
16:09:10 ERROR| FAIL type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.negative_test.invalid_mac -> TestFail: Expect fail, but run successfully.

**Comment by will-Do** [comment]
@chuanchang 
Thanks for your result.
For the first fail case, it PASS on my box:
```
# ./run -t libvirt --test ydu-libvirt.virsh.net_dhcp_leases.positive_test.hotplug_hotunplug_interface  -k --keep-image-between-tests
SETUP: PASS (0.70 s)
DATA DIR: /home/ydu/Work/virt-test/shared/data
DEBUG LOG: /home/ydu/Work/virt-test/logs/run-2015-04-09-11.35.25/debug.log
TESTS: 1
(1/1) type_specific.ydu-libvirt.virsh.net_dhcp_leases.positive_test.hotplug_hotunplug_interface: PASS (60.95 s)
TOTAL TIME: 61.01 s (01:01)
TESTS PASSED: 1
TESTS FAILED: 0
SUCCESS RATE: 100.00 %
```
The error you paste here shows that it fail to log into the vm to run a command, I will try to reproduce the problem later:
```
ShellTimeoutError: Timeout expired while waiting for shell command to complete: 'ifconfig -a' (output: '')
```

And for the second one, this's a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1205045

**Comment by will-Do** [comment]
@chuanchang 
Find the reason of the first fail case: [BZ#888229](https://bugzilla.redhat.com/show_bug.cgi?id=888229)
then, hotplug an interface to a VM which already has an interface in the same nework will cause packet loss, and then 'ifconfig -a' may fail as timeout.  So I re-design the case to avoid muti-interfaces of a VM in the same network.
New test result attached(the fail case has a bug [BZ#1205045](https://bugzilla.redhat.com/show_bug.cgi?id=1205045)):
``` 
./run -t libvirt --test virsh.net_dhcp_leases --no-downloads --keep-image --keep-image-between-tests
SETUP: PASS (0.50 s)
DATA DIR: /home/ydu/Work/virt-test/shared/data
DEBUG LOG: /home/ydu/Work/virt-test/logs/run-2015-04-13-15.57.17/debug.log
TESTS: 5
(1/5) type_specific.ydu-libvirt.virsh.net_dhcp_leases.positive_test.attach_interface_before_vm_start: PASS (22.59 s)
(2/5) type_specific.ydu-libvirt.virsh.net_dhcp_leases.positive_test.attach_interface_after_vm_start: PASS (22.99 s)
(3/5) type_specific.ydu-libvirt.virsh.net_dhcp_leases.negative_test.invalid_option: PASS (3.99 s)
(4/5) type_specific.ydu-libvirt.virsh.net_dhcp_leases.negative_test.invalid_net: PASS (4.04 s)
(5/5) type_specific.ydu-libvirt.virsh.net_dhcp_leases.negative_test.invalid_mac: FAIL (4.41 s)
TOTAL TIME: 58.10 s
TESTS PASSED: 4
TESTS FAILED: 1
SUCCESS RATE: 80.00 %

**Comment by waynesun09** [comment]
@will-Do about bug 1205045, could you add url in cfg file then check and raised it log, current fail log without any debug info for tracking.

**Comment by waynesun09** [comment]
Ack and merging now, thx.

**Pull request merged**
