### PR TITLE
Fix issue as error messages changes

### PR DESCRIPTION
**Pull request by yalzhang**
Edit the cfg file as the expected error messages changes. And update the
case name to be more understandable. Also fix the the function name
about check_cmd_output. And install the package in case it may not
exists in the system.

Signed-off-by: yalzhang <yalzhang@redhat.com>

### CODE REVIEW

**Comment by yalzhang** [comment]
run the 2 cases locally pass
$avocado run --vt-type libvirt filter_aready_present_binding
/root/code/avocado/avocado/plugins/run.py:294: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
JOB ID     : b2c4617609e67b426b82575921c5c27187774e20
JOB LOG    : /root/avocado/job-results/job-2020-07-28T06.06-b2c4617/job.log
 (1/2) type_specific.io-github-autotest-libvirt.filter_aready_present_binding.filter_is_define: PASS (7.62 s)
 (2/2) type_specific.io-github-autotest-libvirt.filter_aready_present_binding.filter_not_define: PASS (9.96 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 19.35 s

**Comment by chunfuwen** [comment]
@yalzhang , please make sure whether it need update case name in CI job accordingly

**Comment by yalzhang** [comment]
> @yalzhang , please make sure whether it need update case name in CI job accordingly

I will update it, Thank you for reminding me.

**Comment by yalzhang** [comment]
> > @yalzhang , please make sure whether it need update case name in CI job accordingly
> 
> I will update it, Thank you for reminding me.

No need to update as in the yaml file it is the file name "filter_aready_present_binding" which do not change.

**Pull request merged**
