### PR TITLE
PCIe: pcie-root-port invalid name

### PR DESCRIPTION
**Pull request by vasekhodina**
This PR adds checks for PCIe root port controller with invalid name. The check should fail.
Automation of VIRT-47650

### CODE REVIEW

**Comment by vasekhodina** [comment]
Test results:
image

**Comment by dzhengfy** [comment]
Please hold on this pr before the https://github.com/autotest/tp-libvirt/pull/4573 is merged because there is a critical update required. See https://github.com/autotest/tp-libvirt/pull/4573#discussion_r1016406856.

**Comment by vasekhodina** [comment]
This PR depends on #4623

**Comment by vasekhodina** [comment]
Overall results from RHEL 9.2, case number 6 is the one added by this PR:
```
# avocado run --vt-type libvirt pcie_root_port_controller
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 7fb061c863cbc0927f157ddaf8d8dd74d9b036d7
JOB LOG    : /var/lib/avocado/job-results/job-2023-01-09T10.39-7fb061c/job.log
 (1/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.positive_test.controllers_different_chassis_same_port: STARTED
 (1/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.positive_test.controllers_different_chassis_same_port: PASS (63.86 s)
 (2/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.device_slot_invalid: STARTED
 (2/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.device_slot_invalid: PASS (9.49 s)
 (3/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.device_slot_wrong_number: STARTED
 (3/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.device_slot_wrong_number: PASS (9.62 s)
 (4/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.controllers_same_chassis_same_port: STARTED
 (4/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.controllers_same_chassis_same_port: PASS (11.81 s)
 (5/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.controllers_same_chassis_different_port: STARTED
 (5/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.controllers_same_chassis_different_port: PASS (12.00 s)
 (6/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.model_name_invalid: STARTED
 (6/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.model_name_invalid: PASS (9.41 s)
 (7/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.index_equals_address_bus: STARTED
 (7/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.index_equals_address_bus: PASS (9.26 s)
 (8/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.index_less_than_address_bus: STARTED
 (8/8) type_specific.io-github-autotest-libvirt.pcie_root_port_controller.negative_test.index_less_than_address_bus: PASS (9.41 s)
RESULTS    : PASS 8 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-01-09T10.39-7fb061c/results.html
JOB TIME   : 140.17 s
```

**Comment by vasekhodina** [comment]
RHEL 8.8 test in progress.

**Comment by vasekhodina** [comment]
@dzhengfy Please review this PR, when you'll have time.

**Comment by dzhengfy** [comment]
@vasekhodina , as your code changes includes other PRs' changes, I have to review it after #4591 is merged. Thanks.

**Comment by dzhengfy** [comment]
@vasekhodina please rebase

**Comment by vasekhodina** [comment]
@dzhengfy Rebase complete.

**Comment by dzhengfy** [comment]
@vasekhodina it seems we still need wait for https://github.com/autotest/tp-libvirt/pull/4623 to be merged, and then you rebase again because two prs' codes are messed up.

BTW, there are unrelated python files involved, too. Please double check.

**Pull request closed without merging**
