### PR TITLE
Fix startupPolicy failure on iscsi volume

### PR DESCRIPTION
**Pull request by chunfuwen**
After libvirt version 8.0.0, this also allows _TYPE_BLOCK volumes to use
startup policy [1].

[1]https://bugzilla.redhat.com/show_bug.cgi?id=2095758

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
2022-06-15 21:37:51,386 stacktrace       L0045 ERROR| Traceback (most recent call last):
2022-06-15 21:37:51,386 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virtual_disks/startup_policy.py", line 407, in run
2022-06-15 21:37:51,386 stacktrace       L0045 ERROR|     libvirt.check_exit_status(result, expect_error=True)
2022-06-15 21:37:51,386 stacktrace       L0045 ERROR|   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/utils_test/libvirt.py", line 1320, in check_exit_status
2022-06-15 21:37:51,386 stacktrace       L0045 ERROR|     "successfully." % result.command)
2022-06-15 21:37:51,386 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Run '/usr/bin/virsh attach-device avocado-vt-vm1 /tmp/avocado__xzgkxup/attach_disk.xml --config' expect fail, but run successfully.
2022-06-15 21:37:51,386 stacktrace       L0045 ERROR|

**Comment by chunfuwen** [comment]
@hs0210  please help take  a review.

**Comment by qiankehan** [comment]
Don't check the libvirt version.
Libvirt should always support the startupPolicy of iscsi volume. The [bug fix commit](https://gitlab.com/libvirt/libvirt/-/commit/ed8984306e1cd44c424fda3ed412a4177dd7b84d) for [BZ2095758](https://bugzilla.redhat.com/show_bug.cgi?id=2095758) indicates the unsupported result is a regression of [37f01262](https://gitlab.com/libvirt/libvirt/-/commit/37f01262eed9f37dd5eb7de8b83edd2fea741054)(since libvirt v6.1.0). So the former expectation of this case is not correct.  
BTW, **the disk with the actual local path** could support startupPolicy. It contains these disks :
- disk@type=file
- disk@type=block
- disk@type=volume AND:
  - pool@type=dir
  - pool@type=fs
  - pool@type=netfs
  - pool@type=logical
  - pool@type=disk
  - pool@type=iscsi
  - pool@type=scsi
  - pool@type=mpath

**Review by nanli1 — APPROVED** [review]

**Comment by chunfuwen** [comment]
After discussion with qiankehan, this PR only address tp-libvirt issue fix after he [bug fix commit] for [BZ2095758] introduced.
In terms of startupPolicy feature enchancement in  iscsi volume, it may need another polarion case to cover that, and not in the scope of this PR fix

**Comment by chunfuwen** [comment]
@dzhengfy , please take a look

**Comment by chunfuwen** [comment]
@dzhengfy 
please take a look

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
