### PR TITLE
graphics_functional: add case checkpoints

### PR DESCRIPTION
**Pull request by dzhengfy**
Add guest xml comparing according to the case steps
Add case ID: VIRT-60201 to test guest booting with listen type='none'
Update case ID: RHEL-171213 to test guest booting with listening on ipv4 localhost
Add case ID: VIRT-99682 to test guest booting with listen on hostname
Add case ID: VIRT-99680 to test guest booting with default vnc_listen address

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
(1/1) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_none: WARN: Test passed but there were warnings during execution. Check the log for details. (9.46 s)

**Comment by dzhengfy** [comment]
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 graphics.functional..vnc_only
 (01/40) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.default: WARN: Test passed but there were warnings during execution. Check the log for details. (9.32 s)
(40/40) type_specific.io-github-autotest-libvirt.graphics.functional.negative_tests.vnc_only.no_port_avail: WARN: Test passed but there were warnings during execution. Check the log for details. (11.38 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 4 | SKIP 0 | WARN 32 | INTERRUPT 0 | CANCEL 3
JOB HTML   : /var/lib/avocado/job-results/job-2022-08-08T04.13-22cc98f/results.html
JOB TIME   : 456.14 s
```

The Error 1 and Fail 4 cases are not run in CI jobs due to bug and not in plan tests. The CANCEL 3 are also skipped in CI jobs.

```
graphics.functional.positive_tests.vnc_only.listen_type_network 
graphics.functional.positive_tests.vnc_only.set_passwd
graphics.functional.positive_tests.vnc_only.no_autoport.port_-1
```

**Comment by dzhengfy** [comment]
@zhentang-tz Could you help review?

**Review by zhentang-tz — APPROVED** [review]

**Comment by Yingshun** [comment]
Rebase please @dzhengfy

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
