### PR TITLE
svirt: Using semanage set context persistently

### PR DESCRIPTION
**Pull request by PandaWei**
please refer to the link for more details:
 https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6
       /html/Security-Enhanced_Linux
       /sect-Security-Enhanced_Linux-SELinux_Contexts_Labeling_Files
        -Persistent_Changes_semanage_fcontext.html

### CODE REVIEW

**Comment by PandaWei** [comment]
updated it.

**Comment by PandaWei** [comment]
[root@localhost virt-test]# ./run -t libvirt --no-downloads -k --keep-image-between-tests --tests "type_specific.io-github-autotest-libvirt.svirt_start_destroy"
SETUP: PASS (0.30 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /tmp/virt-test/logs/run-2015-02-15-12.32.43/debug.log
TESTS: 44
(1/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_virt_content.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (7.10 s)
(2/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_virt_content.relabel_yes.st_static.default_model.without_qemu_conf: PASS (6.29 s)
(3/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_static.default_model.with_qemu_conf.unconfined: PASS (10.20 s)
(4/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_static.default_model.without_qemu_conf: PASS (6.17 s)
(5/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.multi_model.with_qemu_conf.unconfined: PASS (9.98 s)
(6/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.multi_model.without_qemu_conf: PASS (6.23 s)
(7/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.default_model.with_qemu_conf.unconfined: PASS (10.03 s)
(8/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.default_model.without_qemu_conf: PASS (6.19 s)
(9/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_yes.st_dynamic.no_model.with_qemu_conf.security_driver_none: PASS (10.20 s)
(10/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_yes.st_dynamic.no_model.without_qemu_conf: PASS (6.21 s)
(11/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (6.24 s)
(12/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_yes.st_static.default_model.without_qemu_conf: PASS (6.23 s)
(13/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.with_baselabel.legit.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (6.23 s)
(14/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.with_baselabel.mess_MCS.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (6.36 s)
(15/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.with_baselabel.mess_u_r.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (6.30 s)
(16/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_MCS.relabel_no.st_static.default_model.with_qemu_conf.unconfined: PASS (10.05 s)
(17/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_MCS.relabel_no.st_static.default_model.without_qemu_conf: PASS (6.22 s)
(18/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_MCS.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (6.27 s)
(19/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_MCS.relabel_yes.st_static.default_model.without_qemu_conf: PASS (6.22 s)
(20/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_virt_content.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (35.40 s)
(21/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_virt_content.relabel_yes.st_static.default_model.without_qemu_conf: PASS (19.49 s)
(22/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_svirt_img_s0.no_baselabel.relabel_no.st_static.default_model.without_qemu_conf: PASS (19.44 s)
(23/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_svirt_img_s0.no_baselabel.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (19.33 s)
(24/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_svirt_img_s0.no_baselabel.relabel_yes.st_static.default_model.without_qemu_conf: PASS (19.48 s)
(25/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_svirt_img_MCS.relabel_no.st_static.default_model.without_qemu_conf: PASS (22.39 s)
(26/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_svirt_img_MCS.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (22.42 s)
(27/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_shutdown.d_svirt_img_MCS.relabel_yes.st_static.default_model.without_qemu_conf: PASS (22.55 s)
(28/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_virt_content.relabel_no.st_static.default_model.with_qemu_conf.security_driver_none: PASS (9.45 s)
(29/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_virt_content.relabel_no.st_static.default_model.with_qemu_conf.unconfined: PASS (9.74 s)
(30/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_virt_content.relabel_no.st_static.default_model.without_qemu_conf: PASS (5.88 s)
(31/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_virt_content.relabel_yes.st_dynamic.default_model.with_qemu_conf.security_driver_none: PASS (9.42 s)
(32/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_virt_content.relabel_yes.st_static.default_model.with_qemu_conf.security_driver_none: PASS (9.45 s)
(33/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_static.default_model.with_qemu_conf.security_driver_none: PASS (9.65 s)
(34/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.multi_model.with_qemu_conf.security_driver_none: PASS (9.48 s)
(35/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.multi_model.with_qemu_conf.required_confined: PASS (9.62 s)
(36/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.default_model.with_qemu_conf.security_driver_none: PASS (9.47 s)
(37/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.default_model.with_qemu_conf.required_confined: PASS (9.48 s)
(38/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_yes.st_dynamic.default_model.with_qemu_conf.security_driver_none: PASS (9.40 s)
(39/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_yes.st_static.default_model.with_qemu_conf.security_driver_none: PASS (9.42 s)
(40/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.with_baselabel.mess_t.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (5.85 s)
(41/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_s0.with_baselabel.invalid_str.relabel_yes.st_dynamic.default_model.without_qemu_conf: PASS (5.59 s)
(42/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_MCS.relabel_no.st_static.default_model.with_qemu_conf.security_driver_none: PASS (9.41 s)
(43/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_MCS.relabel_yes.st_dynamic.default_model.with_qemu_conf.security_driver_none: PASS (9.39 s)
(44/44) type_specific.io-github-autotest-libvirt.svirt_start_destroy.negative_test.off_destroy.d_svirt_img_MCS.relabel_yes.st_static.default_model.with_qemu_conf.security_driver_none: PASS (9.40 s)
TOTAL TIME: 469.48 s (07:49)
TESTS PASSED: 44
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by will-Do** [comment]
Looks good, ack.

**Comment by yumingfei** [comment]
Thanks, applied.

**Pull request merged**
