### PR TITLE
Add new case of cloning vm with direct type interface

### PR DESCRIPTION
**Pull request by chloerh**
- Clone domain with direct type interface

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
Test result:
PASS 1-type_specific.local.virtual_network.iface_network.vm_clone_test

**Review by yalzhang — APPROVED** [review]

**Comment by chloerh** [comment]
Thanks for the review @yalzhang 
@kylazhang  Would you like to review too?

**Review by kylazhang — COMMENTED** [review]
Do we have cleanup step for cloned vm?

**Comment by kylazhang** [comment]
> Do we have cleanup step for cloned vm?

Ok, just find it as it is in the vms_list.

**Review by kylazhang — APPROVED** [review]

**Pull request merged**
