### PR TITLE
Rename main name in v2v jobs

### PR DESCRIPTION
**Pull request by mxie91**

### CODE REVIEW

**Comment by mxie91** [comment]
@xiaodwan please review the PR, do I need to remove info like '#main_vm = "XEN_VM_NAME_V2V_EXAMPLE"', below is the result:
https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/v2v/view/RHEL-9.4/job/v2v-RHEL-9.4-runtest-x86_64-acceptance-libvirt/12/testReport/

**Comment by mxie91** [comment]
@chloerh Please help merge the PR, vwu has already helped review the PR, thank you!

**Comment by mxie91** [comment]
@brucepatricklee  Please help merge the PR, vwu has already helped review the PR, thank you!

**Comment by xiaodwan** [comment]
> @xiaodwan please review the PR, do I need to remove info like '#main_vm = "XEN_VM_NAME_V2V_EXAMPLE"', below is the result: https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/v2v/view/RHEL-9.4/job/v2v-RHEL-9.4-runtest-x86_64-acceptance-libvirt/12/testReport/

Yes, Please delete them.

**Review by xiaodwan — APPROVED** [review]

**Pull request merged**
