### PR TITLE
v2v: fix the failed cases with error 'Not find cirrus device'

### PR DESCRIPTION
**Pull request by vwu-vera**
Fix the failed TCs with error 'Not find cirrus device'.

### CODE REVIEW

**Comment by vwu-vera** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.bandwidth.esx_70.rhev.rhv_upload.it_vddk.vpx_uri: PASS (383.05 s)

 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.bandwidth_file_not_exist.esx_70.rhev.rhv_upload.it_vddk.vpx_uri:PASS (316.04 s)

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
simple fix, mark it as minor_fix

**Comment by xiaodwan** [comment]
@chunfuwen I haven't reviewed this patch. The change has problem, it should not be merged so quickly.

**Pull request merged**
