### PR TITLE
migration_base: Fix None parameter

### PR DESCRIPTION
**Pull request by dzhengfy**
Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
Before the fix:
`TestError: No connection object needs to be cleaned up&#10;`

After the fix:
```
avocado run --vt-type libvirt --vt-machine-type q35 virsh.live_migration.listen_address.all_ipaddrs.ipv4.migrateuri_ipv4_addr.p2p_live.without_postcopy

JOB ID     : 54a263fd8f8f88f77e7737a6de426f5ce7222374
JOB LOG    : /root/avocado/job-results/job-2021-06-27T22.12-54a263f/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.live_migration.listen_address.all_ipaddrs.ipv4.migrateuri_ipv4_addr.p2p_live.without_postcopy: PASS (268.53 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 268.96 s

```

**Comment by dzhengfy** [comment]
@Yingshun , Please review

**Review by Yingshun — APPROVED** [review]
LGTM

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
