### PR TITLE
Add the cases of thread_pool of virtiofs

### PR DESCRIPTION
**Pull request by iccaszhulili**
Signed-off-by: Lili Zhu <lizhu@redhat.com>

Case: VIRT-294615
Bug: 2079582

### CODE REVIEW

**Comment by iccaszhulili** [comment]
@dzhengfy Please help to review https://github.com/autotest/tp-libvirt/pull/4344 and merge it. I will resolve the confilct afterwards

**Comment by iccaszhulili** [comment]
# avocado run --vt-type libvirt thread_pool_16
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : d5aebfdd07dd2a27c632d98a50ed13afc0f27c10
JOB LOG    : /var/lib/avocado/job-results/job-2022-07-31T23.24-d5aebfd/job.log
 (01/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: STARTED
 (01/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: PASS (72.71 s)
 (02/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: STARTED
 (02/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: PASS (90.58 s)
 (03/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: STARTED
 (03/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: PASS (99.49 s)
 (04/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: STARTED
 (04/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: PASS (85.11 s)
 (05/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: STARTED
 (05/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: PASS (99.42 s)
 (06/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: STARTED
 (06/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: PASS (110.59 s)
 (07/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: STARTED
 (07/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: PASS (99.96 s)
 (08/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: STARTED
 (08/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: PASS (156.06 s)
 (09/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: STARTED
 (09/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: PASS (148.96 s)
 (10/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: STARTED
 (10/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: PASS (104.53 s)
 (11/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: STARTED
 (11/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: PASS (159.12 s)
 (12/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: STARTED
 (12/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: PASS (156.96 s)
 (13/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: STARTED
 (13/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: PASS (77.67 s)
 (14/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: STARTED
 (14/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: PASS (90.00 s)
 (15/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: STARTED
 (15/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.nop.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: PASS (102.09 s)
 (16/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: STARTED
 (16/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.one_guest: PASS (85.57 s)
 (17/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: STARTED
 (17/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.one_fs.two_guests: PASS (98.81 s)
 (18/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: STARTED
 (18/18) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.memfd_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_16.multiple_fs.one_guest: PASS (108.15 s)
RESULTS    : PASS 18 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-07-31T23.24-d5aebfd/results.html
JOB TIME   : 1962.68 s

**Comment by iccaszhulili** [comment]
@dzhengfy conflict resolved, please help to review

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
