### PR TITLE
Bugfix: Fix the cases NG when the domain has cdrom in virsh-domblklist

### PR DESCRIPTION
**Pull request by liuzzfnst**
Change the autotest/tp-libvirt#552 to this branch.

When the domain has a none source cdrom driver, new_disk.source would
point to no object. And sometimes the output from xml and command output's
order is different, so we should order them and then compare them.

### CODE REVIEW

**Comment by PandaWei** [comment]
You'd better to clean up your own branch.

**Comment by Chenditang** [comment]
@PandaWei 
Updated, Thanks~~

**Comment by will-Do** [comment]
ACK

**Comment by waynesun09** [comment]
ACK and merging now, thx

**Pull request merged**
