### PR TITLE
secure_execution: fix file naming

### PR DESCRIPTION
**Pull request by smitterl**
The test couldn't be found due to filename mismatch with test type. Rename to test case name.

Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>

### CODE REVIEW

**Comment by smitterl** [comment]
```
# avocado run --vt-type libvirt --vt-machine-type s390-virtio --vt-connect-uri qemu:///system confirm_environment                                        
JOB ID     : 5a78d7cb66f59cd41f6cd1d6d1f2e27440aa1185                                                                                                                                                                       
JOB LOG    : /var/lib/avocado/job-results/job-2022-12-01T10.56-5a78d7c/job.log                                                                                                                                              
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.confirm_environment: STARTED                                                                                                                               
 (1/1) type_specific.io-github-autotest-libvirt.secure_execution.confirm_environment: PASS (17.65 s)                                                                                                                        
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0                                                                                                                                           
JOB HTML   : /var/lib/avocado/job-results/job-2022-12-01T10.56-5a78d7c/results.html                                                                                                                                         
JOB TIME   : 19.49 s                                                         
```

**Comment by smitterl** [comment]
@fbq815 @chunfuwen please help review, thanks

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by fbq815 — APPROVED** [review]

**Comment by fbq815** [comment]
LGTM

**Pull request merged**
