### PR TITLE
Fix multiattributes.file_disk.start_guest failure on s390x

### PR DESCRIPTION
**Pull request by chunfuwen**
multiattributes on disk is not supported on s390x

### CODE REVIEW

**Comment by chunfuwen** [comment]
previously failure log:

VMStartError: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'error: unsupported configuration: virtio non-transitional model not supported for this qemu(exit status: 1)&#10;

**Comment by chunfuwen** [comment]
@smitterl

**Comment by chunfuwen** [comment]
@meinaLi

**Review by smitterl — APPROVED** [review]
Thank you @chunfuwen !

**Review by meinaLi — APPROVED** [review]

**Review by Yingshun — APPROVED** [review]

**Pull request merged**
