### PR TITLE
[minor fix] virsh_nodecpumap: Fix wrong keyword

### PR DESCRIPTION
**Pull request by liuyd96**
Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>

### CODE REVIEW

**Review by chunfuwen — APPROVED** [review]
LGTM
Better upload test result

**Review by cliping — APPROVED** [review]
LGTM

**Comment by liuyd96** [comment]
> LGTM Better upload test result

Test RT. 
```
 (1/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.no_option: STARTED
 (1/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.no_option: PASS (6.20 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.pretty_option: STARTED
 (2/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.pretty_option: PASS (6.35 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.unexpect_option: STARTED
 (3/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.unexpect_option: PASS (6.12 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.cpu_off_on: STARTED
 (4/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.cpu_off_on: PASS (6.84 s)
```

**Comment by liuyd96** [comment]
@chunfuwen @cliping Gently ping. Sorry for the noise, I have a commit which depends on this PR.
Because it is a moniro fix. Please help review/merge it. Thanks.

**Pull request merged**
