### PR TITLE
numa_topology_with_cpu_topology: add case

### PR DESCRIPTION
**Pull request by dzhengfy**
Case ID: VIRT-296723 - Numa topology with cpu topology

### CODE REVIEW

**Comment by dzhengfy** [comment]
Depend on
- https://github.com/autotest/tp-libvirt/pull/4870

**Comment by dzhengfy** [comment]
```
 (1/1) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_with_order: PASS (63.86 s)

 (1/1) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_without_order: PASS (63.63 s)

```

**Comment by dzhengfy** [comment]
@liang-cong-red-hat, could you help review it?

**Review by Yingshun — APPROVED** [review]
LGTM

**Review by chloerh — APPROVED** [review]

**Pull request merged**
