### PR TITLE
Update for the comments in previous review for transitional memory balloon test

### PR DESCRIPTION
**Pull request by kylazhang**
Signed-off-by: Kyla Zhang <weizhan@redhat.com>

Refer to https://github.com/autotest/tp-libvirt/pull/2443 comments

### CODE REVIEW

**Comment by kylazhang** [comment]
@smitterl please help to check if it match all your review comments, thanks.

**Comment by chunfuwen** [comment]
is there any test result available?

**Comment by kylazhang** [comment]
@chunfuwen It is only reply the comments for qianqian's last pr as she will leave for several month. So more test will show in the job later.

**Comment by kylazhang** [comment]
Hi @smitterl, I think the method which qianqian used is normal for us as we usually setting parameters in cfg file instead of py code. And I think it is clear in cfg as in the py code params.set('disk_model', virtio_model) is also the same meaning. More need to do is maybe add a comment in cfg to make it clear.

**Comment by kylazhang** [comment]
@smitterl  OK, after check more detailed I think you are right. I will update soon.

**Comment by Yingshun** [comment]
**Test result:**
```
(.libvirt-ci-venv-ci-runtest-SHzbMm) [root@yicui-host1 tp-libvirt]# git log
commit 94f6572e8b3aa07c61fdb087fb15b73d2885ecca (HEAD -> master)
Author: Kyla Zhang <weizhan@redhat.com>
Date:   Thu Jan 9 11:58:18 2020 +0800

    Update for the comments in previous review for transitional memory balloon test
    
    Signed-off-by: Kyla Zhang <weizhan@redhat.com>

commit 1fb3ef621f473a878986c58c9786fcf4325354d4 (origin/master, origin/HEAD)
... ... 
(.libvirt-ci-venv-ci-runtest-SHzbMm) [root@yicui-host1 tp-libvirt]# avocado run --vt-type libvirt  virtio_transitional_mem_balloon.default.virtio --vt-machine-type q35 
JOB ID     : d3c4770dd533906e678b52e05cdaf24e370750b9
JOB LOG    : /root/avocado/job-results/job-2020-01-13T01.10-d3c4770/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtio_transitional_mem_balloon.default.virtio: PASS (45.61 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 47.05 s
(.libvirt-ci-venv-ci-runtest-SHzbMm) [root@yicui-host1 tp-libvirt]# 

```

**Pull request merged**
