### PR TITLE
virsh_nodeinfo: fix incorrect checkpoints

### PR DESCRIPTION
**Pull request by dzhengfy**
Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
Before fix:
[virsh.nodeinfo.disable_enable_vcpu]
TestFail: Command cat /proc/cpuinfo |grep "physical id"|sort |uniq|wc -l output 2 isn't equal to NUMA cell(s) 1 * CPU sockets 1

**Comment by dzhengfy** [comment]
(1/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.no_option: STARTED
 (1/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.no_option: PASS (4.99 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.disable_enable_vcpu: STARTED
 (2/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.disable_enable_vcpu: PASS (5.39 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.unexpect_option: STARTED
 (3/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.unexpect_option: PASS (4.03 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.with_libvirtd_stop: STARTED
 (4/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.with_libvirtd_stop: PASS (4.28 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-05-07T09.01-1200c66/results.html
JOB TIME   : 33.22 s
libvirt-8.3.0-1.el9.x86_64

**Comment by dzhengfy** [comment]
@iccaszhulili could you help review?

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by cliping — APPROVED** [review]
LGTM

**Review by iccaszhulili — APPROVED** [review]

**Comment by iccaszhulili** [comment]
LGTM

**Pull request merged**
