### PR TITLE
Fix event case failure

### PR DESCRIPTION
**Pull request by chunfuwen**
Fix event case failure
io-error-reason event type is converged into io-error after libvirt version 9.0.0

### CODE REVIEW

**Comment by chunfuwen** [comment]
previously failed:
 TestFail: Not find expected event:event 'io-error-reason' for domain.*avocado-vt-vm1.*: /tmp/avocado_kny3pfiq/avocado-vt-vm1_new_disk.img \(virtio-disk1\) pause due to enospc. Is your guest too slow to get started in Nones?&#10

2023-05-08 00:08:48,270 virsh_event      L0616 DEBUG| my event_idx is 0
2023-05-08 00:08:48,270 virsh_event      L0625 INFO | Expected event: event 'io-error' for domain.*avocado-vt-vm1.*: /tmp/avocado_kny3pfiq/avocado-vt-vm1_new_disk.img \(virtio-disk1\) pause
2023-05-08 00:08:48,270 virsh_event      L0616 DEBUG| my event_idx is 812
2023-05-08 00:08:48,271 virsh_event      L0625 INFO | Expected event: event 'io-error-reason' for domain.*avocado-vt-vm1.*: /tmp/avocado_kny3pfiq/avocado-vt-vm1_new_disk.img \(virtio-disk1\) pause due to enospc
2023-05-08 00:08:48,303 libvirt_vm       L2217 DEBUG| Destroying VM

**Comment by chunfuwen** [comment]
Command 'virsh list' finished with 0 after 0.032555237s
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.io-error_event.no_timeout.loop

**Review by cliping — APPROVED** [review]
LGTM

**Review by nanli1 — APPROVED** [review]

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
