### PR TITLE
v2v:add win11/win2022 to convert_vm_to_ovirt

### PR DESCRIPTION
**Pull request by vwu-vera**
Signed-off-by: vwu-vera <vwu@redhat.com>

fix acceptance failed cases.

### CODE REVIEW

**Comment by vwu-vera** [comment]
(1/1) type_specific.io-github-autotest-libvirt.convert_vm_to_ovirt.esx.vm.7_0.windows.win11.arch_x86_64.qcow2_f.NFS.rhv_upload.rhv_direct.rhv_verifypeer.sparse.it_vddk: PASS (2721.21 s)

**Comment by vwu-vera** [comment]
@xiaodwan Please help to review. Thanks.

**Comment by xiaodwan** [comment]
The fix is wrong. 
First, you should make sure virtio-win has those drivers for them. Then you can consider how to fix it.
And you should also consider the code works on both rhel8 and rhel9.
Since QXL is depracated in rhel9, the warning checking is not necessary any more.

**Comment by xiaodwan** [comment]
I pushed a PR for this issue. 
https://github.com/autotest/tp-libvirt/pull/4005
You may learn the whole process of solving the issue.
And make sure to add some comments for your code if it's hard to understand by others.

**Pull request closed without merging**
