### PR TITLE
Fix the serial source path permission issues in rhel9

### PR DESCRIPTION
**Pull request by jinqi7**
Signed-off-by: qijing <jinqi@redhat.com>

The serial source path can't use /var/log in rhel9 for having permission issues

### CODE REVIEW

**Comment by jinqi7** [comment]
avocado run --vt-type libvirt  virsh.attach_device.character.serial.multi_serial.without_alias.normal_test.cold_attach_hot_vm.name_ref.file_argument.domain_argument
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : b6f29faa2d9511e6af0bd5a896f72e6ab72a0711
JOB LOG    : /root/avocado/job-results/job-2021-06-28T05.13-b6f29fa/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.attach_device.character.serial.multi_serial.without_alias.normal_test.cold_attach_hot_vm.name_ref.file_argument.domain_argument: PASS (42.65 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 43.25 s

**Comment by jinqi7** [comment]
avocado run --vt-type libvirt serial.functional.type_file
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 3b062151218908ec37ce47abf993691ad8447b47
JOB LOG    : /root/avocado/job-results/job-2021-06-28T05.09-3b06215/job.log
 (1/1) type_specific.io-github-autotest-libvirt.serial.functional.type_file: PASS (30.06 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Comment by jinqi7** [comment]
avocado run --vt-type libvirt virsh.detach_serial_device_alias.serial_type_file.pci-serial 
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 5e94fa4ce05d4e253acb536cff41411f91cc8323
JOB LOG    : /root/avocado/job-results/job-2021-06-28T04.48-5e94fa4/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.detach_serial_device_alias.serial_type_file.pci-serial: PASS (17.95 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 18.57 s

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by kylazhang — APPROVED** [review]

**Pull request merged**
