### PR TITLE
Revert some PRs

### PR DESCRIPTION
**Pull request by hsmj1412**

### CODE REVIEW

**Comment by hsmj1412** [comment]
@balamuruhans Any replace in your local eviroment? such as server_ip, client_ip, nfs_locally_setup, storage_type=nfs could not be found in param list

**Comment by chunfuwen** [comment]
@hsmj1412 ,suggest paste some error log here for enabling debug

**Comment by balamuruhans** [comment]
@hsmj1412 yes, you are right, we need to set the params,
```
disk_target = sda
setup_local_nfs = yes

# NFS related configurations
storage_type = nfs
nfs_mount_dir=/home/bala/sharing
nfs_mount_options="rw"
export_options=rw,sync,no_root_squash
nfs_mount_src=/home/bala/NFS
export_dir=/home/bala/NFS

# libvirt (host information for remote testcases)
local_ip = "10.1.1.20"
local_pwd = "password"

# Default password is same as local_pwd
remote_ip = "10.1.1.21"
remote_pwd = "password"
remote_user = "root"

# params for env_process to take care migration setup
server_ip = "${remote_ip}"
server_pwd = "${remote_pwd}"
server_user = "root"

# Migration source and destination machine details
migrate_source_host = "${local_ip}"
migrate_source_pwd = "${local_pwd}"
migrate_dest_host = "${remote_ip}"
migrate_dest_pwd = "${remote_pwd}"

# This param required for testcases with hugepages
hugepage_force_allocate = "yes"
```

**Comment by balamuruhans** [comment]
we can fix this concern by including these params as part of virsh_migrate.cfg ?

**Comment by hsmj1412** [comment]
@dzhengfy Please help check

**Comment by dzhengfy** [comment]
@balamuruhans @hsmj1412 , I have fixed this problem by https://github.com/autotest/tp-libvirt/pull/1532
Please help to check.

**Comment by dzhengfy** [comment]
I'v fixed the problem in https://github.com/autotest/tp-libvirt/pull/1532. Please help check.

**Pull request closed without merging**
