### PR TITLE
Add more time wait function during guest operation for rhel6 guest.

### PR DESCRIPTION
**Pull request by rbian**

### CODE REVIEW

**Comment by Hao-Liu** [comment]
This PR LGTM if CI passed and dependence merged.

**Comment by will-Do** [comment]
Patch is OK. Just a suggestion for the concise of the code.
1. The ```if``` sentence is a bit long, it's not necessary to use ```re``` for this str judgement, and use ```any``` maybe a good choice.
2. For the wait func, you can define a tiny function for calling, such as:
``` def f(): return vm.state == True```

**Comment by rbian** [comment]
Thanks @will-Do , updated the code.

**Comment by will-Do** [comment]
Merge this PR now

**Pull request merged**
