### PR TITLE
virsh_reboot: improve and perfect the exception handling

### PR DESCRIPTION
**Pull request by PandaWei**
* qemu-guest-agent is not supported on RHEL5.
  and all of cases about qemu-guest-agent should skip, not fail.

* remove 'FIXME' and catch the specific exception

### CODE REVIEW

**Comment by PandaWei** [comment]
This PR has relationship with virt-test#2143

**Comment by yangdongsheng** [comment]
Fine to me

**Comment by will-Do** [comment]
ACK.
@PandaWei BTW, next time you can paste the integral URL in your comment.

**Comment by PandaWei** [comment]
OK, thanks for your reminder.
I will do it as your suggestion.

**Comment by Hao-Liu** [comment]
Merging this. Thanks @PandaWei @yangdongsheng @will-Do.

**Pull request merged**
