### PR TITLE
virsh_domain: Xml to native, quotes in XML output

### PR DESCRIPTION
**Pull request by vasekhodina**
The output, when printing VM configuration from XML contains quotes when describing character device. The same output when printing VM config from native doesn't contain the quotes, so the device argument needs to be added to a list of arguments that should have the quotes removed.

### CODE REVIEW

**Comment by vasekhodina** [comment]
Test on RHEL 9.1 including this PR.
`[root@libvirt-rhel-8-6-x86-64-virsh-domain-rdu-redhat-com ~]# avocado run --vt-type libvirt virsh.domxml_to_native
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 0bff95f8c23207d4d629e82647581d64c6b05770
JOB LOG    : /var/lib/avocado/job-results/job-2022-05-06T10.14-0bff95f/job.log
 (01/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_option: STARTED
 (01/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_option: PASS (69.71 s)
 (02/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.expected_option: STARTED
 (02/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.expected_option: PASS (66.87 s)
 (03/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.invalid_format_option: STARTED
 (03/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.invalid_format_option: PASS (66.02 s)
 (04/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.extra_option: STARTED
 (04/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.extra_option: PASS (65.70 s)
 (05/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_file_extra_option: STARTED
 (05/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_file_extra_option: PASS (66.87 s)
 (06/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.with_libvirtd_stop: STARTED
 (06/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.with_libvirtd_stop: PASS (67.06 s)
 (07/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.readonly_mode: STARTED
 (07/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.readonly_mode: PASS (66.17 s)
 (08/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.id_option: STARTED
 (08/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.id_option: PASS (65.59 s)
 (09/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.uuid_option: STARTED
 (09/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.uuid_option: PASS (65.60 s)
 (10/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.name_option: STARTED
 (10/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.name_option: PASS (65.68 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-05-06T10.14-0bff95f/results.html
JOB TIME   : 672.76 s`

**Comment by vasekhodina** [comment]
Test on RHEL 9.1 including the PR.
`(.libvirt-ci-venv-ci-runtest-kFBaqU) [root@dell-per740-03 ~]# avocado run --vt-type libvirt virsh.domxml_to_native
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : d987f86357af8e99b1cdbff4248dce83e484b390
JOB LOG    : /var/lib/avocado/job-results/job-2022-05-09T10.14-d987f86/job.log
 (01/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_option: STARTED
 (01/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_option: PASS (54.93 s)
 (02/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.expected_option: STARTED
 (02/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.expected_option: PASS (55.16 s)
 (03/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.invalid_format_option: STARTED
 (03/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.invalid_format_option: PASS (56.87 s)
 (04/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.extra_option: STARTED
 (04/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.extra_option: PASS (56.75 s)
 (05/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_file_extra_option: STARTED
 (05/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.no_file_extra_option: PASS (56.87 s)
 (06/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.with_libvirtd_stop: STARTED
 (06/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.with_libvirtd_stop: PASS (57.09 s)
 (07/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.readonly_mode: STARTED
 (07/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.readonly_mode: PASS (56.89 s)
 (08/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.id_option: STARTED
 (08/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.id_option: PASS (56.82 s)
 (09/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.uuid_option: STARTED
 (09/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.uuid_option: PASS (56.30 s)
 (10/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.name_option: STARTED
 (10/10) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.name_option: PASS (56.97 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-05-09T10.14-d987f86/results.html
JOB TIME   : 570.53 s
(.libvirt-ci-venv-ci-runtest-kFBaqU) [root@dell-per740-03 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.1 Beta (Plow)
(.libvirt-ci-venv-ci-runtest-kFBaqU) [root@dell-per740-03 ~]# virsh -V
Virsh command line tool of libvirt 8.3.0
See web site at https://libvirt.org/

Compiled with support for:
 Hypervisors: QEMU/KVM ESX Test
 Networking: Remote Network Bridging Interface udev Nwfilter
 Storage: Dir Disk Filesystem SCSI Multipath iSCSI LVM RBD
 Miscellaneous: Daemon Nodedev SELinux Secrets Debug DTrace Readline
(.libvirt-ci-venv-ci-runtest-kFBaqU) [root@dell-per740-03 ~]#`

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
@vasekhodina please help squash the two commits into one which is our usual way for fixing one issue.  After that,  I will merg e this PR. Thanks.

**Comment by dzhengfy** [comment]
@vasekhodina it seems messed up with other commits finally. Please check again.

**Comment by chunfuwen** [comment]
@vasekhodina 
your commit includes 26 file changes, I assume that is not your intention.
You may incorporate other not-related changes in this PR

**Comment by vasekhodina** [comment]
Closing as the branch containing the changes in this branch are to tangled and complicated to merge.

**Pull request closed without merging**
