### PR TITLE
v2v: Add a new case about reducing v2v log size

### PR DESCRIPTION
**Pull request by xiaodwan**
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by xiaodwan** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/2741

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.log_size_decrease.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (1743.84 s)

**Comment by xiaodwan** [comment]
@chloerh @yantian0 Please help to review this PR, thanks.

**Review by yantian0 — APPROVED** [review]

**Pull request merged**
