### PR TITLE
attach_detach_disk: fix disk discovery

### PR DESCRIPTION
**Pull request by smitterl**
The code compared old and new listing of impersistent disk names, e.g. 'vdX'. Those names can change between reboots.

Instead, use function to identify new disks that don't mount the root file system.

The function raises an error if there is no such disk, so handle that to confirm that disks are detached correctly.

### CODE REVIEW

**Comment by smitterl** [comment]
@chunfuwen Please help review

**Comment by smitterl** [comment]
```
JOB ID     : f50eb82835138f9fa7659a3132b6e5f46fe5bedd
JOB LOG    : /var/lib/avocado/job-results/job-2024-02-08T12.10-f50eb82/job.log
 (01/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.invalid_vm_id: PASS (21.89 s)
 (02/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.invalid_target: PASS (19.10 s)
 (03/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.invalid_option_1: PASS (21.39 s)
 (04/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.invalid_option_2: PASS (21.83 s)
 (05/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.invalid_source: PASS (21.06 s)
 (06/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.twice_diff_source: PASS (22.11 s)
 (07/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.invalid_driver: PASS (19.50 s)
 (08/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.invalid_mode: PASS (21.79 s)
 (09/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.non_exist_source: PASS (20.05 s)
 (10/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.ide_bus: PASS (19.23 s)
 (11/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.invalid_cache: PASS (21.03 s)
 (12/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.hotplug_ccw: PASS (18.82 s)
 (13/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.error_test.only_attach_disk.invalid_scsi_address: PASS (18.82 s)
 (14/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.host_block_vm_name: PASS (22.99 s)
 (15/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.vm_suspend: PASS (24.47 s)
 (16/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.host_block_vm_uuid: PASS (21.96 s)
 (17/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.image_file_no_option: PASS (19.30 s)
 (18/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.vm_shutdown_config: PASS (27.18 s)
 (19/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.vm_shutdown_serial_config: PASS (28.05 s)
 (20/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.vm_shutdown_persistent: PASS (25.76 s)
 (21/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_diff_target: PASS (22.60 s)
 (22/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_same_target_diff_scsi_address: PASS (23.48 s)
 (23/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_multifunction_with_shareable: PASS (29.19 s)
 (24/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.cdrom_eject_control: PASS (37.82 s)
 (25/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.attach_disk_type.file_disk_type: PASS (19.57 s)
 (26/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.attach_disk_type.block_disk_type: PASS (36.03 s)
 (27/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.attach_disk_type.block_disk_type_logical: PASS (36.91 s)
 (28/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.attach_disk_type.block_disk_attach_twice_with_systemlink_change: PASS (44.46 s)
 (29/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.audit_check: PASS (21.05 s)
 (30/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.attach_disk_image_format.qcow2_format: PASS (22.28 s)
 (31/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.image_file_no_mode: PASS (21.72 s)
 (32/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.no_mode: PASS (19.51 s)
 (33/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.option_sourcetype: PASS (22.16 s)
 (34/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.option_cache.cache_none: PASS (22.26 s)
 (35/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.option_cache.cache_default: PASS (19.49 s)
 (36/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.option_cache.cache_writethrough: PASS (19.48 s)
 (37/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.option_cache.cache_writeback: PASS (19.63 s)
 (38/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.option_cache.cache_unsafe: PASS (21.12 s)
 (39/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.only_attach_disk.option_cache.cache_directsync: PASS (19.28 s)
 (40/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.error_test.no_vm_name: PASS (24.36 s)
 (41/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.error_test.hex_vm_id: PASS (24.89 s)
 (42/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.error_test.invalid_vm_uuid: PASS (21.78 s)
 (43/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.error_test.vm_shutdown: PASS (29.32 s)
 (44/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.error_test.only_detach_disk.no_attach: PASS (31.55 s)
 (45/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.error_test.only_detach_disk.no_target: PASS (31.78 s)
 (46/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.host_block_vm_id: PASS (22.29 s)
 (47/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.vm_running_config: PASS (22.19 s)
 (48/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.vm_running_persistent: PASS (24.73 s)
 (49/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.twice_diff_target_with_shareable: PASS (26.95 s)
 (50/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.cdrom: PASS (29.03 s)
 (51/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.special_disk_name.local_disk_name: PASS (21.38 s)
 (52/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.special_disk_name.attch_disk_name: PASS (21.83 s)
 (53/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.detach_disk_with_print_xml: PASS (21.69 s)
 (54/54) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.attach_disk_image_format.raw_format: PASS (24.61 s)
RESULTS    : PASS 54 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2024-02-08T12.10-f50eb82/results.html
JOB TIME   : 1294.19 s
```

**Review by chunfuwen — APPROVED** [review]
lgtm

**Comment by chunfuwen** [comment]
minor change, mark it as minor_fix

**Pull request merged**
