### PR TITLE
fix vm shutdown timeout issue in extreme case

### PR DESCRIPTION
**Pull request by chunfuwen**
Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
use vm.destroy(gracefully=true) to ensure that vm is shutdown gracefully.

**Comment by chunfuwen** [comment]
@will-Do 
@balamuruhans 

Please take a look.

**Comment by chunfuwen** [comment]
@balamuruhans 
Could you do me a favour to have a look?

**Comment by will-Do** [comment]
Merge this trivial fix

**Pull request merged**
