### PR TITLE
iface_network: use nft for new product

### PR DESCRIPTION
**Pull request by yanqzhan**
Replace an ip6tables usage with nft for new product which use the default firewall_backend='nftables'.

### CODE REVIEW

**Comment by yanqzhan** [comment]
1. `# tail -3 /etc/libvirt/network.conf 
#   reloaded using the new backend.)
#
#firewall_backend = "nftables"`

JOB LOG    : /var/log/avocado/job-results/job-2024-06-27T07.22-2ea5210/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.net_forward.net_nat.nat_ipv6: PASS (86.92 s)

# grep nft /var/log/avocado/job-results/job-2024-06-27T07.22-2ea5210/job.log
2024-06-27 07:22:24,757 output           L0702 DEBUG| [stderr] DEBUG:root:firewall_backend is: nftables
2024-06-27 07:23:40,476 process          L0658 INFO | Running 'nft list chain  ip6 libvirt_network  guest_nat'
2024-06-27 07:23:40,480 process          L0739 INFO | Command 'nft list chain  ip6 libvirt_network  guest_nat' finished with 0 after 0.003687063s

2.`# tail -3 /etc/libvirt/network.conf 
#
#firewall_backend = "nftables"
firewall_backend = "iptables"
`
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.net_forward.net_nat.nat_ipv6: PASS (46.26 s)
# grep -E 'iptables|ip6tables' /var/log/avocado/job-results/job-2024-06-27T07.24-1791a36/job.log
2024-06-27 07:24:43,919 output           L0702 DEBUG| [stderr] DEBUG:root:this firewall_backend: iptables
2024-06-27 07:24:43,920 output           L0702 DEBUG| [stderr] DEBUG:root:firewall_backend is: iptables
2024-06-27 07:25:18,748 process          L0658 INFO | Running 'ip6tables -t nat -L'
2024-06-27 07:25:18,758 process          L0739 INFO | Command 'ip6tables -t nat -L' finished with 0 after 0.009259346s
2024-06-27 07:25:18,760 output           L0702 DEBUG| [stderr] DEBUG:aexpect.client:Sending command: ip6tables -F
2024-06-27 07:25:19,990 process          L0658 INFO | Running 'ip6tables -F'
2024-06-27 07:25:20,010 process          L0739 INFO | Command 'ip6tables -F' finished with 0 after 0.019316861s
2024-06-27 07:25:25,084 process          L0658 INFO | Running 'ip6tables-save'
2024-06-27 07:25:25,086 process          L0470 DEBUG| [stdout] # Generated by ip6tables-save v1.8.10 (nf_tables) on Thu Jun 27 07:25:25 2024
2024-06-27 07:25:25,086 process          L0739 INFO | Command 'ip6tables-save' finished with 0 after 0.002193202s
2024-06-27 07:25:25,087 process          L0470 DEBUG| [stdout] # Generated by ip6tables-save v1.8.10 (nf_tables) on Thu Jun 27 07:25:25 2024
2024-06-27 07:25:25,088 process          L0470 DEBUG| [stdout] # Generated by ip6tables-save v1.8.10 (nf_tables) on Thu Jun 27 07:25:25 2024

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
depend on 
- https://github.com/autotest/tp-libvirt/pull/5738

**Comment by yanqzhan** [comment]
The depending one will not be merged. Revert this one by https://github.com/autotest/tp-libvirt/pull/5838/files

**Pull request merged**
