### PR TITLE
virtio_transitional: Add test case for device rng

### PR DESCRIPTION
**Pull request by vivianQizhu**
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@kylazhang Please help review. The failure is very like a product issue. 
When trying to plug virtio model rng device to pcie-to-pci-bridge, if slot is 0, then guest can not detect it; If slot is 1, then it reports duplicated usage but actually no other device occupy it; While if slot is 2, then it reports `error: XML error: Invalid PCI address 0000:08:02.0. slot must be <= 0`, that's super weird.

```
22:07:38 DEBUG| Attach rng by XML: <?xml version='1.0' encoding='UTF-8'?>
<rng model="virtio"><backend model="random">/dev/urandom</backend><address bus="0x08" slot="0x02" type="pci" /></rng>
22:07:38 DEBUG| Running virsh command: attach-device avocado-vt-vm1 /var/tmp/xml_utils_temp_vp3rhchf.xml
22:07:38 INFO | Running '/bin/virsh attach-device avocado-vt-vm1 /var/tmp/xml_utils_temp_vp3rhchf.xml'
22:07:38 DEBUG| [stderr] error: Failed to attach device from /var/tmp/xml_utils_temp_vp3rhchf.xml
22:07:38 DEBUG| [stderr] error: XML error: Invalid PCI address 0000:08:02.0. slot must be <= 0
22:07:38 DEBUG| [stdout]
22:07:38 INFO | Command '/bin/virsh attach-device avocado-vt-vm1 /var/tmp/xml_utils_temp_vp3rhchf.xml' finished with 1 after 0.018305301666259766s
22:07:38 DEBUG| status: 1
22:07:38 DEBUG| stdout:
22:07:38 DEBUG| stderr: error: Failed to attach device from /var/tmp/xml_utils_temp_vp3rhchf.xml
error: XML error: Invalid PCI address 0000:08:02.0. slot must be <= 0
```

```
 (1/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.default.boot_test.virtio: PASS (89.50 s)
 (2/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.default.boot_test.virtio_non_transitional: PASS (89.72 s)
 (3/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.default.boot_test.virtio_transitional: PASS (86.59 s)
 (4/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.default.hotplug_test.virtio_transitional: PASS (46.51 s)
 (5/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.boot_test.virtio: ERROR: Failed to define avocado-vt-vm1 from xml:\n<?xml version='1.0' encoding='UTF-8'?>\n<domain type="kvm">\n  <name>avocado-vt-vm1</name>\n  <uuid>8634d0c5-0a1f-4c00-959b-a094d37c044a</uuid>\n  <metadata>\n    <ns0:libosinfo xmlns:ns0="http://libosinfo.org/xmlns/li... (3.75 s)
 (6/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.boot_test.virtio_transitional: PASS (57.38 s)
 (7/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.hotplug_test.virtio: FAIL: error: Failed to attach device from /var/tmp/xml_utils_temp_vp3rhchf.xml\nerror: XML error: Invalid PCI address 0000:08:02.0. slot must be <= 0\n (26.06 s)
 (8/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.hotplug_test.virtio_transitional: PASS (44.34 s)
```

**Comment by vivianQizhu** [comment]
@kylazhang Sorry, ignore me, just found that the pcie-to-pci-bridge is not added successfully. Thanks.

**Comment by vivianQizhu** [comment]
@kylazhang Test passed, please help review, thanks.
```
 (1/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.default.boot_test.virtio: PASS (99.90 s)
 (2/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.default.boot_test.virtio_non_transitional: PASS (90.37 s)
 (3/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.default.boot_test.virtio_transitional: PASS (62.88 s)
 (4/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.default.hotplug_test.virtio_transitional: PASS (46.36 s)
 (5/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.boot_test.virtio: PASS (60.90 s)
 (6/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.boot_test.virtio_transitional: PASS (59.87 s)
 (7/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.hotplug_test.virtio: PASS (47.31 s)
 (8/8) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.hotplug_test.virtio_transitional: PASS (44.02 s)
```

**Comment by kylazhang** [comment]
Thanks for all the comments, as vivianQizhu will be offline for more than 4 month, I suggest to merge the new file first and then submit the fix by others.

**Pull request merged**
