### PR TITLE
virtual_disks_multidisks: Fix "No more PCI slots" error for aarch64

### PR DESCRIPTION
**Pull request by liuyd96**
Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
code looks fine to me, but please provide some basic validation results.

**Comment by liuyd96** [comment]
Hi, @chunfuwen 
> but please provide some basic validation results

Sorry for the delay, i planned to test all related cases but that will cost a lot of time...
Then i picked some known NG to verify this commit.

**virsh_attach_device**
before this commit:
```
# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio \
> virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 28455a96eb01e187afd180423217fbead6011823
JOB LOG    : /root/avocado/job-results/job-2021-04-25T23.32-28455a9/job.log
 (1/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional:FAIL: Positive operational test failed (43.57 s)
 (2/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (44.07 s)
 (3/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (43.87 s)
 (4/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (43.64 s)
 (5/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (42.76 s)
 (6/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (43.35 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 6 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 262.28 s
```
after this commit:
```
# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio \
> virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional \
> virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 0439dea061191f9b5bfac9e37b4203f78034a4f0
JOB LOG    : /root/avocado/job-results/job-2021-04-25T23.01-0439dea/job.log
 (1/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional:PASS (228.02 s)
 (2/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: PASS (225.36 s)
 (3/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional: PASS (314.75 s)
 (4/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional: PASS (224.58 s)
 (5/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: PASS (342.83 s)
 (6/6) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional: PASS (315.07 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1651.70 s
```

**Comment by liuyd96** [comment]
**virsh_attach_device**
Before this commit
```
# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virtual_disks.multidisks.hotplug.multi_disks_test.virtio_disks_format
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 0b0f2acdc97e65ab986b4e32080d7248dfbf7a2f
JOB LOG    : /root/avocado/job-results/job-2021-04-25T23.38-0b0f2ac/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.hotplug.multi_disks_test.virtio_disks_format: FAIL: error: Failed to attach device from /tmp/xml_utils_temp_ccs_txn5.xml\nerror: internal error: No more available PCI slots\n (43.41 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 44.28 s
```
After this commit
```
# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virtual_disks.multidisks.hotplug.multi_disks_test.virtio_disks_format
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : b807cfbb816e7e8dfd1ffa42d1b36846037ebfca
JOB LOG    : /root/avocado/job-results/job-2021-04-25T23.41-b807cfb/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.hotplug.multi_disks_test.virtio_disks_format: PASS (71.03 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 71.91 s

```

**Comment by liuyd96** [comment]
@chloerh Thanks.

**Comment by liuyd96** [comment]
TODO: Part of this commit is duplicated of https://github.com/autotest/tp-libvirt/commit/10b7fac6f5d9929031ad69e08bfab67a59b85103
But that commit is q35 only, i will remove these duplicates after i verify it on q35

**Comment by liuyd96** [comment]
> TODO: Part of this commit is duplicated of [10b7fac](https://github.com/autotest/tp-libvirt/commit/10b7fac6f5d9929031ad69e08bfab67a59b85103)
> But that commit is q35 only, I will remove these duplicates after verifying on q35

Update this PR, only fix virtual_disks_multidisks job.
virsh_attach_device job should also be verified on q35. I will send a new PR about it.

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by chloerh — APPROVED** [review]
Thank u for taking my advice.

**Pull request merged**
