### PR TITLE
virsh_detach_device_alias: Fix tmp file removed

### PR DESCRIPTION
**Pull request by dzhengfy**
Adjust the invoke method for the utility function in avocado-vt 2988.

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
On ci provisioned machine:

```
#  avocado run --vt-type libvirt --vt-machine-type q35 virsh.detach_device_alias
JOB ID     : d011bad7a866728bf768f1458dad66d23b26f088
JOB LOG    : /root/avocado/job-results/job-2021-04-02T01.05-d011bad/job.log
 (01/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.hostdev: PASS (53.44 s)
 (02/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.controller: PASS (55.63 s)
 (03/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.redirdev: PASS (53.94 s)
 (04/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.channel: PASS (53.59 s)
 (05/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.hostdev: PASS (54.39 s)
 (06/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.controller: PASS (53.89 s)
 (07/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.redirdev: PASS (52.65 s)
 (08/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.channel: PASS (54.73 s)
 (09/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.hostdev: PASS (56.26 s)
 (10/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.controller: PASS (55.01 s)
 (11/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.redirdev: PASS (55.07 s)
 (12/12) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.channel: PASS (54.81 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 654.52 s
```

**Comment by dzhengfy** [comment]
Depend on https://github.com/avocado-framework/avocado-vt/pull/2988

**Review by chloerh — APPROVED** [review]
Yes, these are the files that have references of `create_hostdev_xml()`. 
Seems ok. I guess you could merge the 2 prs yourself at **the same time** when they're ready. :joy:

**Comment by dzhengfy** [comment]
Before the fix:
Cases will get below error:
`CmdError: Command '/bin/virsh attach-device avocado-vt-vm1 /tmp/xml_utils_temp_9exbbws7.xml --current' failed.stdout: b'\n'stderr: b"error: Failed to open file '/tmp/xml_utils_temp_9exbbws7.xml': No such file or directory\n"additional_info: None`

**Review by Yingshun — APPROVED** [review]
LGTM.

**Comment by dzhengfy** [comment]
This PR should be merged together with avocado-vt 2988.

**Review by chunfuwen — APPROVED** [review]
lgtm

**Comment by chunfuwen** [comment]
let''s merge first, and observe the result

**Pull request merged**
