### PR TITLE
fix rbd image size issue

### PR DESCRIPTION
**Pull request by nanli1**
Before fixing:

ShellTimeoutError: Timeout expired while waiting for shell command to complete: 'sha256sum /dev/vdb'    (output: '')&#10;

After fixing:
All passed in jenkins jobs

### CODE REVIEW

**Comment by harihare** [comment]
Can you please provide the description for this fix.

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
@nanli1 ,please upload test result as well

**Comment by nanli1** [comment]
> @nanli1 ,please upload test result as well

I ran this pr with jenkins job, because it' related too many cases .
Could I set jenkins job link here?

**Review by chloerh — APPROVED** [review]

**Comment by nanli1** [comment]
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.blockdev_option.rbd_with_auth_disk.blockdev --vt-connect-uri qemu:///system  PASS (29.31 s)
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.blockdev_option.rbd_with_auth_disk.blockdev_and_shallow --vt-connect-uri qemu:///system  PASS (29.31 s)
```

**Pull request merged**
