### PR TITLE
Fix blockcopy slice case failure

### PR DESCRIPTION
**Pull request by chunfuwen**
slice_offset+slice_size need be equal to size of src_img
as per description in [1]

[1]https://github.com/autotest/tp-libvirt/issues/3751

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.ceph.hot_plug.with_auth.default.rbd_blockcopy.slices_reuse_external

**Comment by chunfuwen** [comment]
@qiankehan , please take a look

**Review by qiankehan — APPROVED** [review]
LGTM. Better if provide the test results.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
