### PR TITLE
Fix Those issues are relative to vm.define without --nvram option

### PR DESCRIPTION
**Pull request by chunfuwen**
Fix them by adding addtional option:--nvram

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Review by cliping — APPROVED** [review]
LGTM

**Comment by cliping** [comment]
Please add test result, thanks.

**Comment by chunfuwen** [comment]
cleaning libvirtd logs...
DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_attach_with_minimal_xml

**Review by nanli1 — APPROVED** [review]

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
