### PR TITLE
Add adaption to support different huge page size for multi arch

### PR DESCRIPTION
**Pull request by liang-cong-red-hat**
Test results on multi arch:
x86_64:
(1/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.2M: PASS (33.56 s)
 (2/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.2M: PASS (7.83 s)
 (3/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.2M: PASS (47.99 s)
 (4/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.2M: PASS (7.88 s)

aarch64 4k:
(1/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.2M: PASS (41.69 s)
 (2/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.512M: CANCEL: Expected host default huge page size is 524288 KiB, but get 2048 (7.02 s)
 (3/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.2M: PASS (7.40 s)
 (4/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.512M: CANCEL: Expected host default huge page size is 524288 KiB, but get 2048 (7.08 s)
 (5/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.2M: PASS (39.22 s)
 (6/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.512M: CANCEL: Expected host default huge page size is 524288 KiB, but get 2048 (7.08 s)
 (7/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.2M: PASS (7.68 s)
 (8/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.512M: CANCEL: Expected host default huge page size is 524288 KiB, but get 2048 (7.06 s)

aarch64 64k:
 (1/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.2M: CANCEL: Expected host default huge page size is 2048 KiB, but get 524288 (4.98 s)
 (2/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.512M: PASS (29.92 s)
 (3/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.2M: CANCEL: Expected host default huge page size is 2048 KiB, but get 524288 (5.46 s)
 (4/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.512M: PASS (5.70 s)
 (5/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.2M: CANCEL: Expected host default huge page size is 2048 KiB, but get 524288 (5.54 s)
 (6/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.512M: PASS (30.16 s)
 (7/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.2M: CANCEL: Expected host default huge page size is 2048 KiB, but get 524288 (5.52 s)
 (8/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.512M: PASS (5.56 s)

### CODE REVIEW

**Comment by liang-cong-red-hat** [comment]
new test results:
x86_64:
(1/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.4k.2048: PASS (45.60 s)
 (2/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.4k.2048: PASS (7.87 s)
 (3/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.4k.2048: PASS (48.24 s)
 (4/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.4k.2048: PASS (7.87 s)

aarch64 64k:
 (1/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.4k.2048: CANCEL: Expected host default page size is 4 KiB, but get 64.0 KiB (5.00 s)
 (2/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.64k.524288: PASS (30.85 s)
 (3/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.4k.2048: CANCEL: Expected host default page size is 4 KiB, but get 64.0 KiB (5.72 s)
 (4/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.64k.524288: PASS (5.77 s)
 (5/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.4k.2048: CANCEL: Expected host default page size is 4 KiB, but get 64.0 KiB (5.54 s)
 (6/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.64k.524288: PASS (31.03 s)
 (7/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.4k.2048: CANCEL: Expected host default page size is 4 KiB, but get 64.0 KiB (5.70 s)
 (8/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.64k.524288:PASS (5.75 s)

**Review by nanli1 — APPROVED** [review]

**Comment by nanli1** [comment]
@dzhengfy Could you review  this pr

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
@liang-cong-red-hat resolve conflicts, please

**Comment by liang-cong-red-hat** [comment]
> @liang-cong-red-hat resolve conflicts, please

done

**Pull request merged**
