### PR TITLE
add 3 cases for multi-kernel test of v2v

### PR DESCRIPTION
**Pull request by chloerh**

### CODE REVIEW

**Comment by will-Do** [comment]
Before reviewing your code, I would like to ask you clean your commits. Google the tips if don't understand how to write a git commit message. Such as: http://chris.beams.io/posts/git-commit/

**Comment by chloerh** [comment]
squash into 1 commit, please review

**Comment by chloerh** [comment]
removed unnecessary commits, please review

**Comment by will-Do** [comment]
As second commit is a bit large, I suggest you split it into a new PR. Before touch that one, let's review the first one in this PR.

**Pull request closed without merging**
