### PR TITLE
nodeinfo: Fix a typo

### PR DESCRIPTION
**Pull request by waynesun09**
s/topolopy/topology/g

Signed-off-by: Wayne Sun <gsun@redhat.com>

### CODE REVIEW

**Comment by waynesun09** [comment]
This depends on:
https://github.com/autotest/virt-test/pull/2021

**Comment by yumingfei** [comment]
Nice catch. Can you solve the travis failure?

**Comment by waynesun09** [comment]
@yumingfei  rebase done, travis failure solved

**Comment by will-Do** [comment]
Merge this PR

**Pull request merged**
