### PR TITLE
v2v: fix several script issues for modular v2v in rhel9

### PR DESCRIPTION
**Pull request by xiaodwan**
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

# Format of PR title < sub-system: summary >
e.g
*virsh_migrate: Fix unsupported direct socket mode issue*

# Check lists by category
## If the PR is new cases
- [ ] Description of the cases
- [ ] Links of libvirt features, libvirt bugs or case IDs
- [ ] Test results

## If the PR is bug cases
- [ ] Bug descriptions or bug links
- [ ] Test results

## If the PR is a trivial fix
It it is the fix of typos, comments or documents, the description of PR could be skipped.

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.copy_on_read.esx_70.rhev.rhv_upload.it_vddk.vpx_uri: PASS (734.66 s)
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.log_size_decrease.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (817.64 s)

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.v2v_options.negative_test.invaild_null_option.of.input_mode.libvirt.kvm.default.output_mode.none: PASS (68.59 s)
(1/1) type_specific.io-github-autotest-libvirt.v2v_options.positive_test.format_convert.input_mode.libvirtxml.qcow2_raw.output_mode.rhev: PASS (530.54 s)
(1/1) type_specific.io-github-autotest-libvirt.v2v_options.positive_test.format_convert.input_mode.libvirtxml.raw_qcow2.output_mode.rhev: PASS (697.79 s)
 (1/1) type_specific.io-github-autotest-libvirt.v2v_options.positive_test.print_source.input_mode.libvirt.esx.esx_67.default.output_mode.none: PASS (9.36 s)
  (1/1) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.no_space.host.default.esx.esx_65.output_mode.rhev.rhv_upload.it_vddk: PASS (346.95 s)

**Comment by xiaodwan** [comment]
@chunfuwen @yantian0 Please help to review this PR, thanks.

**Review by yantian0 — APPROVED** [review]

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
