### PR TITLE
Add some negative tests for virsh domif-getlink/setlink.

### PR DESCRIPTION
**Pull request by liuzzfnst**

### CODE REVIEW

**Comment by liuzzfnst** [comment]
The test result on libvirt-1.2.13 fc20.x86_64

\# ./run -t libvirt --no-downloads -k --tests virsh.domif_setlink_getlink
SETUP: PASS (0.20 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /root/autotest/client/tests/virt/logs/run-2015-07-07-11.49.44/debug.log
TESTS: 25
(1/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_net.no_config.domain_name.running_guest.domif_setlink.setlink_up: PASS (49.01 s)
(2/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_net.no_config.domain_name.running_guest.domif_setlink.setlink_down: PASS (44.42 s)
(3/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_net.no_config.domain_ID.running_guest.domif_setlink.setlink_up: PASS (42.06 s)
(4/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_up: PASS (44.48 s)
(5/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_down: PASS (33.65 s)
(6/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_mac.no_config.domain_name.shutoff_guest.domif_setlink.setlink_up: PASS (53.53 s)
(7/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_mac.no_config.domain_name.shutoff_guest.domif_setlink.setlink_down: PASS (43.04 s)
(8/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_mac.no_config.domain_UUID.shutoff_guest.domif_setlink.setlink_up: PASS (42.78 s)
(9/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_mac.with_config.domain_name.running_guest.domif_setlink.setlink_up: PASS (62.13 s)
(10/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.interface_mac.with_config.domain_name.running_guest.domif_setlink.setlink_down: PASS (55.13 s)
(11/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.multi_functional_test.check_update_device: PASS (34.04 s)
(12/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.multi_functional_test.check_options_config: PASS (61.65 s)
(13/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.running_guest_invalid_option: PASS (42.14 s)
(14/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.shutoff_guest_with_vnet: PASS (34.62 s)
(15/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.config_option_with_vnet: PASS (51.29 s)
(16/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_exist_device.with_config_option.no_exist_interface_net: PASS (60.18 s)
(17/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_exist_device.with_config_option.no_exist_interface_mac: PASS (62.27 s)
(18/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_exist_device.without_config_option.no_exist_interface_net: PASS (46.47 s)
(19/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_exist_device.without_config_option.no_exist_interface_mac: PASS (43.61 s)
(20/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.error_operation: PASS (44.54 s)
(21/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_operation: PASS (44.47 s)
(22/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_device: PASS (34.13 s)
(23/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_match_domain_uuid: PASS (38.25 s)
(24/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.no_match_domain_name: PASS (38.66 s)
(25/25) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.negative_test.without_domain_param: PASS (37.49 s)
TOTAL TIME: 1144.33 s (19:04)
TESTS PASSED: 25
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by waynesun09** [comment]
ACK, pls rebase this PR to resolve conflict, thx.

**Comment by Chenditang** [comment]
@waynesun09 
Updated, thanks~~

**Comment by PandaWei** [comment]
Please clean up your branch and pay more attention to it next time.

**Comment by Chenditang** [comment]
@waynesun09 @PandaWei 
Updated, thanks~~

**Comment by will-Do** [comment]
@Chenditang Has conflicts

**Comment by Chenditang** [comment]
@will-Do 
Sorry for my fault, I think the conflict is resolved now.

**Comment by Chenditang** [comment]
@will-Do @waynesun09 
The conflict has been resolved ~

**Comment by will-Do** [comment]
@Chenditang 
Not really

**Comment by waynesun09** [comment]
no conflict and test is fine, merge this now, thx.

**Pull request merged**
