### PR TITLE
virtual_network/element_model: don't check pci model on s390x

### PR DESCRIPTION
**Pull request by smitterl**
On s390x, interfaces are not PCI devices per default. Don't check the pci model.

### CODE REVIEW

**Comment by smitterl** [comment]
```
JOB ID     : 26ab55306d54697c0ef6c279269e00a3d7f98548
JOB LOG    : /var/lib/avocado/job-results/job-2023-12-04T13.17-26ab553/job.log
 (1/2) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.virtio: PASS (25.11 s)
 (2/2) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.test: PASS (6.19 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-12-04T13.17-26ab553/results.html
JOB TIME   : 31.81 s
```

**Comment by smitterl** [comment]
@chloerh Please help review.

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by cliping — APPROVED** [review]
LGTM

**Pull request merged**
