### PR TITLE
v2v: add new case for 41 disks of VM

### PR DESCRIPTION
**Pull request by xiaodwan**
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/3522

**Comment by xiaodwan** [comment]
```
JOB ID     : 62bb6bd39729d950f1f0af07de70309943786606
JOB LOG    : /root/avocado/job-results/job-2022-09-14T08.54-62bb6bd/job.log
 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.vddk_errors_41_disks.esx_70.rhev.rhv_upload.it_vddk.vpx_uri: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.vddk_errors_41_disks.esx_70.rhev.rhv_upload.it_vddk.vpx_uri: PASS (422.44 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 424.35 s
```

**Comment by xiaodwan** [comment]
@chunfuwen @tianyan0 please help to review this PR, thanks.

**Review by yantian0 — APPROVED** [review]

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
