### PR TITLE
connectivity_check/ethernet: Select host interface

### PR DESCRIPTION
**Pull request by smitterl**
Get IP from configured host interface.
This is important if more than one interface are available.

### CODE REVIEW

**Comment by smitterl** [comment]
```
JOB ID     : c7d9aefe4ae4726911ffdb13a23bc313f4937303
JOB LOG    : /var/lib/avocado/job-results/job-2023-12-05T04.12-c7d9aef/job.log
 (1/7) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.no_mtu.non_root_user: PASS (49.78 s)
 (2/7) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.larger_mtu.non_root_user: PASS (51.75 s)
 (3/7) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.smaller_mtu.non_root_user: PASS (51.66 s)
 (4/7) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.macvtap.no_mtu.non_root_user: PASS (35.84 s)
 (5/7) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.negative_test.no_target_dev.non_root_user: PASS (11.43 s)
 (6/7) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.negative_test.target_dev_not_exist.non_root_user: PASS (11.50 s)
 (7/7) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.negative_test.managed_yes.non_root_user: PASS (28.06 s)
RESULTS    : PASS 7 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-12-05T04.12-c7d9aef/results.html
JOB TIME   : 240.61 s
```

**Comment by smitterl** [comment]
@chloerh please help review

**Review by cliping — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
