### PR TITLE
Increase memory size to fix vm crash some time

### PR DESCRIPTION
**Pull request by jinqi7**
Signed-off-by: qijing <jinqi@redhat.com>

Increase memory size for the vm in case vm crash some time

### CODE REVIEW

**Comment by jinqi7** [comment]
Before the patch -
avocado run --vt-type libvirt memory_discard.common.numa_cell.discard_no
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 975ea9c218277a0e2a43d8320195a672e78a6558
JOB LOG    : /root/avocado/job-results/job-2021-05-27T05.47-975ea9c/job.log
 (1/1) type_specific.io-github-autotest-libvirt.memory_discard.common.numa_cell.discard_no: ERROR: No ipv4 DHCP lease for MAC 52:54:00:4c:d0:77 (261.75 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 262.47 s
With the patch -
# avocado run --vt-type libvirt memory_discard.common.mem_dev.discard_no
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : bc668881612b167ef360c3b3b6e93c86e69ff9e1
JOB LOG    : /root/avocado/job-results/job-2021-05-30T23.28-bc66888/job.log
 (1/1) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.discard_no: PASS (83.67 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 85.20 s

**Comment by jinqi7** [comment]
avocado run --vt-type libvirt memory_discard.common.mem_dev.discard_yes
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : b04f3de37ae807f3c4fef174e8545d7197d9bddd
JOB LOG    : /root/avocado/job-results/job-2021-05-30T23.33-b04f3de/job.log
 (1/1) type_specific.io-github-autotest-libvirt.memory_discard.common.mem_dev.discard_yes: PASS (87.65 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

**Review by chunfuwen — APPROVED** [review]
lgtm

**Comment by chunfuwen** [comment]
only two lines change, mark it as minor_fix

**Pull request merged**
