### PR TITLE
migrate_vm: Add a case for disks-port option

### PR DESCRIPTION
**Pull request by dzhengfy**
Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
This depends on pr https://github.com/avocado-framework/avocado-vt/pull/645

**Comment by dzhengfy** [comment]
# avocado run --vt-type libvirt virsh.migrate.there_timeout_suspend
JOB ID     : a6843613852ba85ebdd3b283a490a038b402c59f
JOB LOG    : /root/avocado/job-results/job-2016-08-12T18.50-a684361/job.log
TESTS      : 1
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate.there_timeout_suspend: PASS (240.41 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /root/avocado/job-results/job-2016-08-12T18.50-a684361/html/results.html
TESTS TIME : 240.41 s

**Comment by dzhengfy** [comment]
# avocado run --vt-type libvirt virsh.migrate_vm.positive_testing.live_storage_migration.disk_ports
JOB ID     : fd2731fb7603d317a33a5bd3e509c4aa64a6fe20
JOB LOG    : /root/avocado/job-results/job-2016-08-11T15.40-fd2731f/job.log
TESTS      : 1
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration.disk_ports: PASS (281.24 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /root/avocado/job-results/job-2016-08-11T15.40-fd2731f/html/results.html
TESTS TIME : 281.24 s

**Comment by dzhengfy** [comment]
@kylazhang @waynesun09 , could you help review?

**Comment by waynesun09** [comment]
ACK

**Pull request merged**
