### PR TITLE
Set controller for ppc test to support hotplug/unplug

### PR DESCRIPTION
**Pull request by chloerh**
Replace old scsi controller with virtio-scsi controller to support
hotplug/unplug

Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

### CODE REVIEW

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by dzhengfy** [comment]
Could you give the test result on PPC? @chloerh

**Comment by chloerh** [comment]
Before
FAIL 1-type_specific.io-github-autotest-libvirt.svirt_attach_disk.positive_test.default_vol.disk_seclabel.disk_label_svirt_image_s0.sec_relabel_yes.sec_type_static -> TestFail: error: Failed to detach device from /tmp/xml_utils_temp_en7qjuc0.xml
error: internal error: unable to execute QEMU command 'device_del': Bus 'scsi0.0' does not support hotplugging

After
PASS 1-type_specific.io-github-autotest-libvirt.svirt_attach_disk.positive_test.default_vol.disk_seclabel.disk_label_svirt_image_s0.sec_relabel_yes.sec_type_static

**Comment by dzhengfy** [comment]
only impact PPC.

**Review by dzhengfy — APPROVED** [review]
lgtm

**Pull request merged**
