### PR TITLE
Update the command line of cache_mode

### PR DESCRIPTION
**Pull request by iccaszhulili**
Bug RHEL-50329 had been fixed, we should update script accordingly.

### CODE REVIEW

**Comment by iccaszhulili** [comment]
\# avocado run --vt-type libvirt filesystem_device..cache_mode_none                                                                  
JOB ID     : eaaefda9a07daabe6e8d13784add34dfe8083578                                                                                                                                         
JOB LOG    : /var/log/avocado/job-results/job-2024-08-14T21.30-eaaefda/job.log  
...
RESULTS    : PASS 18 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0                                                                                                            
JOB HTML   : /var/log/avocado/job-results/job-2024-08-14T21.30-eaaefda/results.html                                                                                                           
JOB TIME   : 854.24 s  

\# avocado run --vt-type libvirt filesystem_device..cache_mode_always                                                                             
JOB ID     : f0fb8f6ef0c7684dbe7950a630330f5cb3c2141d                                                                                                                                         
JOB LOG    : /var/log/avocado/job-results/job-2024-08-14T21.45-f0fb8f6/job.log
...
RESULTS    : PASS 18 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-08-14T21.45-f0fb8f6/results.html
JOB TIME   : 840.37 s

**Review by nanli1 — APPROVED** [review]

**Comment by iccaszhulili** [comment]
@dzhengfy @smitterl Please help to review. Thanks very much

**Review by smitterl — APPROVED** [review]
I already submitted this https://github.com/autotest/tp-libvirt/pull/5840 but I like your solution better.

**Review by chunfuwen — APPROVED** [review]
lgtm

**Pull request merged**
