### PR TITLE
virtual_disks_relative_blockcommit.py: Fix block disk issue in snapshot

### PR DESCRIPTION
**Pull request by meinaLi**
Fix the permission denied in inappropriate path and the block disk issue in snapshot

Signed-off-by: Meina Li <meili@redhat.com>

### CODE REVIEW

**Comment by meinaLi** [comment]
```
# avocado run --vt-type libvirt --vt-machine-type q35 virtual_disks.relativepath.blockcommit.normal_test.network_disk.iscsi virtual_disks.relativepath.blockcommit.normal_test.block_disk.relative_path.active_domain.shallow.top_active
JOB ID     : 67f5d81818f8d6910f5eab7ed9c6ce3e56d00929
JOB LOG    : /root/avocado/job-results/job-2022-02-09T04.15-67f5d81/job.log
 (1/5) type_specific.io-github-autotest-libvirt.virtual_disks.relativepath.blockcommit.normal_test.network_disk.iscsi.relative_path.active_domain.base.top_inactive: PASS (91.86 s)
 (2/5) type_specific.io-github-autotest-libvirt.virtual_disks.relativepath.blockcommit.normal_test.network_disk.iscsi.relative_path.pause_domain.shallow.top_active: PASS (88.83 s)
 (3/5) type_specific.io-github-autotest-libvirt.virtual_disks.relativepath.blockcommit.normal_test.network_disk.iscsi.relative_path.restart_libvirtd.shallow.top_active: PASS (93.68 s)
 (4/5) type_specific.io-github-autotest-libvirt.virtual_disks.relativepath.blockcommit.normal_test.network_disk.iscsi.relative_path.validate_delete_option.shallow.top_active: PASS (154.94 s)
 (5/5) type_specific.io-github-autotest-libvirt.virtual_disks.relativepath.blockcommit.normal_test.block_disk.relative_path.active_domain.shallow.top_active: PASS (135.00 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 565.38 s
```

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
@meinaLi , could you help run one more case to double check whether the change impact other cases

**Comment by chunfuwen** [comment]
it depends on https://github.com/avocado-framework/avocado-vt/pull/3345

**Review by kylazhang — APPROVED** [review]

**Pull request merged**
