### PR TITLE
migration: Add case about migrateuri and disks-port

### PR DESCRIPTION
**Pull request by cliping**
XXX-297867 - VM live migration with copy storage - network data transport - TCP - --migrateuri & --disks-port

### CODE REVIEW

**Comment by cliping** [comment]
Depend on: https://github.com/avocado-framework/avocado-vt/pull/3819

**Comment by cliping** [comment]
Test result:
Due to a bug, some cases fail.

 (1/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr_and_port.default_port.copy_storage_all.p2p: PASS (197.53 s)
 (2/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr_and_port.default_port.copy_storage_all.non_p2p: PASS (195.65 s)
 (3/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr_and_port.valid_port.copy_storage_all.p2p: PASS (206.84 s)
 (4/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr_and_port.valid_port.copy_storage_all.non_p2p: ERROR: Unable to find event block-job (764.57 s)

 (1/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv6_addr_and_port.default_port.copy_storage_all.p2p: PASS (196.18 s)
 (2/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv6_addr_and_port.default_port.copy_storage_all.non_p2p: PASS (199.38 s)
 (3/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv6_addr_and_port.valid_port.copy_storage_all.p2p: PASS (207.56 s)
 (4/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv6_addr_and_port.valid_port.copy_storage_all.non_p2p: FAIL: error: internal error: Failed to reserve port 49870 (218.41 s)

 (1/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr.default_port.copy_storage_all.p2p: PASS (186.62 s)
 (2/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr.default_port.copy_storage_all.non_p2p: PASS (185.03 s)
 (3/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr.valid_port.copy_storage_all.p2p: PASS (196.68 s)
 (4/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.migrateuri.ipv4_addr.valid_port.copy_storage_all.non_p2p: FAIL: error: internal error: Failed to reserve port 49880 (207.36 s)

 (1/2) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.invalid_migrateuri.copy_storage_all.p2p: PASS (279.08 s)
 (2/2) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.invalid_migrateuri.copy_storage_all.non_p2p: PASS (278.41 s)

 (1/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.invalid_disks_port.no_permission_port.copy_storage_all.p2p: PASS (136.75 s)
 (2/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.invalid_disks_port.no_permission_port.copy_storage_all.non_p2p: PASS (137.17 s)
 (3/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.invalid_disks_port.libvirt_reserved_port.copy_storage_all.p2p: PASS (137.69 s)
 (4/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_migrateuri_and_disks_port.invalid_disks_port.libvirt_reserved_port.copy_storage_all.non_p2p: PASS (136.84 s)

**Review by Yingshun — APPROVED** [review]
LGTM

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
