### PR TITLE
Support convert vm from xen and esx

### PR DESCRIPTION
**Pull request by xiaodwan**
Add support for converting vm from xen and esx to rhv

Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.scsi_disk.xen.output_mode.rhev: PASS (484.50 s)
 (2/3) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.noyumrepo-rhn.esx.esx_67.output_mode.rhev: PASS (2095.95 s)
 (3/3) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.kdump.esx.esx_67.output_mode.rhev: PASS (2753.51 s)

**Comment by xiaodwan** [comment]
@chunfuwen @chloerh please help to review this pr, thanks.

**Comment by chloerh** [comment]
We do have other files which already support converting vm from xen or esx. If we need to implement cases of converting vm from esx or xen, we could edit those 2 files instead of this one which is designed to support kvm only

**Comment by xiaodwan** [comment]
@chloerh yes, i thought about that.  Because most guests in specific_kvm are not original, some configuration files have been changed, i want to distinguish those special guest cases from other normal guests cases in convert_from_xen/esx, and the priority is lower than the normal guests, if we keep them in a separated file, it's easier to run jobs in ci because we can avoid to add some filter rules to select the cases.
And kvm to rhv is not a valid scenarios any more, still keep the file to only support kvm guests is not a good idea. In addition, i consider to rename special_kvm* files to special_guests* to make the make the meaning of the files more clearly.

**Comment by chloerh** [comment]
@xiaodwan I see. Then we could create a new file which is about all hypervisors: kvm, xen, esx, and leave the kvm file the way it is.  And we could add non-hypervisor-related function cases to this file.
I mean we should try to avoid mixing things up.

**Comment by xiaodwan** [comment]
@chloerh i still cannot understand why we should keep specific_kvm* files as it is. Most cases are invalid, why we keep some invalid cases for upstream?  
The reason i decide to change the original specific file is that some codes still can be reused, it can save lots of time.

**Comment by chloerh** [comment]
@xiaodwan Then it's up to you, I'm only suggesting.

**Comment by xiaodwan** [comment]
(01/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.virtioscsi_disk.xen.output_mode.rhev: PASS (475.60 s)
 (02/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.sata_disk.esx.esx_65.output_mode.rhev: FAIL: virt-v2v: libguestfs 1.38.4rhel=8,release=10.module+el8+2709+40ed2f2c,libvirt (x86_64)\nlibvirt version: 4.5.0\nlibguestfs: trace: set_verbose true\nlibguestfs: trace: set_verbose = 0\nlibguestfs: trace: get_backend\nlibguestfs: trace: get_backend = "direct"\ni... (13.41 s)
 (03/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.multi_disks.linux.esx.esx_67.output_mode.rhev: PASS (2091.48 s)
 (04/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.noyumrepo-rhn.esx.esx_67.output_mode.rhev: PASS (2050.98 s)
 (05/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.kdump.esx.esx_67.output_mode.rhev: PASS (2728.15 s)
 (06/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.floppy.kvm.output_mode.rhev: PASS (1077.81 s)
 (07/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.floppy_devmap.kvm.output_mode.rhev: PASS (1319.65 s)
 (08/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.fstab.cdrom.esx.esx_65.output_mode.rhev: PASS (1956.57 s)
 (09/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.fstab.label.esx.esx_65.output_mode.rhev: PASS (1874.18 s)
 (10/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.fstab.uuid.esx.esx_65.output_mode.rhev: PASS (1934.99 s)
 (11/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.corrupt_rpmdb.kvm.output_mode.rhev: PASS (1349.74 s)
 (12/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.bogus_kernel.esx.esx_67.output_mode.rhev: PASS (1983.55 s)
 (13/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.network.multi_netcards.esx.esx_67.output_mode.rhev: PASS (2071.22 s)
 (14/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.network.rtl8139.xen.output_mode.rhev: PASS (706.50 s)
 (15/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.windows.network.network.e1000.esx.esx_65.output_mode.rhev: PASS (1871.68 s)
 (16/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.network.only_net.kvm.output_mode.rhev: PASS (1079.99 s)
 (17/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.network.only_br.kvm.output_mode.rhev: PASS (1095.23 s)
 (18/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.display.spice.kvm.output_mode.rhev: PASS (1110.73 s)
 (19/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.display.spice_encrypt.kvm.output_mode.rhev: PASS (1081.38 s)
 (20/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.selinux.host_enable.kvm.output_mode.rhev: PASS (1079.86 s)
 (21/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.selinux.vm_enable.kvm.output_mode.rhev: PASS (1336.72 s)
 (22/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.selinux.vm_disable.kvm.output_mode.rhev: PASS (1320.32 s)
 (23/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.firewalld.host_start.kvm.output_mode.rhev: PASS (1086.60 s)
 (24/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.firewalld.host_stop.kvm.output_mode.rhev: PASS (1076.28 s)
 (25/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.firewalld.guest_status.kvm.output_mode.rhev: PASS (1386.22 s)
 (26/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.remove_securetty.kvm.output_mode.rhev: PASS (1333.78 s)
 (27/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.blank_2nd_disk.kvm.output_mode.rhev: PASS (1258.91 s)
 (28/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.time.ntpd_on.kvm.output_mode.rhev: PASS (1369.84 s)
 (29/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.time.sync_ntp.kvm.output_mode.rhev: PASS (1575.98 s)
 (31/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.no_libguestfs_backend.esx.esx_67.output_mode.rhev: PASS (2084.95 s)
 (32/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.file_image.kvm.output_mode.rhev: PASS (1078.64 s)
 (33/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.to_libvirt.display.mix.qxl.spice.kvm.output_mode.libvirt: PASS (726.48 s)
 (34/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.to_libvirt.display.mix.qxl.vnc.kvm.output_mode.libvirt: PASS (766.44 s)
 (35/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.to_libvirt.display.mix.cirrus.spice.kvm.output_mode.libvirt: PASS (724.37 s)
 (36/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.to_libvirt.display.mix.cirrus.vnc.kvm.output_mode.libvirt: PASS (716.53 s)
 (37/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.to_libvirt.display.listen.type_none.kvm.output_mode.libvirt: PASS (779.93 s)
 (38/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.to_libvirt.display.listen.type_socket.kvm.output_mode.libvirt: PASS (791.74 s)
 (39/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.to_libvirt.mem_alloc.kvm.output_mode.libvirt: PASS (944.19 s)
 (40/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.not_shutdown.running.default.kvm.output_mode.local: PASS (27.04 s)
 (41/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.not_shutdown.paused.default.kvm.output_mode.local: PASS (28.75 s)
 (42/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.serial_terminal.default.esx.esx_65.output_mode.rhev: PASS (250.38 s)
 (43/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.no_space.guest.default.esx.esx_65.output_mode.rhev: ERROR: VM 'esx6.5-rhel7.6-no-space' failed to start: error: failed to get domain 'esx6.5-rhel7.6-no-space'\nerror: Domain not found: no domain with matching name 'esx6.5-rhel7.6-no-space' (11.36 s)
 (44/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.no_space.host.default.esx.esx_65.output_mode.rhev: PASS (1714.57 s)
 (45/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.unclean_file_system.unclean_fs.kvm.output_mode.rhev: PASS (18.98 s)
 (46/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.fstab_invalid.fstab.invalid.esx.esx_67.output_mode.rhev: PASS (58.85 s)

**Comment by xiaodwan** [comment]
This case has a bug, so it cannot pass now.
02/46) type_specific.io-github-autotest-libvirt.specific_kvm.positive_test.linux.sata_disk.esx.esx_65.output_mode.rhev: FAIL: virt-v2v: libguestfs 1.38.4rhel=8,release=10.module+el8+2709+40ed2f2c,libvirt (x86_64)\nlibvirt version: 4.5.0\nlibguestfs: trace: set_verbose true\nlibguestfs: trace: set_verbose = 0\nlibguestfs: trace: get_backend\nlibguestfs: trace: get_backend = "direct"\ni... (13.41 s)

**Comment by xiaodwan** [comment]
This case it may have a bug in v2v, i'm sure it's not a script problem.
(43/46) type_specific.io-github-autotest-libvirt.specific_kvm.negative_test.no_space.guest.default.esx.esx_65.output_mode.rhev: ERROR: VM 'esx6.5-rhel7.6-no-space' failed to start: error: failed to get domain 'esx6.5-rhel7.6-no-space'\nerror: Domain not found: no domain with matching name 'esx6.5-rhel7.6-no-space' (11.36 s)

**Comment by xiaodwan** [comment]
@chloerh @chunfuwen please help to re-review this patch. I updated some logic errors in previous version and ran all cases to verify my changing.  And fixed some errors.

**Pull request merged**
