### PR TITLE
modify vol-resize test for incorrect usage of per_pool

### PR DESCRIPTION
**Pull request by kylazhang**
modify vol-resize test for incorrect usage of per_pool

### CODE REVIEW

**Comment by kylazhang** [comment]
@will-Do please help to review and push it as you are more familiar with it.

**Comment by will-Do** [comment]
This fix already included in https://github.com/autotest/tp-libvirt/pull/477/files

**Comment by rbian** [comment]
@kylazhang ， Please close this PR, since it has already fixed.

**Comment by kylazhang** [comment]
@rbian, ok, thanks

**Pull request closed without merging**
