### PR TITLE
acpi is not supported by pseries

### PR DESCRIPTION
**Pull request by chloerh**
Signed-off-by: haizhao <haizhao@redhat.com>

### CODE REVIEW

**Comment by chloerh** [comment]
Requires @dzhengfy 's review

**Comment by chloerh** [comment]
@chunfuwen , Could you revert this?  I have stated that this pr needs @dzhengfy 's review/confirmation. I guess you missed it.

**Comment by dzhengfy** [comment]
@chloerh @chunfuwen , I agree this change because the script is to looking for a cpu feature 'acpi' under   <feature> element in the guest xml, but no <feature> element is supported on PPC.

**Comment by dzhengfy** [comment]
I closed the revert PR 2860.

**Pull request merged**
