### PR TITLE
Add new cases about v2v --key option

### PR DESCRIPTION
**Pull request by xiaodwan**
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.keys.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (1724.16 s)

**Comment by xiaodwan** [comment]
(1/2) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.keys.invalid.pwd.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (42.09 s)
 (2/2) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.keys.invalid.pwd_file.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (40.50 s)

**Comment by chloerh** [comment]
Conflicting

**Comment by xiaodwan** [comment]
> Conflicting

Done
@chloerh @yantian0 Please help to review this PR, thanks.

**Review by yantian0 — APPROVED** [review]

**Review by chloerh — APPROVED** [review]

**Pull request merged**
