### PR TITLE
virsh_create: fix undefine with nvram

### PR DESCRIPTION
**Pull request by dzhengfy**
Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Review by cliping — APPROVED** [review]
LGTM

**Comment by cliping** [comment]
Please upload test result, thanks.

**Review by chunfuwen — APPROVED** [review]
it is known solution.
LGTM

**Comment by dzhengfy** [comment]
libvirt-8.4.0-3.el9.x86_64
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.create,virsh.autostart,virsh.desc --vt-connect-uri qemu:///system
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : b03ad9352a79ef24cf26e79dacaeeba87de778c1
JOB LOG    : /var/lib/avocado/job-results/job-2022-06-27T19.46-b03ad93/job.log
 (01/40) type_specific.io-github-autotest-libvirt.virsh.create.none: PASS (8.26 s)
 (02/40) type_specific.io-github-autotest-libvirt.virsh.create.dot_name: PASS (8.59 s)
 (03/40) type_specific.io-github-autotest-libvirt.virsh.create.console: PASS (37.25 s)
 (04/40) type_specific.io-github-autotest-libvirt.virsh.create.console_autodestroy: PASS (38.65 s)
 (05/40) type_specific.io-github-autotest-libvirt.virsh.create.console_paused: PASS (38.09 s)
 (06/40) type_specific.io-github-autotest-libvirt.virsh.create.console_autodestroy_paused: PASS (33.73 s)
 (07/40) type_specific.io-github-autotest-libvirt.virsh.create.autodestroy: PASS (10.46 s)
 (08/40) type_specific.io-github-autotest-libvirt.virsh.create.autodestroy_paused: PASS (10.69 s)
 (09/40) type_specific.io-github-autotest-libvirt.virsh.create.paused: PASS (24.84 s)
 (10/40) type_specific.io-github-autotest-libvirt.virsh.create.negtive_readonly: PASS (7.61 s)
 (11/40) type_specific.io-github-autotest-libvirt.virsh.create.negative_validate: PASS (7.68 s)
 (12/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.no_option: PASS (28.06 s)
 (13/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.domain_ID_no_option: PASS (11.22 s)
 (14/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.domain_UUID_no_option: PASS (29.89 s)
 (15/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.title_option: PASS (23.94 s)
 (16/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.live_desc: PASS (24.06 s)
 (17/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.current_desc: PASS (23.91 s)
 (18/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.config_desc: PASS (54.53 s)
 (19/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.live_config_desc: PASS (30.79 s)
 (20/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.live_title: PASS (23.93 s)
 (21/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.current_title: PASS (29.99 s)
 (22/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.config_title: PASS (50.66 s)
 (23/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.live_config_title: PASS (24.59 s)
 (24/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.edit_option: PASS (25.29 s)
 (25/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.new_desc_option: PASS (29.99 s)
 (26/40) type_specific.io-github-autotest-libvirt.virsh.desc.positive_test.transient_live: PASS (9.04 s)
 (27/40) type_specific.io-github-autotest-libvirt.virsh.desc.negative_test.invalid_domain_name: PASS (29.82 s)
 (28/40) type_specific.io-github-autotest-libvirt.virsh.desc.negative_test.invalid_domain_uuid: PASS (32.76 s)
 (29/40) type_specific.io-github-autotest-libvirt.virsh.desc.negative_test.invalid_option1: PASS (24.91 s)
 (30/40) type_specific.io-github-autotest-libvirt.virsh.desc.negative_test.invalid_option2: PASS (23.94 s)
 (31/40) type_specific.io-github-autotest-libvirt.virsh.desc.negative_test.invalid_option3: PASS (23.93 s)
 (32/40) type_specific.io-github-autotest-libvirt.virsh.desc.negative_test.new_desc_without_string: PASS (23.44 s)
 (33/40) type_specific.io-github-autotest-libvirt.virsh.desc.negative_test.transient_config: PASS (8.98 s)
 (34/40) type_specific.io-github-autotest-libvirt.virsh.autostart.positive_test.set_autostart: PASS (55.35 s)
 (35/40) type_specific.io-github-autotest-libvirt.virsh.autostart.positive_test.set_disable: PASS (24.01 s)
 (36/40) type_specific.io-github-autotest-libvirt.virsh.autostart.negative_test.invalid_option: PASS (29.86 s)
 (37/40) type_specific.io-github-autotest-libvirt.virsh.autostart.negative_test.transient_autostart: PASS (23.79 s)
 (38/40) type_specific.io-github-autotest-libvirt.virsh.autostart.negative_test.transient_disable: PASS (23.76 s)
 (39/40) type_specific.io-github-autotest-libvirt.virsh.autostart.negative_test.readonly_autostart: PASS (29.85 s)
 (40/40) type_specific.io-github-autotest-libvirt.virsh.autostart.negative_test.readonly_disable: PASS (25.86 s)
RESULTS    : PASS 40 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-06-27T19.46-b03ad93/results.html
JOB TIME   : 1027.92 s
```

**Comment by dzhengfy** [comment]
Test result is updated. Merged.

**Pull request merged**
