### PR TITLE
virtual_network.iface_network: Add tests for macvtap network.

### PR DESCRIPTION
**Pull request by rbian**

### CODE REVIEW

**Comment by rbian** [comment]
Depends on autotest/virt-test#1997

**Comment by will-Do** [comment]
One case failed:
```
(1/1) type_specific.ydu-libvirt.virtual_network.iface_network.net_forward.route_test: FAIL (39.38 s)

15:40:56 ERROR|
15:40:56 ERROR| Traceback (most recent call last):
15:40:56 ERROR|   File "/root/Downloads/virt-test/virttest/standalone_test.py", line 220, in run_once
15:40:56 ERROR|     run_func(self, params, env)
15:40:56 ERROR|   File "/root/Downloads/tp-libvirt/libvirt/tests/src/virtual_network/iface_network.py", line 754, in run
15:40:56 ERROR|     run_ip_test(session, "ipv6")
15:40:56 ERROR|   File "/root/Downloads/tp-libvirt/libvirt/tests/src/virtual_network/iface_network.py", line 411, in run_ip_test
15:40:56 ERROR|     % ip_gateway)
15:40:56 ERROR| TestFail: Failed to ping gateway address: 2001:db8:ca2:6::1
15:40:56 ERROR|
15:40:56 ERROR| FAIL type_specific.ydu-libvirt.virtual_network.iface_network.net_forward.route_test -> TestFail: Failed to ping gateway address: 2001:db8:ca2:6::1

```
And all other cases are passed:
```
(1/1) type_specific.ydu-libvirt.virtual_network.iface_network.dnsmasq_test.net_dhcp_range: PASS (272.88 s)

(1/1) type_specific.ydu-libvirt.virtual_network.iface_network.net_forward.net_route: PASS (38.83 s)

(1/6) type_specific.ydu-libvirt.virtual_network.iface_network.net_macvtap.error_test.start_error: PASS (0.94 s)
(2/6) type_specific.ydu-libvirt.virtual_network.iface_network.net_macvtap.error_test.define_error: PASS (25.37 s)
(3/6) type_specific.ydu-libvirt.virtual_network.iface_network.net_macvtap.net_bridge.default_test: PASS (30.68 s)
(4/6) type_specific.ydu-libvirt.virtual_network.iface_network.net_macvtap.net_bridge.multi_guests: PASS (192.95 s)
(5/6) type_specific.ydu-libvirt.virtual_network.iface_network.net_macvtap.net_passthrough: PASS (31.02 s)
(6/6) type_specific.ydu-libvirt.virtual_network.iface_network.net_macvtap.net_private: PASS (30.78 s)

(1/3) type_specific.ydu-libvirt.virtual_network.iface_network.net_portgroup.default_portgroup: PASS (31.31 s)
(2/3) type_specific.ydu-libvirt.virtual_network.iface_network.net_portgroup.specific_portgroup: PASS (31.06 s)
(3/3) type_specific.ydu-libvirt.virtual_network.iface_network.net_portgroup.overwriting_bandwidth: PASS (31.03 s)

**Comment by will-Do** [comment]
BTW, your patch series also need squashed

**Comment by rbian** [comment]
@will-Do , I have disabled ping for routed network test because its nexthop is unreachable.
It passed my test. Thanks.

**Comment by waynesun09** [comment]
ACK and merge this now, some tests got failed in latest internal ci testing, this pr is for macvtap and mostly working fine in record. Let's track and fix new problems in new PR to aovid this PR grow even bigger.

**Pull request merged**
