### PR TITLE
src: Drop domain_opt and file_opt

### PR DESCRIPTION
**Pull request by qiankehan**
These two arugments are duplicated with the arugments domainarg and
filearg.

Signed-off-by: Han Han <hhan@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
@qiankehan , previous code experiences are good practices with key=value as input parameter
The benefit for these have at least items below :
1)More clear about each parameter meaning(human readable)
2)Even put parameter in wrong order for method, it still can work normally since it is key=value.
Anyway, welcome your thoughts as well.

**Comment by chunfuwen** [comment]
@kylazhang 
@dzhengfy 
@Yingshun 
Please provide your comments.

**Comment by qiankehan** [comment]
@chunfuwen Let me try to explain it more clearly:  
The key problem I tried to fix is that **domain_opt** and **file_opt** of method **attach_device** are dup to **domainarg** and **filearg**. However, direct remove in avocado-vt will cause the case failed at where the codes using the duplicated arguments. So I first update that in tp-libvirt. But I agree that key=value form is more readable.  
BTW, the dup agruments should be remove from **detach_device update_device**, too  
They should be like:
```py
def attach_device(domainarg=None, filearg=None, flagstr=None, **dargs)
```

**Comment by qiankehan** [comment]
@chunfuwen  Any more review?

**Comment by chloerh** [comment]
Code check haven't completed for some reason.

**Comment by qiankehan** [comment]
> Code check haven't completed for some reason.

Passed now

**Pull request merged**
