### PR TITLE
migration: Add case about disks-uri

### PR DESCRIPTION
**Pull request by cliping**
XXX-297892 - VM live migration with copy storage - network data transport - TCP - --disks-uri

### CODE REVIEW

**Comment by cliping** [comment]
Depend on: https://github.com/avocado-framework/avocado-vt/pull/3819

**Comment by cliping** [comment]
Test result:

 (01/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv4_addr_and_port.with_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (185.08 s)
 (02/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv4_addr_and_port.without_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (185.42 s)
 (03/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv6_addr_and_port.with_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (185.82 s)
 (04/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv6_addr_and_port.without_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (187.29 s)
 (05/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.hostname_and_port.with_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (185.29 s)
 (06/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.hostname_and_port.without_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (186.42 s)
 (07/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv4_addr.with_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (185.29 s)
 (08/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv4_addr.without_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (186.54 s)
 (09/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv6_addr.with_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (187.16 s)
 (10/10) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.tcp.ipv6_addr.without_migrateuri_and_listen_addr.copy_storage_all.p2p: PASS (186.19 s)

 (1/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.with_disks_uri_and_disks_port.copy_storage_all.p2p: PASS (135.22 s)
 (2/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.with_disks_uri_and_disks_port.copy_storage_all.non_p2p: PASS (135.37 s)
 (3/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.with_disks_uri_and_disks_port.copy_storage_inc.p2p: PASS (135.11 s)
 (4/4) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.with_disks_uri_and_disks_port.copy_storage_inc.non_p2p: PASS (135.02 s)

 (1/2) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.invalid_disks_uri.invalid_ip_addr.copy_storage_inc.non_p2p: PASS (136.41 s)
 (2/2) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.network_data_transport.tcp_disks_uri.invalid_disks_uri.invalid_hostname.copy_storage_inc.non_p2p: PASS (136.41 s)

**Review by nanli1 — COMMENTED** [review]
Is there only one cfg file pushed?

**Comment by cliping** [comment]
> Is there only one cfg file pushed?

Yes, just one cfg file is needed. Thanks.

**Review by nanli1 — APPROVED** [review]

**Review by dzhengfy — COMMENTED** [review]
LGTM, but please consider my comments in https://github.com/avocado-framework/avocado-vt/pull/3819, thanks.

**Comment by cliping** [comment]
> LGTM, but please consider my comments in [avocado-framework/avocado-vt#3819](https://github.com/avocado-framework/avocado-vt/pull/3819), thanks.

Updated, thanks.

**Review by dzhengfy — APPROVED** [review]

**Pull request merged**
