### PR TITLE
V2V: Resolve uefi guest fail to check device.map

### PR DESCRIPTION
**Pull request by weikunzz**
Modify  "provider/v2v_vmcheck_helper.py" file ,resolve the uefi guest fail to check "device.map" part.

Signed-off-by: Kun Wei kuwei@redhat.com

### CODE REVIEW

**Comment by weikunzz** [comment]
Reopen the request, i thinks it is better, and expect result looks good.

**Comment by balamuruhans** [comment]
Please fix the same in actual commit message.

**Comment by weikunzz** [comment]
@balamuruhans Thanks, i have fix the actual commit message

**Comment by balamuruhans** [comment]
please see commit msg https://github.com/autotest/tp-libvirt/pull/1373/commits/ed6839e4f55c820e3c718c95ff0000627ac881a1, it is better to have git commit description for your fixes and it also doesn't have your `signed-off-by:`

**Comment by chloerh** [comment]
Looks good to me

**Comment by kylazhang** [comment]
@weikunzz Please add signoff in your comment message with "commit -s"

**Pull request merged**
