### PR TITLE
Add openvswitch network tests.

### PR DESCRIPTION
**Pull request by rbian**

### CODE REVIEW

**Comment by rbian** [comment]
Depends on #virt-test/pull/2011

**Comment by will-Do** [comment]
Test all PASS:
```
# ./run -t libvirt --test ydu-libvirt.virtual_network.iface_ovs  -k --keep-image-between-test
SETUP: PASS (0.30 s)
DATA DIR: /root/Downloads/virt-test/shared/data
DEBUG LOG: /root/Downloads/virt-test/logs/run-2015-04-09-16.21.54/debug.log
TESTS: 4
(1/4) type_specific.ydu-libvirt.virtual_network.iface_ovs.net_ovs.default_test: PASS (1.80 s)
(2/4) type_specific.ydu-libvirt.virtual_network.iface_ovs.net_ovs.ovs_portgroup.portgroup_42: PASS (1.72 s)
(3/4) type_specific.ydu-libvirt.virtual_network.iface_ovs.net_ovs.ovs_portgroup.portgroup_4: PASS (1.72 s)
(4/4) type_specific.ydu-libvirt.virtual_network.iface_ovs.net_ovs.ovs_iface: PASS (1.51 s)
TOTAL TIME: 6.79 s
TESTS PASSED: 4
TESTS FAILED: 0
SUCCESS RATE: 100.00 %
```
BTW, pls squash your patches, and we can merge it.

**Comment by rbian** [comment]
Thanks @will-Do, updated the commits.

**Comment by will-Do** [comment]
ACK

**Comment by waynesun09** [comment]
ACK and merging now, thx @rbian @will-Do

**Pull request merged**
