### PR TITLE
blockpull: Add various disk types for testing

### PR DESCRIPTION
**Pull request by waynesun09**
Add network disk with gluster and iscsi type, block disk use iscsi
backend, netfs disk mounted on local for testing.

Also added test case for option --async and --keep-relative.

Signed-off-by: Wayne Sun <gsun@redhat.com>

### CODE REVIEW

**Comment by yumingfei** [comment]
LGTM.
But why not run complete blockpull cases in a single round?

**Comment by waynesun09** [comment]
@yumingfei I also like to collect result in one run, but my machine could fail specific type cases some time and succeed other time (mostly iscsi and gluster related), so I need to split runs and solve all problems, the run result could also be collected from different machines and os.

**Comment by yumingfei** [comment]
OK, I just want to confirm that failed testcases will not effect others.

**Comment by waynesun09** [comment]
@yumingfei the most disturbing problem is gluster bug 1143800 and it did affect the env, which I've solved with commit 789a623. So, it's all good. :)

**Pull request merged**
