### PR TITLE
Treat cfq scheduler error as expected

### PR DESCRIPTION
**Pull request by lento-sun**
cfq scheduler not used in rhel8 anymore, libvirt now giving a
clear error:
"Unable to change blkio parameterserror: Requested operation
is not valid: blkio device weight is valid only for cfq scheduler"
So change the script to treat that error as expected if libvirt
version is later than the fixed-in-version. Detailed info in
bz1658890.

Signed-off-by: Yi Sun <yisun@redhat.com>

### CODE REVIEW

**Comment by lento-sun** [comment]
before fix:
```
(.libvirt-ci-venv-ci-runtest-5qoL79) [root@dell-per730-61 ~]# avocado run --vt-type libvirt virsh.blkiotune.positive.set_blkio_parameter.running_guest.change_device_weights.options.current.maximum_boundary
JOB ID     : bcca7e6939a6cb848b80f2ee8f15dd9e971af2a8
JOB LOG    : /root/avocado/job-results/job-2019-07-15T04.35-bcca7e6/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.set_blkio_parameter.running_guest.change_device_weights.options.current.maximum_boundary: FAIL: error: Unable to change blkio parameters\nerror: Requested operation is not valid: blkio device weight is valid only for cfq scheduler\n (16.55 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 18.46 s
```

after fix:
```
(.libvirt-ci-venv-ci-runtest-5qoL79) [root@dell-per730-61 ~]# avocado run --vt-type libvirt virsh.blkiotune.positive.set_blkio_parameter.running_guest.change_device_weights.options.current.maximum_boundary
JOB ID     : 5fbbfac429d5960547856290ef2fc49b81916d42
JOB LOG    : /root/avocado/job-results/job-2019-07-15T04.41-5fbbfac/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.set_blkio_parameter.running_guest.change_device_weights.options.current.maximum_boundary: PASS (6.19 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 7.81 s
```

**Comment by dzhengfy** [comment]
@lento-sun https://github.com/autotest/tp-libvirt/pull/2349
Above PR fixed same issue with this one. And we think 2349 has a better solution. So please close this one. Thanks.

**Comment by dzhengfy** [comment]
@lento-sun https://github.com/autotest/tp-libvirt/pull/2349
After discussion, we think above PR has better solution for this issue. So we decide to keep 2349. Please help close this one. Thank you.

**Comment by lento-sun** [comment]
@dzhengfy agree, close this one, thx

**Pull request closed without merging**
