### PR TITLE
virsh_net_dhcp_leases: Don't remove the original interfaces

### PR DESCRIPTION
**Pull request by will-Do**
Remove interfaces outside the VM is not enough to update the virtnet
info. Actually, there's no need to remove all the interfaces before
testing , as we will also create a new network for the testing.
And if login VM by IP address failed, we should try serial and run
'dhclient' inside the VM to assign a new IP address for the NIC.

Signed-off-by: Yanbing Du <ydu@redhat.com>

### CODE REVIEW

**Comment by bssrikanth** [comment]
@will-Do I thought removing original interfaces -> hotplugging new interfaces and checking of they get dhcp leases was part of the test case flow. 
So I had fixed the restore/sync part in finally section @ #892 .. Please let me know your thoughts.

**Comment by will-Do** [comment]
@bssrikanth 
Not really, remove the NIC before test start has nothing with this command, the original design is trying to avoid the complexity when check the result.  But as we using a new defined network for testing, the remove step is unnecessary.

**Comment by bssrikanth** [comment]
@will-Do ok. Acked. 

Can you also please fixup issue 2 which I had pointed #892? before hotplugging interface we need to make sure the guest is fully up and running. This can be done by `vm.wait_for_serial_login()`
If you agree I will close #892.

**Comment by will-Do** [comment]
@bssrikanth 
Of course, I think which already in the first patch, line 177. And thanks for your confirm.

**Comment by will-Do** [comment]
Dependent on https://github.com/avocado-framework/avocado-vt/pull/732

**Pull request merged**
