### PR TITLE
Add one case to cover hotplug qcow2 image with opened fdgroup 

### PR DESCRIPTION
**Pull request by chunfuwen**
Add one case to cover hotplug qcow2 image with opened fdgroup by virsh attach-device

Bug 2193315 - Fail to hot-plug a qcow2 image with fdgroup

### CODE REVIEW

**Review by cliping — APPROVED** [review]
LGTM

**Comment by cliping** [comment]
Please upload test result, thanks.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
currently there is new issue apperance, so the test result will fail, but soon I will upload failed result

**Comment by chunfuwen** [comment]
ERROR 1-type_specific.io-github-autotest-libvirt.virtual_disks.file_descriptor.hotplug.attach_device.associate_flag_seclabel_default -> CmdError: Command 'virsh "dom-fd-associate avocado-vt-vm1 diskfdgroup 6   ; attach-device avocado-vt-vm1 /tmp/xml_utils_temp_2os4l4ev.xml;" 6<>/var/lib/libvirt/images/device_test_fd' failed.
stdout: b'\n\n'
stderr: b"error: Failed to attach device from /tmp/xml_utils_temp_2os4l4ev.xml\nerror: internal error: unable to execute QEMU command 'add-fd': No file descriptor supplied via SCM_RIGHTS\n"
additional_info: None

**Pull request merged**
