### PR TITLE
v2v: Add some new cases(luks, '-ip')

### PR DESCRIPTION
**Pull request by xiaodwan**
1) Add several luks cases
2) Add a case that without '-ip' in command line

Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/2732

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.without_ip_option.esx_67.json.pattern.it_vddk.vpx_uri: /PASS (1539.92 s)
 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.without_ip_option.esx_67.rhev.rhv_upload.it_default: PASS (3043.31 s)
 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.luks.swap_luks.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (2489.34 s)
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.luks.swap_3luks.esx_67.rhev.rhv.it_vddk.vpx_uri: PASS (1843.23 s)

**Comment by xiaodwan** [comment]
@chunfuwen @chloerh @yantian0 Please help to review this PR, thanks.

**Review by yantian0 — APPROVED** [review]

**Review by chloerh — APPROVED** [review]

**Comment by chloerh** [comment]
Conflict?

**Comment by xiaodwan** [comment]
> Conflict?

Done

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.option_root.single.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (56.31 s)
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.option_root.dev_vglv.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (2344.45 s)
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.option_root.ask.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (2317.59 s)
 (1/2) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.option_root.first.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (1142.42 s)
 (2/2) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.option_root.dev_sdx.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (1112.19 s)

**Pull request merged**
