### PR TITLE
usb_device: fix with compatible match

### PR DESCRIPTION
**Pull request by dzhengfy**
Use compatible search pattern for both json and old format of qemu cmd line.

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
Before fix:
[rhel.usb_device.redirdev.tcp.usb2_0.companion.pcie-root.pcie-root-port.pcie-to-pci-bridge]
TestFail: the check of controller alias fails

After fix:
Class | Duration | Fail | (diff) | Skip | (diff) | Pass | (diff) | Total | (diff)
usb_device | 42 min | 0 | -1 | 1 |   | 27 | +1 | 28

libvirt-8.3.0-1.el9.x86_64

**Comment by dzhengfy** [comment]
Test


usb_device | 41 min | 0 |   | 0 |   | 28 |   | 28
-- | -- | -- | -- | -- | -- | -- | -- | --


<br class="Apple-interchange-newline">[usb_device](https://libvirt-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Results%20Dashboard/view/RHEL-8.7-x86_64-Report/job/libvirt-RHEL-8.7-runtest-x86_64-function-usb/2/testReport/rhel/usb_device/)	41 min	0		0		28		28

**Review by cliping — APPROVED** [review]
LGTM

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
