### PR TITLE
v2v: fix the modification for 'base_os_directory'

### PR DESCRIPTION
**Pull request by vwu-vera**
Fix the base_os_directory

### CODE REVIEW

**Comment by vwu-vera** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.block_dev.large.esx_70.json.pattern.it_vddk.vpx_uri: PASS (268.25 s)

 (1/1) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.block_dev.small.esx_70.json.pattern.it_vddk.vpx_uri: PASS (83.23 s)

**Comment by vwu-vera** [comment]
@xiaodwan Please help to review. Thanks.

**Comment by xiaodwan** [comment]
I proves that https://github.com/autotest/tp-libvirt/pull/3708 breaks some cases.
And this PR won't correct that.
I'll figure out the issue.

**Comment by xiaodwan** [comment]
Those PRs should resolve the previous issues.
https://github.com/autotest/tp-libvirt/pull/3882
https://github.com/autotest/tp-libvirt/pull/3883
https://github.com/avocado-framework/avocado-vt/pull/3281

**Comment by xiaodwan** [comment]
@vwu-vera You can close this PR now. Let's see if the issue has gone in latest codes.

**Pull request closed without merging**
