### PR TITLE
migration: Add case about parallel connections

### PR DESCRIPTION
**Pull request by cliping**
VIRT-XXXX - VM live migration - parallel network connections

### CODE REVIEW

**Comment by cliping** [comment]
Test result:
 (01/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.default_conn_num.with_precopy.p2p: PASS (285.76 s)
 (02/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.default_conn_num.with_precopy.non_p2p: PASS (284.05 s)
 (03/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_4.with_precopy.p2p: PASS (284.39 s)
 (04/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_4.with_precopy.non_p2p: PASS (282.83 s)
 (05/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_0.with_precopy.p2p: PASS (218.13 s)
 (06/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_0.with_precopy.non_p2p: PASS (217.98 s)
 (07/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_1.with_precopy.p2p: PASS (283.17 s)
 (08/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_1.with_precopy.non_p2p: PASS (283.78 s)
 (09/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_255.with_precopy.p2p: PASS (286.17 s)
 (10/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_255.with_precopy.non_p2p: PASS (282.58 s)
 (11/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_256.with_precopy.p2p: PASS (219.43 s)
 (12/12) type_specific.io-github-autotest-libvirt.migration.migration_performance_tuning.migration_parallel_connections.tcp.conn_num_256.with_precopy.non_p2p: PASS (220.12 s)

**Comment by cliping** [comment]
Depend on https://github.com/avocado-framework/avocado-vt/pull/3700.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by smitterl — APPROVED** [review]
LGTM

**Pull request merged**
