### PR TITLE
update test case for netfs pool with new cmd protocol_ver

### PR DESCRIPTION
**Pull request by ljmen**
update the matrix and the test content with new virsh cmd option protocol_ver

Singed-off-by: ljmen <lmen@redhat.com>

### CODE REVIEW

**Comment by lento-sun** [comment]
this pr depends on:
https://github.com/avocado-framework/avocado-vt/pull/2255

**Comment by lento-sun** [comment]
pls add depending info as above comment if necessary

**Comment by lento-sun** [comment]
@ljmen Conflicts happened, pls have a check.

**Comment by ljmen** [comment]
@lento-sun  updated,pls check it, thanks

**Comment by lento-sun** [comment]
Pls always remember to paste your test result here when you submit a PR which adds new case(s):
Such as https://github.com/autotest/tp-libvirt/pull/2395 having a "test result" comment.

**Comment by kylazhang** [comment]
Yes, as lento-sun said need a test result for all related case. May not all the cases but the update changed part may affected cases.

**Pull request merged**
