### PR TITLE
graphics_functional: add network case

### PR DESCRIPTION
**Pull request by dzhengfy**
Test scenario: Test islated/macvtap/host bridge network for graphics device (VIRT-13206)

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
Depend on https://github.com/avocado-framework/avocado-vt/pull/3569, https://github.com/avocado-framework/avocado-vt/pull/3570

**Comment by dzhengfy** [comment]
libvirt-8.9.0-2.el9.x86_64

```
 (1/5) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_vnet: WARN: Test passed but there were warnings during execution. Check the log for details. (12.11 s)
 (2/5) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_macvtap: WARN: Test passed but there were warnings during execution. Check the log for details. (13.62 s)
 (3/5) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_bridge: WARN: Test passed but there were warnings during execution. Check the log for details. (31.39 s)
 (4/5) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_nat: ERROR: Failed to start network virt-test-nat.\nDetail: error: Failed to start network virt-test-nat\nerror: internal error: Check the host setup: interface eth0 has kernel autoconfigured IPv6 routes and enabling forwarding  without accept_ra set to 2 will cause th... (7.66 s)
 (5/5) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_route: ERROR: Failed to start network virt-test-route.\nDetail: error: Failed to start network virt-test-route\nerror: internal error: Check the host setup: interface eth0 has kernel autoconfigured IPv6 routes and enabling forwarding  without accept_ra set to 2 will caus... (7.48 s)

```

**Comment by dzhengfy** [comment]
```
 (01/10) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.spice_only.listen_type_network.network_vnet: PASS (55.84 s)
 (02/10) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.spice_only.listen_type_network.network_macvtap: PASS (57.02 s)
 (03/10) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.spice_only.listen_type_network.network_bridge: PASS (66.31 s)
...
 (06/10) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_vnet: PASS (67.14 s)
 (07/10) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_macvtap: PASS (57.55 s)
 (08/10) type_specific.io-github-autotest-libvirt.graphics.functional.positive_tests.vnc_only.listen_type_network.network_bridge: PASS (83.99 s)

```

**Comment by dzhengfy** [comment]
@zhentang-tz Please help review, thanks

**Review by zhentang-tz — APPROVED** [review]
LGTM

**Review by Yingshun — APPROVED** [review]
LGTM

**Comment by Yingshun** [comment]
wait for all dependencies to merge

**Review by chloerh — APPROVED** [review]

**Pull request merged**
