### PR TITLE
Update with guest agent related changes

### PR DESCRIPTION
**Pull request by Hao-Liu**
There patches update the guest agent related tests to follow the new
method for preparation of guest agent. And some small fixes included.

This PR depends on https://github.com/autotest/virt-test/pull/1961.

Signed-off-by: Hao Liu <hliu@redhat.com>

### CODE REVIEW

**Comment by yumingfei** [comment]
Looks good for an overview.We'd better verify it one by one.

**Comment by waynesun09** [comment]
@Hao-Liu pls rebase this as pep8 mass update, and I'm running jobs against this PR on 6/7/upstream, so more feedback later.

**Comment by waynesun09** [comment]
The test result on rhel7 is good, with 10hrs run of all cases touched here, there are failed cases but with a cause not the change here. Other runs failed due to network env problem, also not cause by this change.
So ACK from me.
@will-Do pls also help check, thx.

**Comment by Hao-Liu** [comment]
@will-Do, please help go over this PR. Since the dependence patch has been merge a long time ago, and I'll cause fail continuously. It'll waste a lot of time for people who missed this PR and tries to fix this. Thanks.

**Comment by will-Do** [comment]
ACKed, thanks.

**Pull request merged**
