### PR TITLE
Add precheck whether nwfilter exists before call create create_nwfilt…

### PR DESCRIPTION
**Pull request by chunfuwen**
…er_xml

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
previous error message if without pre-checker:

```
 Traceback (most recent call last):
 File "/root/workdir/avocado-vt/virttest/utils_test/libvirt.py", line 2053, in create_nwfilter_xml
 filterxml = new_filter.new_from_filter_dumpxml(exist_filter)
File "/root/workdir/avocado-vt/virttest/libvirt_xml/nwfilter_xml.py", line 312, in new_from_filter_dumpxml
 filter_xml['xml'] = result.stdout_text.strip()
 File "/root/workdir/avocado-vt/virttest/propcan.py", line 196, in __setitem__
 return accessor(value)
 File "/root/workdir/avocado-vt/virttest/libvirt_xml/base.py", line 119, in set_xml
self.__dict_set__('xml', xml_utils.XMLTreeFile(value))
 File "/root/workdir/avocado-vt/virttest/xml_utils.py", line 294, in __init__
 raise IOError("Error parsing XML: '%s'" % xml)
OSError: Error parsing XML: ''
```

**Comment by chunfuwen** [comment]
#https://github.com/avocado-framework/avocado-vt/pull/3083

**Review by yalzhang — APPROVED** [review]
LGTM

**Review by kamilvarga — APPROVED** [review]
LGTM.

**Review by kylazhang — APPROVED** [review]

**Pull request merged**
