### PR TITLE
v2v: add win11/win2022 to vmcheck

### PR DESCRIPTION
**Pull request by vwu-vera**
bz#2031603. 

Signed-off-by: vwu-vera <vwu@redhat.com>

### CODE REVIEW

**Comment by vwu-vera** [comment]
@xiaodwan  Thanks for reminding me about this modification. Please help to review.

**Comment by xiaodwan** [comment]
Test result is always required. @vwu-vera

**Comment by vwu-vera** [comment]
(1/1) type_specific.io-github-autotest-libvirt.convert_vm_to_libvirt.esx.vm.6_5.windows.win11.arch_x86_64.it_default: PASS (4663.62 s)

 (1/1) type_specific.io-github-autotest-libvirt.convert_vm_to_libvirt.esx.vm.6_7.windows.win2022.arch_x86_64.it_vddk: PASS (503.48 s)

**Comment by vwu-vera** [comment]
Passed on RHEL9:
 (1/1) type_specific.io-github-autotest-libvirt.convert_vm_to_libvirt.esx.vm.6_5.windows.win11.arch_x86_64.it_default: PASS (9019.87 s)
 (1/1) type_specific.io-github-autotest-libvirt.convert_vm_to_libvirt.esx.vm.6_7.windows.win2022.arch_x86_64.it_vddk: PASS (617.73 s)

**Review by xiaodwan — APPROVED** [review]

**Pull request merged**
