### PR TITLE
virsh_edit: Random device xml tests.

### PR DESCRIPTION
**Pull request by rbian**

### CODE REVIEW

**Comment by will-Do** [comment]
```
# ./run -t libvirt --test ydu-libvirt.virsh.edit.positive_test.name_option.edit_rng -k --keep-image-between-test
SETUP: PASS (0.50 s)
DATA DIR: /home/ydu/Work/virt-test/shared/data
DEBUG LOG: /home/ydu/Work/virt-test/logs/run-2015-04-15-17.46.44/debug.log
TESTS: 4
(1/4) type_specific.ydu-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_null: FAIL (22.61 s)
(2/4) type_specific.ydu-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_dev: PASS (57.13 s)
(3/4) type_specific.ydu-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_type_unix: PASS (26.43 s)
(4/4) type_specific.ydu-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_type_invalid: PASS (26.99 s)
TOTAL TIME: 133.22 s (02:13)
TESTS PASSED: 3
TESTS FAILED: 1

**Comment by rbian** [comment]
Thanks @will-Do , Could you post your detail logs. The tests passed on my host:
14:15:09 (15/18) virsh.edit.positive_test.name_option.edit_rng.backend_null  Result: PASS 24.62 s
14:15:35 (16/18) virsh.edit.positive_test.name_option.edit_rng.backend_dev  Result: PASS DIFF 85.59 s

**Comment by will-Do** [comment]
BTW, I run the test on F20
```
17:46:47 INFO | Trying to edit xml with cmd [':g/<rng.*<\\/rng>/d', ":/<devices>/s/$/<rng model='virtio'><backend model='random' ><\\/backend><\\/rng>"]
17:46:47 ERROR| Error occurred: Client process terminated    (status: 0,    output: '')
17:46:47 DEBUG| Setting ignore_status to True.
17:46:47 DEBUG| Running 'systemctl status libvirtd.service'
17:46:47 ERROR| Expect success, but failure
17:46:47 DEBUG| Destroying VM
...
17:47:07 ERROR| 
17:47:07 ERROR| Traceback (most recent call last):
17:47:07 ERROR|   File "/home/ydu/Work/virt-test/virttest/standalone_test.py", line 220, in run_once
17:47:07 ERROR|     run_func(self, params, env)
17:47:07 ERROR|   File "/home/ydu/Work/tp-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_edit.py", line 222, in run
17:47:07 ERROR|     raise error.TestFail("Run failed with right command")
17:47:07 ERROR| TestFail: Run failed with right command
17:47:07 ERROR| 
17:47:07 ERROR| FAIL type_specific.ydu-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_null -> TestFail: Run failed with right command
17:47:07 INFO |

**Comment by rbian** [comment]
Passed on fedora21, maybe you can try again.
\# ./run -t libvirt --no-downloads --keep-image --keep-image-between-tests --tests virsh.edit.positive_test.name_option.edit_rng
SETUP: PASS (0.40 s)
DATA DIR: /tmp/tp-libvirt-virtio-rng-13/shared/data
DEBUG LOG: /tmp/tp-libvirt-virtio-rng-13/logs/run-2015-04-23-16.01.21/debug.log
TESTS: 4
(1/4) type_specific.io-github-autotest-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_null: PASS (38.19 s)
(2/4) type_specific.io-github-autotest-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_dev: PASS (25.59 s)
(3/4) type_specific.io-github-autotest-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_type_unix: PASS (26.15 s)
(4/4) type_specific.io-github-autotest-libvirt.virsh.edit.positive_test.name_option.edit_rng.backend_type_invalid: PASS (25.51 s)
TOTAL TIME: 115.47 s (01:55)
TESTS PASSED: 4
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by waynesun09** [comment]
ACK and merging now, thx @rbian @will-Do

**Pull request merged**
