### PR TITLE
Update func invoke usage

### PR DESCRIPTION
**Pull request by dzhengfy**
Due to the API is moved to a new place, we update the cases accordingly.

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2720

**Comment by dzhengfy** [comment]
Test on local host:
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.pty_channel.with_postcopy: PASS (208.92 s)
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.attach_virtual_disk.with_postcopy: PASS (200.87 s)

Because the sriov migration need two special hosts, I can not get them now. So I can not paste the result. But it is obvious that the change has been proved by other test cases' results.

**Comment by dzhengfy** [comment]
Retest after 2720 is updated,

Local test based on the change:

```
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.migrate_vm.positive_testing.migration_with_devices.attach_virtual_disk.with_postcopy
JOB ID     : 4419b80e5b9f15707f063aeaffd6078fecf9a017
JOB LOG    : /root/avocado/job-results/job-2020-09-01T10.34-4419b80/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.attach_virtual_disk.with_postcopy: PASS (161.03 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 164.38 s

# avocado run --vt-type libvirt --vt-machine-type q35 virsh.migrate_options_shared.positive_test.pty_channel.with_postcopy
JOB ID     : bba6e578e062c7c89e06e7c8340df7da4d375a32
JOB LOG    : /root/avocado/job-results/job-2020-09-01T10.15-bba6e57/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.pty_channel.with_postcopy: PASS (258.27 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 260.70 s
```

**Comment by chloerh** [comment]
@Yingshun Would you like to review this?

**Review by Yingshun — APPROVED** [review]
LGTM

**Pull request merged**
