### PR TITLE
don't use a hardcode emulator

### PR DESCRIPTION
**Pull request by zhijianli88**

### CODE REVIEW

**Comment by zhijianli88** [comment]
paste the result with emulator qemu-system-x86_64
```
$ sudo virsh dumpxml avocado-vt-vm1 | grep emulator
    <emulator>/usr/bin/qemu-system-x86_64</emulator>

$ sudo avocado -V run --vt-type libvirt type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.enable_logd
JOB ID     : e54fbccc39919b5acbd15c61749648473c1f3a0b
JOB LOG    : /home/lizhijian/avocado/job-results/job-2021-01-04T15.40-e54fbcc/job.log
 (1/1) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.enable_logd: -
PASS (85.35 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 86.33 s
```

**Comment by zhijianli88** [comment]
As suggested with @sathnaga , 
decouple this PR with [Add emulator accessor](https://github.com/avocado-framework/avocado-vt/pull/2873)

**Review by sathnaga — APPROVED** [review]
LGTM, below line, I just gave an example, just look around in library if there any other nicer way of getting this value, like any api/method present already.

     emulator_path = parse(vm_xml.get_devices(device_type='emulator')[0]['xml']).getroot().text

**Comment by zhijianli88** [comment]
> LGTM, below line, I just gave an example, just look around in library if there any other nicer way of getting this value, like any api/method present already.
> 
> ```
>  emulator_path = parse(vm_xml.get_devices(device_type='emulator')[0]['xml']).getroot().text 
> ```

one easier way is get it from vm_xml.xmltreefile directly instead of go through devices class
```
>>> vm_xml.xmltreefile.findall('devices/emulator')[0].text
'/usr/bin/kvm-spice'
```

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
