### PR TITLE
libvirt.tests: add test cases for migration testing

### PR DESCRIPTION
**Pull request by chuanchang**
Merge previous PR 372, 373, 374 and 450 into this PR and add new test scenarios for migration testing.

BTW, this PR based on https://github.com/autotest/virt-test/pull/2007, https://github.com/autotest/virt-test/pull/2067, https://github.com/autotest/virt-test/pull/2111.

$ ./run -t libvirt --list-tests|grep migrate_vm|wc -l
41
$  ./run -t libvirt --list-tests|grep migrate_vm
7487 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.pause_vm (requires root)
7488 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.reboot_vm (requires root)
7489 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.listen_address (requires root)
7490 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.basic.with_ssh (requires root)
7491 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tcp (requires root)
7492 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tls (requires root)
7493 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.p2p_listen_address.with_ssh (requires root)
7494 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.p2p_listen_address.with_tcp (requires root)
7495 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.p2p_listen_address.with_tls (requires root)
7496 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.tunnelled_migration.basic.with_ssh (requires root)
7497 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.tunnelled_migration.basic.with_tcp (requires root)
7498 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.tunnelled_migration.basic.with_tls (requires root)
7499 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_ipv6.with_ssh (requires root)
7500 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_ipv6.with_tcp (requires root)
7501 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_ipv6.with_tls (requires root)
7502 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.eject_cdrom_in_guest (requires root)
7503 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.requisite_policy (requires root)
7504 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.optional_policy (requires root)
7505 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.mandatory_policy (requires root)
7506 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.requisite_policy (requires root)
7507 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.optional_policy (requires root)
7508 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.mandatory_policy (requires root)
7509 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.requisite_policy (requires root)
7510 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.optional_policy (requires root)
7511 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.mandatory_policy (requires root)
7512 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_migration.stop_libvirtd_remotely (requires root)
7513 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_migration.disable_virt_use_nfs_remotely (requires root)
7514 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_migration.noexist_xml (requires root)
7515 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_migration.unprivileged_user (requires root)
7516 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_migration.same_host_uuid (requires root)
7517 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_migration.invalid_listen_address (requires root)
7518 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_migration.abort_job (requires root)
7519 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.p2p_migration.unreachable_destenation.with_ssh (requires root)
7520 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.p2p_migration.unreachable_destenation.with_tcp (requires root)
7521 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.p2p_migration.unreachable_destenation.with_tls (requires root)
7522 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.p2p_migration.invalid_listen_address.with_ssh (requires root)
7523 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.p2p_migration.invalid_listen_address.with_tcp (requires root)
7524 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.p2p_migration.invalid_listen_address.with_tls (requires root)
7525 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.migration_with_devices.startup_policy.attach_cdrom.invalid_policy (requires root)
7526 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.migration_with_devices.startup_policy.attach_floppy.invalid_policy (requires root)
7527 type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.invalid_policy (requires root)

Signed-off-by: Alex Jia <ajia@redhat.com>

### CODE REVIEW

**Comment by PandaWei** [comment]
can you attach the result of new cases?

**Comment by chuanchang** [comment]
[root@rhel7 virt-test]# ./run -t libvirt --tests type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices --no-downloads --keep-image --keep-image-between-tests
SETUP: PASS (0.50 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /home/ajia/Workspace/virt-test/logs/run-2015-03-26-14.46.41/debug.log
TESTS: 12
(1/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.eject_cdrom_in_guest: PASS (52.96 s)
(2/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.requisite_policy: PASS (47.66 s)
(3/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.optional_policy: PASS (48.91 s)
(4/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.mandatory_policy: PASS (48.99 s)
(5/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.requisite_policy: PASS (48.80 s)
(6/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.optional_policy: PASS (48.30 s)
(7/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.mandatory_policy: PASS (49.53 s)
(8/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.requisite_policy: PASS (49.22 s)
(9/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.optional_policy: PASS (49.06 s)
(10/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.mandatory_policy: PASS (48.80 s)
(11/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.attach_virtual_disk: PASS (73.02 s)
(12/12) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.migration_with_devices.attach_virtual_nic: PASS (50.55 s)
TOTAL TIME: 615.91 s (10:15)
TESTS PASSED: 12
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

[root@rhel7 virt-test]# ./run -t libvirt --tests type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration --no-downloads --keep-image --keep-image-between-tests
SETUP: PASS (0.50 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /home/ajia/Workspace/virt-test/logs/run-2015-03-26-14.57.36/debug.log
TESTS: 6
(1/6) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration.simple: PASS (38.07 s)
(2/6) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration.basic: PASS (47.24 s)
(3/6) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration.writethrough_driver_cache: PASS (145.82 s)
(4/6) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration.raw_to_qcow2_target_image_format.copy_storage_all: PASS (54.03 s)
(5/6) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration.raw_to_qcow2_target_image_format.copy_storage_inc: PASS (50.51 s)
(6/6) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_storage_migration.backing_file_with_copy_storage_inc: PASS (59.29 s)
TOTAL TIME: 395.07 s (06:35)
TESTS PASSED: 6
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by chuanchang** [comment]
[root@rhel7 virt-test]# ./run -t libvirt --tests type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration --no-downloads --keep-image --keep-image-between-tests
SETUP: PASS (0.50 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /home/ajia/Workspace/virt-test/logs/run-2015-03-26-19.52.12/debug.log
TESTS: 20
(1/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.vm_without_video: PASS (48.95 s)
(2/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.write_bytes_sec: PASS (51.94 s)
(3/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.read_bytes_sec: PASS (51.67 s)
(4/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.total_bytes_sec: PASS (50.53 s)
(5/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.total_iops_sec: PASS (51.66 s)
(6/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_watchdog.ib700: PASS (73.20 s)
(7/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_watchdog.i6300esb: PASS (73.98 s)
(8/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_smartcard.ccid: PASS (81.94 s)
(9/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.SandyBridge: SKIP
(10/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Hasswell: SKIP
(11/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Westmere_no_xsave: SKIP
(12/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Nehalem_no_xsave: SKIP
(13/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Penryn_no_xsave: SKIP
(14/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Conroe_no_xsave: PASS (49.42 s)
(15/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G5: SKIP
(16/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G4: SKIP
(17/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G3_no_xsave: SKIP
(18/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G2_no_xsave: SKIP
(19/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G1_no_xsave: SKIP
(20/20) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_s3_s4.between_source_and_remote: PASS (329.58 s)
TOTAL TIME: 1125.06 s (18:45)
TESTS PASSED: 10
TESTS FAILED: 0
TESTS SKIPPED: 10
SUCCESS RATE: 100.00 %

**Comment by kylazhang** [comment]
My test result:
*   9 cases SKIP
*  79 cases PASS
11:05:41 (1/88) virsh.migrate_vm.positive_testing.live_migration.pause_vm  Result: PASS 71.91 s
11:06:53 (2/88) virsh.migrate_vm.positive_testing.live_migration.reboot_vm  Result: PASS 81.18 s
11:08:15 (3/88) virsh.migrate_vm.positive_testing.live_migration.listen_address  Result: PASS 46.75 s
11:09:02 (4/88) virsh.migrate_vm.positive_testing.live_migration.diff_cpu_vendor  Result: SKIP 10.17 s
11:09:13 (5/88) virsh.migrate_vm.positive_testing.live_migration.cpuset  Result: PASS 70.30 s
11:10:23 (6/88) virsh.migrate_vm.positive_testing.live_migration.timeout  Result: PASS 54.58 s
11:11:18 (7/88) virsh.migrate_vm.positive_testing.live_migration.track_statistics  Result: PASS 62.19 s
11:12:21 (8/88) virsh.migrate_vm.positive_testing.live_migration.default_cache_size  Result: PASS 51.17 s
11:13:13 (9/88) virsh.migrate_vm.positive_testing.live_migration.set_cache_size  Result: PASS 68.99 s
11:14:22 (10/88) virsh.migrate_vm.positive_testing.live_migration.with_hugepages  Result: PASS 59.20 s
11:15:22 (11/88) virsh.migrate_vm.positive_testing.live_migration.iscsi.ipv4  Result: PASS 27.61 s
11:15:50 (12/88) virsh.migrate_vm.positive_testing.live_migration.iscsi.ipv6  Result: PASS 29.20 s
11:16:20 (13/88) virsh.migrate_vm.positive_testing.live_migration.stress.host.netperf_network  Result: PASS 677.60 s
11:27:38 (14/88) virsh.migrate_vm.positive_testing.p2p_migration.basic.with_ssh  Result: PASS 46.90 s
11:28:25 (15/88) virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tcp  Result: PASS 48.57 s
11:29:14 (16/88) virsh.migrate_vm.positive_testing.p2p_migration.basic.with_tls  Result: PASS 61.75 s
11:30:16 (17/88) virsh.migrate_vm.positive_testing.p2p_migration.listen_address.with_ssh  Result: PASS 47.01 s
11:31:04 (18/88) virsh.migrate_vm.positive_testing.p2p_migration.listen_address.with_tcp  Result: PASS 51.52 s
11:31:56 (19/88) virsh.migrate_vm.positive_testing.p2p_migration.listen_address.with_tls  Result: PASS 61.54 s
11:32:58 (20/88) virsh.migrate_vm.positive_testing.p2p_migration.with_keepalive_protocol.default_conf_less_than_keepalive_time  Result: PASS 84.11 s
11:34:22 (21/88) virsh.migrate_vm.positive_testing.tunnelled_migration.basic.with_ssh  Result: PASS 43.90 s
11:35:07 (22/88) virsh.migrate_vm.positive_testing.tunnelled_migration.basic.with_tcp  Result: PASS 52.01 s
11:35:59 (23/88) virsh.migrate_vm.positive_testing.tunnelled_migration.basic.with_tls  Result: PASS 61.71 s
11:37:01 (24/88) virsh.migrate_vm.positive_testing.migration_with_ipv6.with_ssh  Result: PASS 53.14 s
11:37:55 (25/88) virsh.migrate_vm.positive_testing.migration_with_ipv6.with_tcp  Result: PASS 57.21 s
11:38:53 (26/88) virsh.migrate_vm.positive_testing.migration_with_ipv6.with_tls  Result: PASS 70.18 s
11:40:03 (27/88) virsh.migrate_vm.positive_testing.migration_with_devices.eject_cdrom_in_guest  Result: PASS 45.52 s
11:40:49 (28/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.requisite_policy  Result: PASS 49.98 s
11:41:40 (29/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.optional_policy  Result: PASS 47.83 s
11:42:28 (30/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom.mandatory_policy  Result: PASS 47.38 s
11:43:16 (31/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.requisite_policy  Result: PASS 47.22 s
11:44:04 (32/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.optional_policy  Result: PASS 47.30 s
11:44:51 (33/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_floppy.mandatory_policy  Result: PASS 47.26 s
11:45:39 (34/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.requisite_policy  Result: PASS 47.86 s
11:46:28 (35/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.optional_policy  Result: PASS 47.62 s
11:47:16 (36/88) virsh.migrate_vm.positive_testing.migration_with_devices.startup_policy.attach_cdrom_and_floppy.mandatory_policy  Result: PASS 47.54 s
11:48:04 (37/88) virsh.migrate_vm.positive_testing.migration_with_devices.attach_virtual_disk  Result: PASS 52.96 s
11:48:57 (38/88) virsh.migrate_vm.positive_testing.migration_with_devices.attach_virtual_nic  Result: PASS 48.42 s
11:49:46 (39/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.write_bytes_sec  Result: PASS 48.57 s
11:50:35 (40/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.read_bytes_sec  Result: PASS 48.46 s
11:51:24 (41/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.total_bytes_sec  Result: PASS 48.63 s
11:52:13 (42/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_io_throttling.total_iops_sec  Result: PASS 49.77 s
11:53:03 (43/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_watchdog.ib700  Result: PASS 62.56 s
11:54:06 (44/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_watchdog.i6300esb  Result: PASS 62.85 s
11:55:10 (45/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_smartcard.ccid  Result: PASS 47.75 s
11:55:58 (46/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.SandyBridge  Result: PASS 47.16 s
11:56:46 (47/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Hasswell  Result: SKIP 21.74 s
11:57:08 (48/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Westmere_no_xsave  Result: PASS 44.07 s
11:57:52 (49/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Nehalem_no_xsave  Result: PASS 47.07 s
11:58:40 (50/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Penryn_no_xsave  Result: PASS 47.34 s
11:59:28 (51/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.intel.Conroe_no_xsave  Result: PASS 47.68 s
12:00:16 (52/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G5  Result: SKIP 21.58 s
12:00:38 (53/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G4  Result: SKIP 21.50 s
12:01:00 (54/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G3_no_xsave  Result: SKIP 21.47 s
12:01:22 (55/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G2_no_xsave  Result: SKIP 21.53 s
12:01:44 (56/88) virsh.migrate_vm.positive_testing.cross_rhel_platform_migration.with_cpu_model.amd.Opteron_G1_no_xsave  Result: SKIP 21.49 s
12:02:06 (57/88) virsh.migrate_vm.positive_testing.live_storage_migration.simple  Result: PASS 32.66 s
12:02:39 (58/88) virsh.migrate_vm.positive_testing.live_storage_migration.backing_file_with_copy_storage_inc  Result: PASS 55.45 s
12:03:35 (59/88) virsh.migrate_vm.negative_testing.live_migration.stop_libvirtd_remotely  Result: PASS 44.05 s
12:04:19 (60/88) virsh.migrate_vm.negative_testing.live_migration.disable_virt_use_nfs_remotely  Result: PASS 42.00 s
12:05:02 (61/88) virsh.migrate_vm.negative_testing.live_migration.noexist_xml  Result: PASS 41.18 s
12:05:44 (62/88) virsh.migrate_vm.negative_testing.live_migration.unprivileged_user  Result: PASS 41.30 s
12:06:25 (63/88) virsh.migrate_vm.negative_testing.live_migration.same_host_uuid  Result: PASS 49.62 s
12:07:16 (64/88) virsh.migrate_vm.negative_testing.live_migration.invalid_listen_address  Result: PASS 41.62 s
12:07:58 (65/88) virsh.migrate_vm.negative_testing.live_migration.abort_job  Result: PASS 51.08 s
12:08:49 (66/88) virsh.migrate_vm.negative_testing.live_migration.cancel_migration  Result: PASS 45.80 s
12:09:36 (67/88) virsh.migrate_vm.negative_testing.live_migration.restart_local_libvirtd  Result: PASS 160.41 s
12:12:16 (68/88) virsh.migrate_vm.negative_testing.live_migration.with_hugepages.no_config_target  Result: PASS 45.17 s
12:13:02 (69/88) virsh.migrate_vm.negative_testing.live_migration.with_hugepages.target_hugemem_less_than_vm_mem  Result: PASS 54.77 s
12:13:57 (70/88) virsh.migrate_vm.negative_testing.live_migration.with_hugepages.no_restart_target_libvirtd  Result: PASS 53.32 s
12:14:51 (71/88) virsh.migrate_vm.negative_testing.p2p_migration.unreachable_destenation.with_ssh  Result: PASS 94.38 s
12:16:26 (72/88) virsh.migrate_vm.negative_testing.p2p_migration.unreachable_destenation.with_tcp  Result: PASS 92.62 s
12:17:59 (73/88) virsh.migrate_vm.negative_testing.p2p_migration.unreachable_destenation.with_tls  Result: PASS 31.64 s
12:18:31 (74/88) virsh.migrate_vm.negative_testing.p2p_migration.invalid_listen_address.with_ssh  Result: PASS 41.74 s
12:19:13 (75/88) virsh.migrate_vm.negative_testing.p2p_migration.invalid_listen_address.with_tcp  Result: PASS 34.98 s
12:19:49 (76/88) virsh.migrate_vm.negative_testing.p2p_migration.invalid_listen_address.with_tls  Result: PASS 34.63 s
12:20:24 (77/88) virsh.migrate_vm.negative_testing.tunnelled_migration.restart_local_libvirtd  Result: PASS 144.95 s
12:22:50 (78/88) virsh.migrate_vm.negative_testing.live_storage_migration.no_create_target_image.simple  Result: PASS 23.47 s
12:23:13 (79/88) virsh.migrate_vm.negative_testing.live_storage_migration.no_create_target_image.basic  Result: PASS 24.98 s
12:23:39 (80/88) virsh.migrate_vm.negative_testing.live_storage_migration.qcow2_to_raw_target_image_format.copy_storage_all  Result: PASS 28.54 s
12:24:08 (81/88) virsh.migrate_vm.negative_testing.live_storage_migration.qcow2_to_raw_target_image_format.copy_storage_inc  Result: PASS 28.56 s
12:24:37 (82/88) virsh.migrate_vm.negative_testing.live_storage_migration.mutually_exclusive_options  Result: PASS 28.30 s
12:25:06 (83/88) virsh.migrate_vm.negative_testing.rdma_migration.no_memory_hard_limit  Result: PASS 26.60 s
12:25:33 (84/88) virsh.migrate_vm.negative_testing.rdma_migration.no_rdma_env  Result: PASS 25.12 s
12:25:59 (85/88) virsh.migrate_vm.negative_testing.rdma_migration.no_rdma_env_rdma_pin_all  Result: PASS 25.18 s
12:26:24 (86/88) virsh.migrate_vm.negative_testing.rdma_migration.no_rdma_env_turn_off_rdma_pin_all  Result: PASS 25.03 s
12:26:50 (87/88) virsh.migrate_vm.negative_testing.cross_rhel_platform_migration.with_disabled_device.sound_device  Result: SKIP 4.36 s
12:26:55 (88/88) virsh.migrate_vm.negative_testing.cross_rhel_platform_migration.with_disabled_device.with_host_cdrom  Result: SKIP 4.49 s

**Comment by dzhengfy** [comment]
This pr is used in our migration test now. I will submit patch if anything need to be fixed later. So now it is ok to be merged.

**Comment by will-Do** [comment]
OK, just rebase and merge this pull request by command.

**Pull request closed without merging**
