### PR TITLE
Fix the sysinfo problem when dmidecode can not give the version

### PR DESCRIPTION
**Pull request by kylazhang**
Remove the status check for dmidecode commands output as with pipe it can not show the right commands status, and use output check instead

### CODE REVIEW

**Comment by yumingfei** [comment]
Reasonable, but do we need to check the output format first?

**Comment by kylazhang** [comment]
@yumingfei In my opinion only 2 types of result we can get, the version string or NULL. I think we do not need to check more.

**Comment by yumingfei** [comment]
Oh, I meant the output data:
[root@domain virt-test]# dmidecode -t processor | awk -F: '/Version/ {print $2}'
 Intel(R) Core(TM)2 Duo CPU     E7500  @ 2.93GHz     

Since you simply compare command output and xml output, I'm afraid that little difference may cause unnecessary failure, such as one more space for command output.
So I think that splitting the elements(Intel, 2 Duo CPU, E7500...) in output would be more reasonable.

**Comment by kylazhang** [comment]
@yumingfei This patch is only for correcting the wrong judge situation which cause my test fail, I think the problem you think about should be another issues. Thanks

**Comment by kylazhang** [comment]
@waynesun09 how do you think about the issue that yumingfei said?

**Comment by liyangfnst** [comment]
good enough, merge it now.

**Pull request merged**
