### PR TITLE
libvirt_rng: add test case with invalid XML

### PR DESCRIPTION
**Pull request by smitterl**
1. In the past, libvirtd crashed on invalid address.
Checking error message on invalid address setting
confirms libvirtd handles this correctly.

2. Check error message on invalid model.

### CODE REVIEW

**Comment by smitterl** [comment]
```
JOB ID     : 1ae5de528aa841bb749a13e3745fd0aea0c374db
JOB LOG    : /var/lib/avocado/job-results/job-2023-07-04T10.19-1ae5de5/job.log
 (1/1) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.invalid_address.device_assign: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.invalid_address.device_assign: PASS (13.10 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-07-04T10.19-1ae5de5/results.html
JOB TIME   : 14.83 s

```

**Comment by smitterl** [comment]
JOB ID     : 039c3072aed3c3349a028d608a90708f74634450
JOB LOG    : /var/lib/avocado/job-results/job-2023-07-05T03.47-039c307/job.log
 (1/1) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.invalid_model.device_assign: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.invalid_model.device_assign: PASS (6.72 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-07-05T03.47-039c307/results.html
JOB TIME   : 7.99 s

**Comment by smitterl** [comment]
```
JOB ID     : 9b55c184fbfc29ed4aeb2b4944eb7ae52df3d991
JOB LOG    : /var/lib/avocado/job-results/job-2023-07-05T08.17-9b55c18/job.log
 (1/2) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.invalid_address.device_assign: PASS (9.48 s)
 (2/2) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.invalid_model.device_assign: PASS (9.61 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2023-07-05T08.17-9b55c18/results.html
JOB TIME   : 20.77 s

```

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
