### PR TITLE
virsh_attach_device: Fix "No more PCI slots" error

### PR DESCRIPTION
**Pull request by liuyd96**
Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>

### CODE REVIEW

**Comment by liuyd96** [comment]
Veirfied on q35
```
# avocado run --vt-machine-type q35 --vt-type libvirt block.multi_virtio_file..normal_test.hot_attach_hot_vm..name_ref.file_positional.domain_positional
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 06285379ec44d7c0937ab593078df7c17cd0d14b
JOB LOG    : /root/avocado/job-results/job-2021-04-27T06.00-0628537/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: PASS (132.43 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional: PASS (133.49 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: PASS (133.16 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional:PASS (134.54 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 535.13 s
```

**Comment by liuyd96** [comment]
On aarch64
Before this commit
```
# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio block.multi_virtio_file..normal_test.hot_attach_hot_vm..name_ref.file_positional.domain_positional
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 13b0ad6f88f963d5263ec80e7203f2d763b30e8a
JOB LOG    : /root/avocado/job-results/job-2021-04-27T06.19-13b0ad6/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (41.53 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (43.53 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: FAIL: Positive operational test failed (43.77 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional:FAIL: Positive operational test failed (44.35 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 4 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 174.15 s
```
After this commit
```
# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio block.multi_virtio_file..normal_test.hot_attach_hot_vm..name_ref.file_positional.domain_positional
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
JOB ID     : 29fd42f361736186ba4fdf6d6b4aa989572f2485
JOB LOG    : /root/avocado/job-results/job-2021-04-27T06.30-29fd42f/job.log
 (1/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: PASS (225.36 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.without_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional: PASS (226.88 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.persistent.name_ref.file_positional.domain_positional: PASS (226.74 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm.live_config.name_ref.file_positional.domain_positional:PASS (227.24 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 907.27 s
```

**Comment by liuyd96** [comment]
@chloerh @chunfuwen . Help review it. Thanks.

**Review by chunfuwen — APPROVED** [review]
lgtm

**Review by chloerh — APPROVED** [review]

**Pull request merged**
