### PR TITLE
[Batch 1] Fix Admin API cases for split daemon mode

### PR DESCRIPTION
**Pull request by iccaszhulili**
As the server name changed under split daemon mode, the config
file is also changed, update them.

Signed-off-by: Lily Zhu <lizhu@redhat.com>

### CODE REVIEW

**Comment by iccaszhulili** [comment]
Under split daemon

JOB ID     : 65f3407eb9033816efa84ddfbe0134c25b90d13a
JOB LOG    : /root/avocado/job-results/job-2020-11-06T20.17-65f3407/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virt_admin.srv_clients_info: PASS (17.09 s)
JOB ID     : 0e5c0dce0eba5916685e78999ff72c11294ef8b7
JOB LOG    : /root/avocado/job-results/job-2020-11-06T20.18-0e5c0dc/job.log
 (1/2) type_specific.io-github-autotest-libvirt.virt_admin.srv_list.admin: PASS (6.87 s)
 (2/2) type_specific.io-github-autotest-libvirt.virt_admin.srv_list.libvirtd: PASS (6.93 s)
JOB ID     : 250b3ccfcf4ce2496fd807ba12931d9f385511e2
JOB LOG    : /root/avocado/job-results/job-2020-11-06T20.19-250b3cc/job.log
 (1/2) type_specific.io-github-autotest-libvirt.virt_admin.srv_threadpool_info.libvirtd: PASS (9.75 s)
 (2/2) type_specific.io-github-autotest-libvirt.virt_admin.srv_threadpool_info.admin: PASS (9.67 s)

**Comment by iccaszhulili** [comment]
Also tested under legacy mode, all cases passed either

**Review by chloerh — COMMENTED** [review]
Well, 'test.fail' seems good, 'raise' could be removed.

**Comment by iccaszhulili** [comment]
> Well, 'test.fail' seems good, 'raise' could be removed.

@chloerh updated

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by Yingshun** [comment]
Depends on https://github.com/avocado-framework/avocado-vt/pull/2817

**Review by chloerh — APPROVED** [review]
Waiting for dependency

**Comment by iccaszhulili** [comment]
@chloerh https://github.com/avocado-framework/avocado-vt/pull/2817 has been merged already. Thanks

**Pull request merged**
