### PR TITLE
Fix guest agent get illegal character when getting ip address

### PR DESCRIPTION
**Pull request by chunfuwen**
Fix guest agent get illegal character when getting ip address
Previously,it attempts to login guest and use command to get ipaddress, in some s390x guest, it may pop up some illegal characters while executing those commands, such as [35m192.168.122.21[0m'

Moreover, it need to restore to previous root password, otherwise it affect next case for login

### CODE REVIEW

**Comment by chunfuwen** [comment]
previously failure log:

--user root --password $1$77HrOTpq$dNdCFwAEhuUCFA/klZySH1 --encrypted'
2024-11-27 01:56:04,582 avocado.utils.process process          L0473 DEBUG| [stdout] Password set successfully for root in avocado-vt-vm1
2024-11-27 01:56:04,586 avocado.utils.process process          L0714 INFO | Command '/usr/bin/virsh set-user-password --domain avocado-vt-vm1 --user root --password $1$77HrOTpq$dNdCFwAEhuUCFA/klZySH1 --encrypted' finished with 0 after 0.061529057s
2024-11-27 01:56:04,587 avocado.virttest.virsh virsh            L0873 DEBUG| status: 0
2024-11-27 01:56:04,587 avocado.virttest.virsh virsh            L0874 DEBUG| stdout: Password set successfully for root in avocado-vt-vm1
2024-11-27 01:56:04,587 avocado.virttest.virsh virsh            L0875 DEBUG| stderr:
2024-11-27 01:56:04,587 avocado.virttest.utils_test.libvirt libvirt          L1379 DEBUG| Command output:Password set successfully for root in avocado-vt-vm1
2024-11-27 01:56:04,588 aexpect.remote remote           L0464 DEBUG| Attempting to log into [35m192.168.122.21[0m:22 using ssh (timeout 30s)
2024-11-27 01:56:04,840 aexpect.remote remote           L0476 DEBUG| Client process terminated    (status: 255,    output: 'hostname contains invalid characters\n')
2024-11-27 01:56:06,844 aexpect.remote remote           L0416 DEBUG| Login command: 'ssh -vv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -o PreferredAuthentications=password root@[35m192.168.122.21[0m'
2024-11-27 01:56:07,010 aexpect.remote remote           L0476 DEBUG| Client process terminated    (status: 255,    output: 'hostname contains invalid characters\n')
2024-11-27 01:56:09,011 aexpect.remote remote           L0416 DEBUG| Login command: 'ssh -vv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -o PreferredAuthentications=password root@[35m192.168.122.21[0m'
2024-11-27 01:56:09,289 aexpect.remote remote           L0476 DEBUG| Client process terminated    (status: 255,    output: 'hostname contains invalid characters\n')
2024-11-27 01:56:11,294 aexpect.remote remote           L0416 DEBUG| Login command: 'ssh -vv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -o PreferredAuthentications=password root@[35m192.168.122.21[0m'
2024-11-27 01:56:11,474 aexpect.remote remote           L0476 DEBUG| Client process terminated    (status: 255,    output: 'hostname contains invalid characters\n')
2024-11-27 01:56:13,475 aexpect.remote remote           L0416 DEBUG| Login command: 'ssh -vv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -o PreferredAuthentications=password root@[35m192.168.122.21[0m'
2024-11-27 01:56:13,745 aexpect.remote remote           L0476 DEBUG| Client process terminated    (status: 255,    output: 'hostname contains invalid characters\n')
2024-11-27 01:56:15,746 aexpect.remote remote           L0416 DEBUG| Login command: 'ssh -vv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -o PreferredAuthentications=password root@[35m192.168.122.21[0m'
2024-11-27 01:56:15,913 aexpect.remote remote           L0476 DEBUG| Client process terminated    (status: 255,    output: 'hostname contains

**Comment by chunfuwen** [comment]
2024-11-27 01:56:47,458 avocado.virttest.libvirt_vm libvirt_vm       L2653 DEBUG| Starting vm 'avocado-vt-vm1'
2024-11-27 01:56:47,682 avocado.virttest.utils_misc utils_misc       L0578 DEBUG| waiting for domain avocado-vt-vm1 to start (0.000079 secs)
2024-11-27 01:56:47,753 avocado.virttest.libvirt_vm libvirt_vm       L1549 DEBUG| Command used to create serial console: virsh -c qemu:///system console avocado-vt-vm1 serial0
2024-11-27 01:56:47,991 avocado.virttest.libvirt_vm libvirt_vm       L2682 DEBUG| Updating nic 0 with mac 52:54:00:e4:e2:e7 on vm avocado-vt-vm1
2024-11-27 01:56:48,770 aexpect.remote remote           L0313 DEBUG| Got shell prompt -- logged in
2024-11-27 01:56:48,770 aexpect.client client           L1199 DEBUG| Sending command: list
2024-11-27 01:56:48,916 avocado.virttest.virt_vm virt_vm          L1264 DEBUG| Attempting to log into 'avocado-vt-vm1' (timeout 240s)
2024-11-27 01:56:56,194 avocado.virttest.ip_sniffing ip_sniffing      L0059 DEBUG| Updated HWADDR (52:54:00:e4:e2:e7)<->(192.168.122.21) IP pair into address cache
2024-11-27 01:56:56,422 avocado.virttest.virt_vm virt_vm          L0943 DEBUG| Found/Verified IP 192.168.122.21 for VM avocado-vt-vm1 NIC 0
2024-11-27 01:57:00,134 avocado.virttest.virsh virsh            L1666 DEBUG| Undefine VM avocado-vt-vm1
2024-11-27 01:57:00,150 avocado.virttest.virsh virsh            L1651 DEBUG| Define VM from /var/tmp/xml_utils_temp_ebyvvi6b.xml
2024-11-27 01:57:00,179 avocado.test stacktrace       L0040 ERROR|
2024-11-27 01:57:00,179 avocado.test stacktrace       L0042 ERROR| Reproduced traceback from: /var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py:298
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR| Traceback (most recent call last):
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py", line 49, in run
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     vm.prepare_guest_agent(prepare_xml=False, channel=False, start=True)
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/libvirt_vm.py", line 3205, in prepare_guest_agent
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     self.install_package("qemu-guest-agent", serial=serial)
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/libvirt_vm.py", line 3120, in install_package
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     session = self.wait_for_login() if not serial else self.wait_for_serial_login()
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|               ^^^^^^^^^^^^^^^^^^^^^
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/libvirt_vm.py", line 2012, in wait_for_login
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     return super(VM, self).wait_for_login(
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/virt_vm.py", line 1289, in wait_for_login
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     return self.login(nic_index, internal_timeout, username, password)
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/error_context.py", line 141, in new_fn
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     return fn(*args, **kwargs)
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|            ^^^^^^^^^^^^^^^^^^^
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/virt_vm.py", line 1134, in login
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     session = remote.remote_login(
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|               ^^^^^^^^^^^^^^^^^^^^
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/root/.libvirt-ci-venv-ci-runtest-ubPUzW/lib/python3.12/site-packages/aexpect-1.7.0-py3.12.egg/aexpect/remote.py", line 422, in remote_login
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|     handle_prompts(session, username, password, prompt, timeout)
2024-11-27 01:57:00,181 avocado.test stacktrace       L0049 ERROR|   File "/root/.libvirt-ci-venv-ci-runtest-ubPUzW/lib/python3.12/site-packages/aexpect-1.7.0-py3.12.egg/aexpect/remote.py", line 281, in handle_prompts
2024-11-27 01:57:00,182 avocado.test stacktrace       L0049 ERROR|     raise LoginAuthenticationError("Got password prompt twice",
2024-11-27 01:57:00,182 avocado.test stacktrace       L0049 ERROR| aexpect.remote.LoginAuthenticationError: Got password prompt twice    (output: "\nPermission denied, please try again.\nroot@192.168.122.21's password: ")

**Comment by chunfuwen** [comment]
Those issue happen when test case 1 already update root password, but it failed to complete restore root password due to some reasons. So it will impact next case run(fail next case)

**Comment by chunfuwen** [comment]
(1/1) type_specific.io-github-autotest-libvirt.virsh.set_user_password.normal_test.root.encrypted: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.virsh.set_user_password.normal_test.root.encrypted: PASS (98.40 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-11-27T21.28-6e9a8fd/results.html
JOB TIME   : 100.06 s

**Comment by chunfuwen** [comment]
JOB LOG    : /var/log/avocado/job-results/job-2024-11-27T22.29-e67e752/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.set_user_password.normal_test.root.encrypted: STARTED
 (1/1) type_specific.io-github-autotest-libvirt.virsh.set_user_password.normal_test.root.encrypted: PASS (81.62 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-11-27T22.29-e67e752/results.html
JOB TIME   : 83.18 s

**Review by iccaszhulili — APPROVED** [review]

**Comment by iccaszhulili** [comment]
LGTM

**Comment by chunfuwen** [comment]
this is urgent need ,let's merge it

**Pull request merged**
