### PR TITLE
remote_access: Add root password to fix type error

### PR DESCRIPTION
**Pull request by cliping**
Add root password to pass through the login prompt.

Signed-off-by: lcheng <lcheng@redhat.com>

### CODE REVIEW

**Comment by cliping** [comment]
Before fix:
# avocado run --vt-type libvirt --vt-machine-type q35 virsh.remote_with_unix.negative_testing.socket_access_controls.cfg_file --vt-connect-uri qemu:///system
JOB ID     : 5b6bbe766920d8d67ad10e8524a9c446f2f344aa
JOB LOG    : /root/avocado/job-results/job-2021-12-13T04.06-5b6bbe7/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_unix.negative_testing.socket_access_controls.cfg_file: ERROR: unsupported operand type(s) for +: 'NoneType' and 'str' (66.90 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 68.39 s

**Comment by cliping** [comment]
After fix:
#avocado run --vt-type libvirt --vt-machine-type q35 virsh.remote_with_unix.negative_testing.socket_access_controls.cfg_file --vt-connect-uri qemu:///system
JOB ID     : 9db0fd5bed901bfd4392ea8197f83b2c64add437
JOB LOG    : /root/avocado/job-results/job-2021-12-13T05.14-9db0fd5/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_unix.negative_testing.socket_access_controls.cfg_file: PASS (65.52 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 67.00 s

**Review by chunfuwen — APPROVED** [review]
LGTM

**Comment by chunfuwen** [comment]
mark it as minor_fix

**Pull request merged**
