### PR TITLE
libvirt_rng: relax qemu cmdline check

### PR DESCRIPTION
**Pull request by smitterl**
The used qemu interface for devices has changed from version 6.1 to 6.2.
Tests will failed with qemu 6.2 during qemu commandline check.

Update the test code to allow for both 6.1 and 6.2 API.

Use regular expressions inside the python code instead of grep
on shell in order to preserve the actual cmdline for debugging purposes.
This way if a check fails, the log will contain the actual cmdline that was
tested which currently isn't the case.

Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>

### CODE REVIEW

**Comment by smitterl** [comment]
Test run w/ QEMU 6.2:
```
# avocado run --vt-type libvirt --vt-machine-type s390-virtio --vt-connect-uri qemu:///system libvirt_rng.backend_builtin.hotplug_unplug.positive.no_options,libvirt_rng.backend_builtin.device_assign,libvirt_rng.backend_rdm.default.hotplug_unplug.positive.persistent,libvirt_rng.backend_rdm.default.device_assign,libvirt_rng.backend_rdm.with_packed_on.device_assign,libvirt_rng.backend_udp.bind_connect_mode.hotplug_unplug.positive.no_options,libvirt_rng.backend_udp.bind_connect_mode.device_assign,libvirt_rng.backend_udp.connect_mode.hotplug_unplug.positive.persistent,libvirt_rng.backend_udp.connect_mode.device_assign,libvirt_rng.backend_tcp.connect_mode.hotplug_unplug.positive.no_options,libvirt_rng.backend_tcp.connect_mode.device_assign,libvirt_rng.backend_tcp.bind_mode.hotplug_unplug.positive.no_options,libvirt_rng.backend_tcp.bind_mode.device_assign,libvirt_rng.rng_rate.back_rdm.device_assign                                                                                                                                                         JOB ID     : 1097b340ac64f71b1666db1e0b1eb2626f608471
JOB LOG    : /root/avocado/job-results/job-2021-12-22T10.34-1097b34/job.log
 (01/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.hotplug_unplug.positive.no_options: PASS (19.33 s)
 (02/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.device_assign: PASS (21.17 s)
 (03/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.default.hotplug_unplug.positive.persistent: PASS (16.60 s)
 (04/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.default.device_assign: PASS (18.35 s)
 (05/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.with_packed_on.device_assign: PASS (20.55 s)
 (06/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.bind_connect_mode.hotplug_unplug.positive.no_options: PASS (76.82 s)
 (07/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.bind_connect_mode.device_assign: PASS (80.51 s)
 (08/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.connect_mode.hotplug_unplug.positive.persistent: PASS (77.81 s)
 (09/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.connect_mode.device_assign: PASS (77.93 s)
 (10/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.connect_mode.hotplug_unplug.positive.no_options: PASS (16.47 s)
 (11/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.connect_mode.device_assign: PASS (21.44 s)
 (12/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.bind_mode.hotplug_unplug.positive.no_options: PASS (17.49 s)
 (13/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.bind_mode.device_assign: PASS (20.70 s)
 (14/14) type_specific.io-github-autotest-libvirt.libvirt_rng.rng_rate.back_rdm.device_assign: PASS (38.71 s)
RESULTS    : PASS 14 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 524.58 s
```

**Comment by smitterl** [comment]
Test run w/ QEMU 6.1:
```
# avocado run --vt-type libvirt --vt-machine-type s390-virtio --vt-connect-uri qemu:///system libvirt_rng.backend_builtin.hotplug_unplug.positive.no_options,libvirt_rng.backend_builtin.device_assign,libvirt_rng.backend_rdm.default.hotplug_unplug.positive.persistent,libvirt_rng.backend_rdm.default.device_assign,libvirt_rng.backend_rdm.with_packed_on.device_assign,libvirt_rng.backend_udp.bind_connect_mode.hotplug_unplug.positive.no_options,libvirt_rng.backend_udp.bind_connect_mode.device_assign,libvirt_rng.backend_udp.connect_mode.hotplug_unplug.positive.persistent,libvirt_rng.backend_udp.connect_mode.device_assign,libvirt_rng.backend_tcp.connect_mode.hotplug_unplug.positive.no_options,libvirt_rng.backend_tcp.connect_mode.device_assign,libvirt_rng.backend_tcp.bind_mode.hotplug_unplug.positive.no_options,libvirt_rng.backend_tcp.bind_mode.device_assign,libvirt_rng.rng_rate.back_rdm.device_assign 
JOB ID     : e21c055dceeba636f70d58892ecd92382c0661b2
JOB LOG    : /root/avocado/job-results/job-2021-12-22T10.44-e21c055/job.log
 (01/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.hotplug_unplug.positive.no_options: PASS (18.33 s)
 (02/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.device_assign: PASS (17.84 s)
 (03/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.default.hotplug_unplug.positive.persistent: PASS (19.79 s)
 (04/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.default.device_assign: PASS (20.15 s)
 (05/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_rdm.with_packed_on.device_assign: PASS (21.48 s)
 (06/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.bind_connect_mode.hotplug_unplug.positive.no_options: PASS (76.94 s)
 (07/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.bind_connect_mode.device_assign: PASS (80.50 s)
 (08/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.connect_mode.hotplug_unplug.positive.persistent: PASS (76.92 s)
 (09/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.connect_mode.device_assign: PASS (80.13 s)
 (10/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.connect_mode.hotplug_unplug.positive.no_options: PASS (19.61 s)
 (11/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.connect_mode.device_assign: PASS (21.08 s)
 (12/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.bind_mode.hotplug_unplug.positive.no_options: PASS (16.48 s)
 (13/14) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp.bind_mode.device_assign: PASS (19.68 s)
 (14/14) type_specific.io-github-autotest-libvirt.libvirt_rng.rng_rate.back_rdm.device_assign: PASS (40.82 s)
RESULTS    : PASS 14 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 530.44 s
```

**Review by chunfuwen — APPROVED** [review]
LGTM

**Review by dzhengfy — COMMENTED** [review]
LGTM

**Comment by dzhengfy** [comment]
@smitterl Please help fix the conflicts.

**Comment by smitterl** [comment]
> @smitterl Please help fix the conflicts.

Done :)

**Comment by smitterl** [comment]
(reopened after closing accidentally)

**Pull request merged**
