### PR TITLE
SRIOV: add new negative scenario when start vm with hostdev interface

### PR DESCRIPTION
**Pull request by meinaLi**
This PR mainly automates a new negative scenatio with invalid driver
    model for hostdev interface in VIRT-293914.

### CODE REVIEW

**Comment by meinaLi** [comment]
```
# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 sriov.vm_lifecycle.start.negative.hostdev_interface.invalid_driver_model
JOB ID     : 9af7f84915f2ce706553f7ec3c108eaf5b0dceb2
JOB LOG    : /var/lib/avocado/job-results/job-2024-03-04T21.59-9af7f84/job.log
 (1/1) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start.negative.hostdev_interface.invalid_driver_model: PASS (17.11 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2024-03-04T21.59-9af7f84/results.html
JOB TIME   : 18.79 s
```

**Comment by meinaLi** [comment]
@Yingshun Please help review this SRIOV PR, thanks.

**Comment by Yingshun** [comment]
> This PR mainly automate the scenario 9 in test matrix in VIRT-293914.

@meinaLi Can you plz describe the test scenario in commit message? The test scenario order might be changed in the future and it's not easy for others to get the purpose of this PR from the current message.

**Comment by meinaLi** [comment]
> @meinaLi Can you plz describe the test scenario in commit message? The test scenario order might be changed in the future and it's not easy for others to get the purpose of this PR from the current message.

Thanks for your useful suggestion. I've already updated it now.

**Review by Yingshun — APPROVED** [review]

**Review by nanli1 — APPROVED** [review]

**Pull request merged**
