### PR TITLE
v2v: update rhv-disk-uuid cases

### PR DESCRIPTION
**Pull request by xiaodwan**
Update the cases based on bz#1789279.

Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com>

### CODE REVIEW

**Comment by xiaodwan** [comment]
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.no-copy-illegal.exist_rhv-disk-uuid.esx_67.rhev.rhv_upload.it_vddk.vpx_uri: PASS (372.37 s)

**Comment by xiaodwan** [comment]
depends on https://github.com/avocado-framework/avocado-vt/pull/3118

**Comment by xiaodwan** [comment]
@chloerh @chunfuwen @yantian0 please help to review this PR, thanks.

**Review by yantian0 — APPROVED** [review]

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
