### PR TITLE
libvirt: update cases for avocado execution

### PR DESCRIPTION
**Pull request by will-Do**
1. Replace the default VM name as avocado using 'avocado-vt-vm1'.
2. Function utils_misc.find_command is deprecated, and which will not
raise ValueError when command not find, so replace it by the right function.

Signed-off-by: Yanbing Du <ydu@redhat.com>

### CODE REVIEW

**Comment by PandaWei** [comment]
ACK

**Comment by waynesun09** [comment]
ACK

**Comment by waynesun09** [comment]
Please on hold of merging this, as different group haven't fully migrated to avocado-vt yet, this will possibly fail testing for users still on virt-test. You could use the PR to run tests on avocado-vt for now.

**Comment by will-Do** [comment]
Now our job already migrate to avocado, so let's merge this PR

**Pull request merged**
