### PR TITLE
Storage discard

### PR DESCRIPTION
**Pull request by PandaWei**
Fergus Yu has closed the old PR #436 ( libvirt.tests: Fix storage_discard bugs.)

Now I'm in charge of this work and push two commits:

1)   storage_discard: fix bugs about lvm
     * Create lvm for given block device too.
     * Delete lvthin before vgthin in cleanup
2)  storage_discard: ensure all storage discarded safely
    Sometimes, although fstrim has returned,
    the operation of discarding unused storage need to last longer.
    This commit allow it enough time to finish all works and
    ensure all discard storage is released safely.

### CODE REVIEW

**Comment by PandaWei** [comment]
I have test it at local.
[root@localhost tp-libvirt]# inspekt lint libvirt/tests/src/storage_discard.py
Syntax check PASS
[root@localhost tp-libvirt]# inspekt style libvirt/tests/src/storage_discard.py
PEP8 compliance check PASS
[root@localhost tp-libvirt]# inspekt indent libvirt/tests/src/storage_discard.py
Indentation check PASS
[root@localhost tp-libvirt]# inspekt github 521
Fetching https://github.com/autotest/tp-libvirt/pull/521.patch -> /tmp/github-521.patch
Github ID #521 check PASS

But the CI show failed.
I want to take a look at the 'Details',
but the URL https://travis-ci.org/autotest/tp-libvirt/builds/58374341 couldn't be opened.
who can tell why?

**Comment by will-Do** [comment]
snip from travis-ci
```
$ inspekt lint
************* Module src.storage_discard
E1123: 78,4: create_volume: Unexpected keyword argument 'force' in function call
Pylint check fail: /home/travis/build/autotest/tp-libvirt/libvirt/tests/src/storage_discard.py
Syntax check FAIL
The command "inspekt lint" exited with 1.

**Comment by PandaWei** [comment]
@Hao-Liu 
I calls vg_create to like below,
lv_utils.vg_create(vgname, device, force=True)

and the declare at autotest/client/lv_utils.py
@error.context_aware
def vg_create(vg_name, pv_list, force=False):

Both of them have three paramters.
but CI reports that Unexpected keyword argument 'force' .
I suspect it's a bug of CI.
can you help me to check it? 
Thanks in advance.

**Comment by Hao-Liu** [comment]
Sure, @PandaWei I'll check later today.

**Comment by Hao-Liu** [comment]
@PandaWei . I've checked your PR and It results no pylint error locally. I think it's caused by a CI malfunctioning. Please help try rebase this pull request to check if it can be fixed.

**Pull request closed without merging**
