### PR TITLE
Added Numatune scenarios for migration - Version 2

### PR DESCRIPTION
**Pull request by balamuruhans**
This patch adds tests that will pin guest numa node with host numa 
node and performs live, online and live_there_and_back migration 
scenarios. It covers different memory modes strict, preferred and 
interleave. Memory placement is static currently.

### CODE REVIEW

**Comment by balamuruhans** [comment]
@waynesun09 @sathnaga  - Rebased #PR791

**Comment by balamuruhans** [comment]
#791

**Comment by balamuruhans** [comment]
@waynesun09 please help me in merging this PR

**Comment by waynesun09** [comment]
@balamuruhans merge now, thanks

**Pull request merged**
