### PR TITLE
Fix for func entry update

### PR DESCRIPTION
**Pull request by dzhengfy**
According to the update in https://github.com/avocado-framework/avocado-vt/pull/3466,
the scripts need to be updated.

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
@liuyd96 Could you help review?

**Comment by dzhengfy** [comment]
8.7 numa job


Test name | Duration | Status
-- | -- | --
unrelated_cpu_offline | 34 sec | Fixed

**Review by Yingshun — APPROVED** [review]

**Review by liuyd96 — APPROVED** [review]
Thanks.

**Comment by dzhengfy** [comment]
rerun 8.7
 (1/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.no_option: PASS (6.28 s)
 (2/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.disable_enable_vcpu: PASS (5.57 s)
 (3/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.unexpect_option: PASS (5.20 s)
 (4/4) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.with_libvirtd_stop: PASS (6.37 s)

**Pull request merged**
