### PR TITLE
Add more nwfilter test cases

### PR DESCRIPTION
**Pull request by waynesun09**

### CODE REVIEW

**Comment by waynesun09** [comment]
This depends on:
https://github.com/autotest/virt-test/pull/1982

**Comment by waynesun09** [comment]
# ./run -t libvirt --test nwfilter_define,nwfilter_edit_uuid,nwfilter_vm_start
Running setup. Please wait...
SETUP: PASS (25.21 s)
DATA DIR: /home/wayne/work/virt-test/shared/data
DEBUG LOG: /home/wayne/work/virt-test/logs/run-2015-01-22-17.20.50/debug.log
TESTS: 94
(1/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.variable_notation: PASS (19.65 s)
(2/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.ip_learning: PASS (40.86 s)
(3/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.chain_priority_greater_than_rule: PASS (28.52 s)
(4/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.dhcpserver_variable: PASS (28.48 s)
(5/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.no_other_l2_traffic: PASS (28.45 s)
(6/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.no_mac_spoofing: PASS (28.48 s)
(7/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.no_mac_broadcast: PASS (27.88 s)
(8/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.no_ip_spoofing: PASS (27.50 s)
(9/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.no_arp_spoofing: PASS (28.80 s)
(10/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.disallow_ipv6: PASS (28.89 s)
(11/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.disallow_dhcp: PASS (29.95 s)
(12/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.disallow_arp: PASS (28.80 s)
(13/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.clean_traffic: PASS (28.62 s)
(14/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.allow_ipv6: PASS (28.30 s)
(15/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.allow_dhcp: PASS (29.54 s)
(16/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.allow_ipv4: PASS (28.45 s)
(17/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.allow_incoming_ipv4: PASS (28.61 s)
(18/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.possitive_test.allow_arp: PASS (28.34 s)
(19/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.negative_test.ip_learning_err: PASS (5.79 s)
(20/94) type_specific.io-github-autotest-libvirt.nwfilter_vm_start.negative_test.dhcpserver_variable: PASS (6.26 s)
(21/94) type_specific.io-github-autotest-libvirt.nwfilter_edit_uuid: PASS (13.71 s)
(22/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.update_exist_filter.non_acl.with_uuid: PASS (19.18 s)
(23/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.update_exist_filter.non_acl.without_uuid: PASS (21.11 s)
(24/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.update_exist_filter.acl_test: PASS (23.62 s)
(25/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.acl_test: PASS (23.40 s)
(26/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.invalid_extra_option: PASS (20.96 s)
(27/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.no_xml_file: PASS (19.75 s)
(28/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.invalid_xml_file: PASS (20.68 s)
(29/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.invalid_rule_action: PASS (20.27 s)
(30/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.mac_test: PASS (21.17 s)
(31/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.arp_test: PASS (20.62 s)
(32/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.rarp_test: PASS (21.11 s)
(33/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.ip_test: PASS (19.96 s)
(34/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.ipv6_test: PASS (21.56 s)
(35/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.tcp_test: PASS (20.37 s)
(36/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.udp_test: PASS (21.56 s)
(37/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.sctp_test: PASS (20.24 s)
(38/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.tcp_ipv6_test: PASS (21.52 s)
(39/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.udp_ipv6_test: PASS (20.14 s)
(40/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.sctp_ipv6_test: PASS (21.38 s)
(41/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.icmp_test: PASS (20.29 s)
(42/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.icmpv6_test: PASS (21.48 s)
(43/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.ah_ipv6_test: PASS (20.31 s)
(44/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.all_ipv6_test: PASS (20.84 s)
(45/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.esp_ipv6_test: PASS (20.72 s)
(46/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.negative_test.boundary_test.udplite_ipv6_test: PASS (21.11 s)
(47/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.mac_test.non_acl: PASS (21.01 s)
(48/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.mac_test.acl_test: PASS (24.22 s)
(49/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.vlan_test.non_acl: PASS (21.37 s)
(50/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.vlan_test.acl_test: PASS (23.63 s)
(51/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.stp_test.non_acl: PASS (21.08 s)
(52/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.stp_test.acl_test: PASS (24.32 s)
(53/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.arp_test.non_acl: PASS (20.70 s)
(54/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.arp_test.acl_test: PASS (23.69 s)
(55/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.rarp_test.non_acl: PASS (20.98 s)
(56/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.rarp_test.acl_test: PASS (23.84 s)
(57/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ip_test.non_acl: PASS (21.49 s)
(58/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ip_test.acl_test: PASS (23.52 s)
(59/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ipv6_test.non_acl: PASS (20.70 s)
(60/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ipv6_test.acl_test: PASS (23.99 s)
(61/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.tcp_test.non_acl: PASS (20.61 s)
(62/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.tcp_test.acl_test: PASS (24.68 s)
(63/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udp_test.non_acl: PASS (20.29 s)
(64/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udp_test.acl_test: PASS (23.77 s)
(65/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.sctp_test.non_acl: PASS (20.67 s)
(66/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.sctp_test.acl_test: PASS (23.91 s)
(67/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.tcp_ipv6_test.non_acl: PASS (20.32 s)
(68/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.tcp_ipv6_test.acl_test: PASS (24.47 s)
(69/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udp_ipv6_test.non_acl: PASS (20.35 s)
(70/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udp_ipv6_test.acl_test: PASS (23.63 s)
(71/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.sctp_ipv6_test.non_acl: PASS (21.42 s)
(72/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.sctp_ipv6_test.acl_test: PASS (23.93 s)
(73/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.icmp_test.non_acl: PASS (20.59 s)
(74/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.icmp_test.acl_test: PASS (24.83 s)
(75/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.icmpv6_test.non_acl: PASS (20.29 s)
(76/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.icmpv6_test.acl_test: PASS (24.50 s)
(77/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.igmp_test.non_acl: PASS (21.21 s)
(78/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.igmp_test.acl_test: PASS (23.69 s)
(79/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.esp_test.non_acl: PASS (20.75 s)
(80/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.esp_test.acl_test: PASS (25.05 s)
(81/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ah_test.non_acl: PASS (20.13 s)
(82/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ah_test.acl_test: PASS (23.80 s)
(83/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udplite_test.non_acl: PASS (20.73 s)
(84/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udplite_test.acl_test: PASS (23.82 s)
(85/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.all_test.non_acl: PASS (20.43 s)
(86/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.all_test.acl_test: PASS (25.10 s)
(87/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ah_ipv6_test.non_acl: PASS (20.55 s)
(88/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.ah_ipv6_test.acl_test: PASS (23.78 s)
(89/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.all_ipv6_test.non_acl: PASS (21.37 s)
(90/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.all_ipv6_test.acl_test: PASS (23.62 s)
(91/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.esp_ipv6_test.non_acl: PASS (21.12 s)
(92/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.esp_ipv6_test.acl_test: PASS (24.29 s)
(93/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udplite_ipv6_test.non_acl: PASS (20.24 s)
(94/94) type_specific.io-github-autotest-libvirt.virsh.nwfilter_define.positive_test.udplite_ipv6_test.acl_test: PASS (23.92 s)
TOTAL TIME: 2144.29 s (35:44)
TESTS PASSED: 94
TESTS FAILED: 0
SUCCESS RATE: 100.00 %

**Comment by yumingfei** [comment]
Looks good in overview.
BTW, could you paste result for following added cases?

**Comment by waynesun09** [comment]
@yumingfei the result comment was updated with latest run result, which include all updates here.

**Comment by waynesun09** [comment]
This depends on:
https://github.com/autotest/virt-test/pull/1998

**Comment by waynesun09** [comment]
@yumingfei all updated, test result included, pls help check, thx.

**Comment by yumingfei** [comment]
OK, because you are the actual owner of nwfilter modules, I believe you judgement.
And it looks good enough from the result.
So applied and thank you~

**Pull request merged**
