### PR TITLE
aarch64: fix console connection issue on ARM

### PR DESCRIPTION
**Pull request by xiaodwan**

### CODE REVIEW

**Comment by xiaodwan** [comment]
```
JOB ID     : e6f43e4703ad266700b0ea9b479d7f23330c0b1c
JOB LOG    : /var/log/avocado/job-results/job-2024-06-28T03.36-e6f43e4/job.log
 (1/1) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.acl_test.valid_domid: PASS (175.70 s)
Not opening readers, lock_server_running not locked
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-06-28T03.36-e6f43e4/results.html
JOB TIME   : 176.24 s
```

**Comment by xiaodwan** [comment]
```
JOB ID     : 82b8fd33449de975ce512322aa9923a0493c976f
JOB LOG    : /var/log/avocado/job-results/job-2024-06-28T03.51-82b8fd3/job.log
 (1/6) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.non_acl.valid_domname: PASS (170.14 s)
 (2/6) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.non_acl.valid_domid: PASS (169.81 s)
 (3/6) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.non_acl.valid_domuuid: PASS (171.33 s)
 (4/6) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.acl_test.valid_domname: PASS (174.37 s)
 (5/6) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.acl_test.valid_domid: PASS (176.81 s)
 (6/6) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.acl_test.valid_domuuid: PASS (175.64 s)
Not opening readers, lock_server_running not locked
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/log/avocado/job-results/job-2024-06-28T03.51-82b8fd3/results.html
JOB TIME   : 1038.79 s
```

**Comment by xiaodwan** [comment]
@dzhengfy @Yingshun Please help to review, thanks.

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
