### PR TITLE
npiv: use existing npiv_utils code in test case

### PR DESCRIPTION
**Pull request by lento-sun**
The npiv methods were moved to avocado-vt/virttest/npiv_utils.py,
we should clean up the code here.

Signed-off-by: Yi Sun <yisun@redhat.com>

### CODE REVIEW

**Comment by lento-sun** [comment]
set as DRAFT for now since will add this pr to ci and have a double check. We meet some random failure recently about 'fdisk -l' hang. Will check if this pr will fix it with some test rounds.

**Comment by lento-sun** [comment]
Have executed some test rounds within our CI and previous failures not happened again.
https://<URI_OF_OUR_CI>/job/libvirt-RHEL-9.1-runtest-x86_64-function-npiv/43/testReport/
https://<URI_OF_OUR_CI>/job/libvirt-RHEL-9.1-runtest-x86_64-function-npiv/44/testReport/
https://<URI_OF_OUR_CI>/job/libvirt-RHEL-9.1-runtest-x86_64-function-npiv/45/testReport/

There is still one case failed, but not related to this patch.

**Comment by lento-sun** [comment]
@chloerh @chunfuwen could you pls help to review this pr, thx

**Review by chloerh — APPROVED** [review]

**Review by dzhengfy — APPROVED** [review]
LGTM

**Pull request merged**
