### PR TITLE
expand virsh_iothreaddel to cover related disk attach detach operations

### PR DESCRIPTION
**Pull request by carlsplace**
expand iothreaddel to cover RHEL7-23916.
All 12 cases(4 newly added) are PASSed on my local machine.

Signed-off-by: yachang <yachang@redhat.com>

### CODE REVIEW

**Comment by balamuruhans** [comment]
@carlsplace please squash some of code changes from commit: 7f4085e to 37ffdc4. I will be good to have commit message that explains appropriate code changes and testcase added for BZ1253108.

**Comment by carlsplace** [comment]
I squashed the commits. Sorry for being not able to explain things about BZ1253108, since this commit was added when I was intern in RedHat, and now I am not in RedHat any more.
As long as I can remember, I expanded the test case to cover more situations, and didn't change the code related to BZ1253108. You may have to contact other maintainer

**Comment by iccaszhulili** [comment]
rh-caselink retest please

**Comment by chunfuwen** [comment]
there is no update for too long time, close it

**Pull request closed without merging**
