### PR TITLE
Fixup: Handle new hwclock format

### PR DESCRIPTION
**Pull request by sathnaga**
Seems hwclock output format has changed in recent distributions,
let's handle it.

Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by sathnaga** [comment]
```
JOB LOG    : /home/sath/avocado-fvt-wrapper/results/job-2019-03-22T05.35-3d9ad4a/job.log
 (1/1) qemu.qcow2.virtio_scsi.smp2.virtio_net.Guest.RHEL.8.0.ppc64le.powerkvm-libvirt.virsh.domtime.positive.get_time: PASS (110.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 117.38 s
JOB HTML   : /home/sath/avocado-fvt-wrapper/results/job-2019-03-22T05.35-3d9ad4a/results.html
```

```
2019-03-22 05:37:11,497 client           L1126 DEBUG| Sending command: hwclock
2019-03-22 05:37:12,158 virsh_domtime    L0069 INFO | Result of command "hwclock". Duration: 0.660917043686. Output:2009-02-14 05:01:31.449705+05:30
2019-03-22 05:37:12,158 client           L1126 DEBUG| Sending command: date
2019-03-22 05:37:12,269 virsh_domtime    L0069 INFO | Result of command "date". Duration: 0.110804080963. Output:Sun Feb 15 05:01:32 IST 2009
2019-03-22 05:37:12,270 client           L1126 DEBUG| Sending command: date -u
2019-03-22 05:37:12,379 virsh_domtime    L0069 INFO | Result of command "date -u". Duration: 0.10933804512. Output:Sat Feb 14 23:31:32 UTC 2009
2019-03-22 05:37:12,424 virsh_domtime    L0135 INFO | Result of "domtime". Duration: 0.0401890277863. Output:Time: 2009-02-14 23:31:32
2019-03-22 05:37:12,425 virsh_domtime    L0206 DEBUG| Timezone diff on host is -4 hours.
2019-03-22 05:37:12,425 virsh_domtime    L0209 INFO | Add 0:00:01.176318s to expected guest time
2019-03-22 05:37:12,425 virsh_domtime    L0176 DEBUG| Time shift is 2.10442614555
2019-03-22 05:37:12,425 virsh_domtime    L0187 DEBUG| For domtime, expect get time 2009-02-14 23:31:31.163396, got 2009-02-14 23:31:31.072603, time diff: -0.090793
2019-03-22 05:37:12,425 virsh_domtime    L0187 DEBUG| For local_hw, expect get time 2009-02-14 05:01:30.430156, got 2009-02-14 05:01:30.338660, time diff: -0.091496
2019-03-22 05:37:12,426 virsh_domtime    L0187 DEBUG| For local_sys, expect get time 2009-02-15 05:01:31.320065, got 2009-02-15 05:01:31.227485, time diff: -0.09258
2019-03-22 05:37:12,426 virsh_domtime    L0187 DEBUG| For utc_sys, expect get time 2009-02-14 23:31:31.209572, got 2009-02-14 23:31:31.117800, time diff: -0.091772
2019-03-22 05:37:12,426 virsh_domtime    L0162 DEBUG| Time shift is 2.10547995567
```

**Comment by iccaszhulili** [comment]
@sathnaga  
Thx. Please also add the results of virsh.domtime cases here.

**Comment by sathnaga** [comment]
@iccaszhulili have given the result of run log details above for a single virsh.domtime subtest, hope that should be enough?

**Comment by iccaszhulili** [comment]
# avocado run --vt-type libvirt virsh.domtime 
JOB ID     : 0c190b36e97907e0e6da238a7f8873531567d9c8
JOB LOG    : /root/avocado/job-results/job-2019-04-17T04.13-0c190b3/job.log
 (01/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.get_time: PASS (52.54 s)
 (02/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.with_pretty: PASS (75.53 s)
 (03/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.set_time_now: PASS (72.87 s)
 (04/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.set_time_sync: PASS (79.52 s)
 (05/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.set_time: PASS (71.91 s)
 (06/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.set_time_max_1: PASS (72.93 s)
 (07/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.set_time_max_2: PASS (71.56 s)
 (08/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.set_time_max_3: PASS (75.57 s)
 (09/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.suspend_vm: PASS (86.53 s)
 (10/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.managedsave_vm: PASS (94.60 s)
 (11/21) type_specific.io-github-autotest-libvirt.virsh.domtime.positive.pmsuspend_vm: ERROR: Login timeout expired    (output: 'exceeded 240 s timeout, last failure: No ipv4 DHCP lease for MAC 52:54:00:6c:4d:78') (601.17 s)
 (12/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.shutdown_vm: PASS (70.49 s)
 (13/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.now_sync: PASS (57.54 s)
 (14/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.time_sync: PASS (73.55 s)
 (15/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.time_now: PASS (69.59 s)
 (16/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.no_agent_channel: PASS (68.84 s)
 (17/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.no_agent: PASS (72.67 s)
 (18/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.set_time_-1: PASS (69.56 s)
 (19/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.set_time_too_large: PASS (69.57 s)
 (20/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.readonly_test.get_time_readonly: PASS (76.54 s)
 (21/21) type_specific.io-github-autotest-libvirt.virsh.domtime.negative.readonly_test.set_time_readonly: PASS (84.54 s)
RESULTS    : PASS 20 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 2069.62 s
@kylazhang pmsuspend case failed because of pmwakeup process after pmsuspend does not work well, the pmsuspend feature belongs to S3/S4, will add it to blacklist afterwards

**Comment by waynesun09** [comment]
ACK

**Pull request merged**
