### PR TITLE
numa_topology_with_numa_distance: add case

### PR DESCRIPTION
**Pull request by dzhengfy**
This is to test guest numa topology with distance is working well.

Case ID: VIRT-296724

Signed-off-by: Dan Zheng <dzheng@redhat.com>

### CODE REVIEW

**Comment by dzhengfy** [comment]
libvirt v9.0.0
```
 (1/1) type_specific.io-github-autotest-libvirt.numa_topology_with_numa_distance.asymmetrical: PASS (215.13 s)
 (1/1) type_specific.io-github-autotest-libvirt.numa_topology_with_numa_distance.symmetrical: PASS (216.51 s)
```

**Review by chloerh — APPROVED** [review]

**Comment by dzhengfy** [comment]
depend on 
- https://github.com/autotest/tp-libvirt/pull/4870

 (1/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_numa_distance.symmetrical: PASS (47.78 s)
 (2/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_numa_distance.asymmetrical: PASS (59.34 s)

**Comment by dzhengfy** [comment]
Depend on 
- https://github.com/autotest/tp-libvirt/pull/4870

**Review by liang-cong-red-hat — COMMENTED** [review]
LGTM

**Pull request merged**
