### PR TITLE
virsh_migrate: memory hotplug/hotunplug with migration

### PR DESCRIPTION
**Pull request by balamuruhans**
added testcases that perform memory hotplug/hotunplug along with migration
of guests, testcases cover different scenarios as below,

1. memory hotplug before migration
2. memory hotplug after migration
3. memory hotplug & hotunplug before migration
4. memory hotplug & hotunplug after migration
5. memory hotplug before and hotunplug after migration
6. memory Hotplug & hotunplug before and hotplug & hotunplug after migration

Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
@balamuruhans , migration is relative complex cases, Could you have chance to upload test results for those newly added cases?

**Comment by balamuruhans** [comment]
@chunfuwen, sure I am working on it and I will upload the results for newly added cases.

**Comment by balamuruhans** [comment]
**Test result**
```
JOB ID     : d57990c32ccaf90c5c3358eac96fc3955081e0fa
JOB LOG    : /home/bala/avocado-fvt-wrapper/results/job-2017-12-22T19.57-d57990c/job.log
 (1/6) guest_migration.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-libvirt.virsh.migrate.there_live_with_numa.with_numa_only.with_memory_hotplug.with_hotplug.mem_hotplug_before_migration.without_cpu_hotplug.without_postcopy:  PASS (181.38 s)
 (2/6) guest_migration.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-libvirt.virsh.migrate.there_live_with_numa.with_numa_only.with_memory_hotplug.with_hotplug.mem_hotplug_after_migration.without_cpu_hotplug.without_postcopy:  PASS (189.00 s)
 (3/6) guest_migration.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-libvirt.virsh.migrate.there_live_with_numa.with_numa_only.with_memory_hotplug.with_hotunplug.hotplug_before_unplug_before_migration.without_cpu_hotplug.without_postcopy:  PASS (220.61 s)
 (4/6) guest_migration.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-libvirt.virsh.migrate.there_live_with_numa.with_numa_only.with_memory_hotplug.with_hotunplug.hotplug_before_unplug_after_migration.without_cpu_hotplug.without_postcopy:  PASS (227.19 s)
 (5/6) guest_migration.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-libvirt.virsh.migrate.there_live_with_numa.with_numa_only.with_memory_hotplug.with_hotunplug.hotplug_after_unplug_after_migration.without_cpu_hotplug.without_postcopy:  PASS (234.77 s)
 (6/6) guest_migration.qemu.qcow2.virtio_scsi.smp2.virtio_net.Pegas.1.0.ppc64le.powerkvm-libvirt.virsh.migrate.there_live_with_numa.with_numa_only.with_memory_hotplug.with_hotunplug.hotplug_unplug_before_hotplug_unplug_after.without_cpu_hotplug.without_postcopy:  PASS (273.32 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1331.70 s
JOB HTML   : /home/bala/avocado-fvt-wrapper/results/job-2017-12-22T19.57-d57990c/results.html
```

**Comment by dzhengfy** [comment]
@balamuruhans , could you provide your guest XML used in your test? I guest there maybe some differences between yours and ours which may make some scripts' failures. Thanks.

And another suggestion is that it is better to add new cases into new file because existing migrate_vm.py and virsh_migrate.py already have many lines which are inconvenient to maintain.

**Comment by balamuruhans** [comment]
> @balamuruhans , could you provide your guest XML used in your test? I guest there maybe some differences between yours and ours which may make some scripts' failures. Thanks.

@dzhengfy sure, I am attaching the guest xml here used for my tests.
[avocado-vt-vm1-migration.txt](https://github.com/autotest/tp-libvirt/files/1586685/avocado-vt-vm1-migration.txt)

> And another suggestion is that it is better to add new cases into new file because existing migrate_vm.py and virsh_migrate.py already have many lines which are inconvenient to maintain.

Agreed, we have a good infrastructure for Numa, HP in virsh_migrate.py so I used it. Going forward, we will add new test cases in new file. Thanks! for reviewing and testing the patch 👍

**Comment by chunfuwen** [comment]
Hi All,

It is better, if one separate cfg and python file were created,e.g hot_migrate.py, and it also can wrap :#1325,https://github.com/autotest/tp-libvirt/pull/1465 into it

**Comment by chunfuwen** [comment]
@balamuruhans ,please rebase code to resolve the conflict

**Comment by iccaszhulili** [comment]
rh-caselink retest please

**Comment by sathnaga** [comment]
@balamuruhans needs rebase

**Comment by dzhengfy** [comment]
After confirmation with the IBM PPC FVT lead that the author does not work on this any more and the pr is not in use by them. So I close it.

**Pull request closed without merging**
