### PR TITLE
Fix up inspekt check failures

### PR DESCRIPTION
**Pull request by Yingshun**
Fix up E275 errors to work with the latest pycodestyle(2.9.0).

Signed-off-by: Yingshun Cui <yicui@redhat.com>

### CODE REVIEW

**Review by chloerh — APPROVED** [review]

**Review by dzhengfy — APPROVED** [review]
LGTM

**Review by nanli1 — APPROVED** [review]

**Review by cliping — APPROVED** [review]

**Comment by chunfuwen** [comment]
Could add some explanation in the commit message or description what or why leads to this change?

**Comment by Yingshun** [comment]
> Could add some explanation in the commit message or description what or why leads to this change?

Added.

**Review by chunfuwen — APPROVED** [review]
LGTM

**Pull request merged**
