### PR TITLE
virsh_domcapabilities: traverse all arch and not just test the first.

### PR DESCRIPTION
**Pull request by Chenditang**
At present, the case just test the first arch, we should test all.

### CODE REVIEW

**Comment by Chenditang** [comment]
\# ./run -t libvirt --no-downloads -k --tests virsh.domcapabilities
SETUP: PASS (0.00 s)
DATA DIR: /var/lib/virt_test
DEBUG LOG: /root/autotest/client/tests/virt/logs/run-2015-12-18-11.01.20/debug.log
TESTS: 9
(1/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.positive_test.local_host.default_option_values: PASS (10.34 s)
(2/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.positive_test.local_host.auto_option_values: PASS (12.98 s)
(3/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.positive_test.remote_host.default_option_values: PASS (11.75 s)
(4/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.positive_test.remote_host.auto_option_values: PASS (33.49 s)
(5/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.negative_test.invalid_option: PASS (11.56 s)
(6/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.negative_test.invalid_virttype: PASS (11.41 s)
(7/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.negative_test.invalid_emulatorbin: PASS (11.47 s)
(8/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.negative_test.invalid_arch: PASS (11.53 s)
(9/9) type_specific.io-github-autotest-libvirt.virsh.domcapabilities.negative_test.invalid_machine: PASS (11.33 s)
TOTAL TIME: 125.92 s (02:05)
TESTS PASSED: 9
TESTS FAILED: 0
SUCCESS RATE: 100 %

**Comment by will-Do** [comment]
Patch is good, could you please update the commit summary?

**Comment by Chenditang** [comment]
@will-Do 
updated, Thanks~~

**Comment by waynesun09** [comment]
ACK

**Pull request merged**
