### PR TITLE
virsh_domif_setlink_getlink: Use 'ip link' to set link state in guest.

### PR DESCRIPTION
**Pull request by rbian**

### CODE REVIEW

**Comment by yumingfei** [comment]
Do they have discrepancy may trouble the test?

**Comment by rbian** [comment]
Ifup script also call "ip link" to set link state, but ifup use the interface name which should have a configuration file, otherwise it will report error.
For example:
if we use "ifup eth2", but there is no ifcfg-eth2 on /etc/sysconfig/network-scripts/, we can't get the right result.

**Comment by yumingfei** [comment]
OK.

**Comment by chuanchang** [comment]
ACKed.

**Comment by will-Do** [comment]
Patch is good, I guess you can amend your patch description to add the detail reason just like you said in comment 2

**Comment by rbian** [comment]
Thanks @will-Do , updated the patch.

**Comment by waynesun09** [comment]
ACK

**Comment by will-Do** [comment]
Thx all, merge this PR

**Pull request merged**
